import type { NaxosGuideArticle } from "@/types/content";
import { ls } from "./_shared";

/** "Explore" cluster — the beaches, villages and mountains. Highest search volume. */
export const EXPLORE_ARTICLES: NaxosGuideArticle[] = [
  {
    slug: "best-beaches-in-naxos",
    cluster: "explore",
    title: ls(
      "The 14 best beaches in Naxos 2026, ranked and mapped",
      "Οι 14 καλύτερες παραλίες της Νάξου 2026",
      "Le 14 migliori spiagge di Naxos 2026",
      "Les 14 plus belles plages de Naxos en 2026",
      "Die 14 besten Strände auf Naxos 2026",
    ),
    excerpt: ls(
      "Every beach with its distance from Chora, whether the bus reaches it, how sheltered it is from the meltemi, and who it actually suits.",
      "Κάθε παραλία με την απόσταση από τη Χώρα, αν την εξυπηρετεί λεωφορείο, πόσο προστατευμένη είναι από το μελτέμι και σε ποιους ταιριάζει.",
      "Ogni spiaggia con la distanza da Chora, se è servita dall'autobus, quanto è riparata dal meltemi e a chi si adatta.",
      "Chaque plage avec sa distance de Chora, sa desserte en bus, son abri du meltemi et à qui elle convient.",
      "Jeder Strand mit Entfernung von Chora, Busanbindung, Schutz vor dem Meltemi und für wen er passt.",
    ),
    answer: ls(
      "Agios Prokopios is the best all-rounder, Plaka the best long quiet stretch, Agia Anna the best for families with tavernas at the sand, Mikri Vigla the kitesurf beach, and Alyko the most beautiful  -  a cedar forest above three wild coves. All five sit on the west coast within 25 minutes of Chora. When the meltemi blows, switch to Moutsouna or Panormos in the east.",
      "Ο Άγιος Προκόπιος είναι η καλύτερη συνολικά, η Πλάκα η μεγαλύτερη και πιο ήσυχη, η Αγία Άννα η καλύτερη για οικογένειες, η Μικρή Βίγλα για kitesurf και το Αλυκό η ομορφότερη. Και οι πέντε βρίσκονται στη δυτική ακτή σε 25 λεπτά από τη Χώρα. Με μελτέμι, στραφείτε στη Μουτσούνα ή τον Πάνορμο.",
      "Agios Prokopios è la migliore in assoluto, Plaka la più lunga e tranquilla, Agia Anna la migliore per famiglie, Mikri Vigla per il kitesurf e Alyko la più bella. Tutte e cinque sulla costa ovest entro 25 minuti da Chora. Col meltemi, spostati a Moutsouna o Panormos.",
      "Agios Prokopios est la meilleure globalement, Plaka la plus longue et tranquille, Agia Anna la meilleure en famille, Mikri Vigla pour le kitesurf et Alyko la plus belle. Toutes les cinq sur la côte ouest à moins de 25 minutes de Chora. Par meltemi, allez à Moutsouna ou Panormos.",
      "Agios Prokopios ist der beste Allrounder, Plaka der längste und ruhigste, Agia Anna der beste für Familien, Mikri Vigla der Kitesurf-Strand und Alyko der schönste. Alle fünf liegen an der Westküste, höchstens 25 Minuten von Chora. Bei Meltemi weichen Sie nach Moutsouna oder Panormos aus.",
    ),
    hero: "/images/naxos/plaka-beach.jpg",
    publishedAt: "2026-08-22",
    updatedAt: "2026-08-22",
    readingTime: 13,
    keywords: [
      "best beaches in naxos",
      "naxos beaches",
      "naxos best beaches",
      "plaka beach naxos",
      "agios prokopios beach",
      "alyko naxos",
    ],
    related: ["things-to-do-in-naxos", "naxos-travel-guide", "naxos-itinerary", "best-time-to-visit-naxos"],
    vehiclePicks: ["hyundai-i10", "fiat-500-cabrio", "citroen-berlingo-7"],
    locationPicks: ["agios-prokopios", "agia-anna", "plaka", "mikri-vigla"],
    table: {
      caption: ls(
        "Naxos beaches compared",
        "Σύγκριση παραλιών Νάξου",
        "Spiagge di Naxos a confronto",
        "Comparatif des plages de Naxos",
        "Naxos-Strände im Vergleich",
      ),
      columns: [
        ls("Beach", "Παραλία", "Spiaggia", "Plage", "Strand"),
        ls("From Chora", "Από Χώρα", "Da Chora", "De Chora", "Ab Chora"),
        ls("Bus?", "Λεωφορείο;", "Autobus?", "Bus ?", "Bus?"),
        ls("Wind shelter", "Προστασία από αέρα", "Riparo dal vento", "Abri du vent", "Windschutz"),
        ls("Best for", "Ιδανική για", "Ideale per", "Idéale pour", "Ideal für"),
      ],
      rows: [
        [ls("Agios Georgios"), ls("Walk", "Με τα πόδια", "A piedi", "À pied", "Zu Fuß"), ls("Yes", "Ναι", "Sì", "Oui", "Ja"), ls("Good", "Καλή", "Buono", "Bon", "Gut"), ls("Toddlers, late swims", "Νήπια, βραδινό μπάνιο", "Bimbi piccoli, bagni serali", "Tout-petits, baignades tardives", "Kleinkinder, späte Bäder")],
        [ls("Agios Prokopios"), ls("6 km"), ls("Yes", "Ναι", "Sì", "Oui", "Ja"), ls("Good", "Καλή", "Buono", "Bon", "Gut"), ls("All-rounder", "Συνολικά", "Tutto", "Polyvalence", "Allrounder")],
        [ls("Agia Anna"), ls("7 km"), ls("Yes", "Ναι", "Sì", "Oui", "Ja"), ls("Good", "Καλή", "Buono", "Bon", "Gut"), ls("Families, tavernas", "Οικογένειες, ταβέρνες", "Famiglie, taverne", "Familles, tavernes", "Familien, Tavernen")],
        [ls("Plaka"), ls("8 km"), ls("Limited", "Περιορισμένο", "Limitato", "Limité", "Eingeschränkt"), ls("Moderate", "Μέτρια", "Medio", "Moyen", "Mäßig"), ls("Long quiet walks", "Μεγάλοι ήσυχοι περίπατοι", "Lunghe passeggiate", "Longues promenades", "Lange ruhige Spaziergänge")],
        [ls("Kastraki"), ls("14 km"), ls("No", "Όχι", "No", "Non", "Nein"), ls("Low", "Χαμηλή", "Basso", "Faible", "Gering"), ls("Solitude", "Ερημιά", "Solitudine", "Solitude", "Einsamkeit")],
        [ls("Mikri Vigla"), ls("17 km"), ls("No", "Όχι", "No", "Non", "Nein"), ls("None (south side)", "Καθόλου (νότια)", "Nessuno (lato sud)", "Aucun (côté sud)", "Keiner (Südseite)"), ls("Kitesurf, windsurf", "Kitesurf, windsurf", "Kitesurf, windsurf", "Kitesurf, planche", "Kite- und Windsurfen")],
        [ls("Alyko"), ls("21 km"), ls("No", "Όχι", "No", "Non", "Nein"), ls("Good", "Καλή", "Buono", "Bon", "Gut"), ls("Scenery, seclusion", "Τοπίο, απομόνωση", "Paesaggio, isolamento", "Paysage, isolement", "Landschaft, Abgeschiedenheit")],
        [ls("Pyrgaki"), ls("22 km"), ls("No", "Όχι", "No", "Non", "Nein"), ls("Good", "Καλή", "Buono", "Bon", "Gut"), ls("Sunset, quiet", "Ηλιοβασίλεμα, ησυχία", "Tramonto, quiete", "Coucher de soleil, calme", "Sonnenuntergang, Ruhe")],
        [ls("Moutsouna"), ls("38 km"), ls("No", "Όχι", "No", "Non", "Nein"), ls("Excellent", "Εξαιρετική", "Eccellente", "Excellent", "Ausgezeichnet"), ls("Windy days, fish", "Ημέρες με αέρα, ψάρι", "Giornate ventose, pesce", "Jours de vent, poisson", "Windige Tage, Fisch")],
      ],
    },
    sections: [
      {
        heading: ls(
          "Agios Prokopios  -  the one to go to first",
          "Άγιος Προκόπιος  -  η πρώτη επιλογή",
          "Agios Prokopios  -  la prima scelta",
          "Agios Prokopios  -  le premier choix",
          "Agios Prokopios  -  der erste Strand",
        ),
        body: ls(
          "Six kilometres south of Chora and regularly rated among the best beaches in Greece, Agios Prokopios is 1.5 km of fine pale sand with water that stays clear and waist-deep an improbable distance out. It has everything organised  -  sunbeds, several beach bars, tavernas across the road, showers  -  without feeling like a resort, because the village behind it is small and low-rise. The bus runs here every hour in summer and parking is easy outside July and August. If you only get one beach day on Naxos, spend it here: it is the most reliable combination of good sand, calm water and somewhere decent to eat lunch on the whole island.",
          "Έξι χιλιόμετρα νότια της Χώρας, ο Άγιος Προκόπιος είναι 1,5 χλμ. ψιλής άμμου με καθαρά, ρηχά νερά. Έχει ξαπλώστρες, beach bars, ταβέρνες και ντουζιέρες χωρίς να μοιάζει με θέρετρο. Το λεωφορείο περνά κάθε ώρα το καλοκαίρι. Αν έχετε μόνο μία ημέρα παραλίας, περάστε την εδώ.",
          "Sei chilometri a sud di Chora, Agios Prokopios è 1,5 km di sabbia fine con acqua limpida e bassa a lungo. Ha lettini, beach bar, taverne e docce senza sembrare un resort. L'autobus passa ogni ora d'estate. Se hai una sola giornata di mare, passala qui.",
          "À six kilomètres au sud de Chora, Agios Prokopios offre 1,5 km de sable fin avec une eau claire et peu profonde très loin. Transats, bars de plage, tavernes et douches sans allure de station balnéaire. Le bus passe toutes les heures l'été. Si vous n'avez qu'une journée plage, passez-la ici.",
          "Sechs Kilometer südlich von Chora bietet Agios Prokopios 1,5 km feinen Sand mit klarem, lange flachem Wasser. Liegen, Strandbars, Tavernen und Duschen  -  ohne Resortcharakter. Der Bus fährt im Sommer stündlich. Wenn Sie nur einen Strandtag haben: hier.",
        ),
      },
      {
        heading: ls(
          "Agia Anna and Plaka  -  the long southern run",
          "Αγία Άννα και Πλάκα  -  η μεγάλη νότια αμμουδιά",
          "Agia Anna e Plaka  -  la lunga distesa a sud",
          "Agia Anna et Plaka  -  la longue étendue au sud",
          "Agia Anna und Plaka  -  der lange Südabschnitt",
        ),
        body: ls(
          "Agia Anna picks up where Prokopios ends: a small fishing harbour with tavernas literally on the sand, which makes it the easiest beach on the island to spend a whole day at with children. Keep walking south and Agia Anna becomes Plaka without any obvious boundary  -  and Plaka runs for almost four kilometres, broad enough that even in mid-August the middle section stays genuinely uncrowded. The southern half is naturist by long-standing local convention. Bus frequency to Plaka varies by season, so a car makes it far more practical; park along the access road and pick your own spot rather than the first beach bar you reach. Together these two are the best argument for basing yourself south of Chora.",
          "Η Αγία Άννα συνεχίζει εκεί που τελειώνει ο Προκόπιος: μικρό ψαρολίμανο με ταβέρνες πάνω στην άμμο, ιδανικό για ολόκληρη ημέρα με παιδιά. Συνεχίζοντας νότια γίνεται Πλάκα, που εκτείνεται σχεδόν τέσσερα χιλιόμετρα και παραμένει αραιή ακόμη και τον Αύγουστο. Το νότιο μισό είναι παραδοσιακά γυμνιστών. Τα δρομολόγια ποικίλλουν  -  το αυτοκίνητο βοηθά πολύ.",
          "Agia Anna riprende dove finisce Prokopios: un porticciolo con taverne sulla sabbia, ideale per una giornata intera con bambini. Proseguendo a sud diventa Plaka, quasi quattro chilometri che restano poco affollati anche ad agosto. La metà sud è tradizionalmente naturista. Le corse variano  -  l'auto aiuta molto.",
          "Agia Anna prend le relais de Prokopios : un petit port de pêche avec des tavernes sur le sable, idéal pour une journée entière en famille. Vers le sud, elle devient Plaka, près de quatre kilomètres qui restent peu fréquentés même en août. La moitié sud est traditionnellement naturiste. Les bus varient  -  la voiture aide beaucoup.",
          "Agia Anna schließt an Prokopios an: ein kleiner Fischerhafen mit Tavernen direkt am Sand, ideal für einen ganzen Tag mit Kindern. Weiter südlich wird daraus Plaka  -  fast vier Kilometer, die selbst im August nicht überfüllt sind. Die Südhälfte ist traditionell FKK. Die Busfrequenz schwankt  -  ein Auto hilft sehr.",
        ),
      },
      {
        heading: ls(
          "Alyko  -  the cedar forest and the painted hotel",
          "Αλυκό  -  το κεδρόδασος και το ζωγραφισμένο ξενοδοχείο",
          "Alyko  -  la foresta di cedri e l'hotel dipinto",
          "Alyko  -  la forêt de cèdres et l'hôtel peint",
          "Alyko  -  der Zedernwald und das bemalte Hotel",
        ),
        body: ls(
          "Alyko is the most beautiful place on the Naxos coast and the least like anywhere else in the Cyclades: a protected forest of juniper and cedar growing straight out of the dunes on a headland, with three small beaches tucked below it and water the colour of a swimming pool. Inside the forest stands the shell of a hotel abandoned mid-construction in the 1970s, every wall of which has since been covered in murals  -  entirely unofficial, constantly changing, and genuinely worth the walk. Park at the signed area on the paved road and go in on foot; the sand tracks beyond are excluded from every rental agreement on the island and the tow-out is expensive. Bring water and shade  -  there are no facilities at all.",
          "Το Αλυκό είναι το ομορφότερο σημείο της ναξιώτικης ακτής: προστατευόμενο δάσος κέδρων πάνω στους αμμόλοφους, με τρεις μικρές παραλίες από κάτω και νερά χρώματος πισίνας. Μέσα στο δάσος στέκει το κέλυφος ενός ημιτελούς ξενοδοχείου του 1970, καλυμμένο με τοιχογραφίες. Παρκάρετε στο σηματοδοτημένο σημείο και συνεχίστε με τα πόδια  -  οι αμμώδεις δρόμοι εξαιρούνται από κάθε συμβόλαιο ενοικίασης. Δεν υπάρχουν παροχές.",
          "Alyko è il punto più bello della costa di Naxos: una foresta protetta di cedri sulle dune, con tre piccole spiagge sotto e acqua color piscina. Nella foresta c'è lo scheletro di un hotel incompiuto degli anni '70, ricoperto di murales. Parcheggia nell'area segnalata e prosegui a piedi  -  le piste sabbiose sono escluse da ogni contratto di noleggio. Nessun servizio.",
          "Alyko est le plus bel endroit de la côte de Naxos : une forêt protégée de cèdres sur les dunes, trois petites plages en contrebas et une eau couleur piscine. Dans la forêt se dresse la carcasse d'un hôtel inachevé des années 1970, couverte de fresques. Garez-vous à l'aire signalée et continuez à pied  -  les pistes de sable sont exclues de tout contrat de location. Aucun service.",
          "Alyko ist der schönste Ort an der Küste von Naxos: ein geschützter Zedernwald auf den Dünen, darunter drei kleine Strände und Wasser in Poolfarbe. Im Wald steht die Ruine eines in den 1970ern unvollendeten Hotels, überzogen von Wandbildern. Parken Sie am ausgeschilderten Platz und gehen Sie zu Fuß weiter  -  Sandpisten sind von jedem Mietvertrag ausgeschlossen. Keinerlei Einrichtungen.",
        ),
      },
      {
        heading: ls(
          "Mikri Vigla  -  two beaches, two completely different days",
          "Μικρή Βίγλα  -  δύο παραλίες, δύο διαφορετικές ημέρες",
          "Mikri Vigla  -  due spiagge, due giornate diverse",
          "Mikri Vigla  -  deux plages, deux journées différentes",
          "Mikri Vigla  -  zwei Strände, zwei völlig verschiedene Tage",
        ),
        body: ls(
          "A rocky headland 17 km south of Chora splits Mikri Vigla in two, and the difference between the sides is dramatic. The north face (Parthena) is sheltered, shallow and calm  -  a good family beach. The south face (Sahara) takes the full meltemi and is one of Europe's better-known kitesurf and windsurf spots, with schools operating through the summer and 30 or more kites in the air on a strong afternoon. Even if you have no intention of getting on a board, it is worth driving down to watch. The paved road ends at a signed car park; walk from there. No organised sunbeds on the south side, so bring shade.",
          "Ένα βραχώδες ακρωτήρι 17 χλμ. νότια της Χώρας χωρίζει τη Μικρή Βίγλα στα δύο. Η βόρεια πλευρά (Παρθένα) είναι προστατευμένη και ρηχή, ιδανική για οικογένειες. Η νότια (Σαχάρα) δέχεται το μελτέμι και είναι από τα γνωστότερα σημεία kitesurf της Ευρώπης. Αξίζει η επίσκεψη ακόμη και μόνο για θέαμα. Ο ασφαλτοστρωμένος δρόμος τελειώνει σε πάρκινγκ.",
          "Un promontorio roccioso a 17 km da Chora divide Mikri Vigla in due. Il lato nord (Parthena) è riparato e basso, ottimo per famiglie. Il lato sud (Sahara) prende il meltemi ed è tra i più noti spot di kitesurf d'Europa. Vale la visita anche solo per guardare. La strada asfaltata termina in un parcheggio.",
          "Un promontoire rocheux à 17 km de Chora coupe Mikri Vigla en deux. Le côté nord (Parthena) est abrité et peu profond, très bien en famille. Le côté sud (Sahara) prend le meltemi et compte parmi les spots de kitesurf les plus connus d'Europe. Cela vaut le détour rien que pour regarder. La route goudronnée s'arrête à un parking.",
          "Eine Felsnase 17 km südlich von Chora teilt Mikri Vigla in zwei Hälften. Die Nordseite (Parthena) ist geschützt und flach  -  gut für Familien. Die Südseite (Sahara) bekommt den vollen Meltemi und ist einer der bekannteren Kitesurf-Spots Europas. Schon zum Zuschauen lohnt die Fahrt. Die asphaltierte Straße endet an einem Parkplatz.",
        ),
      },
      {
        heading: ls(
          "When the meltemi blows: go east",
          "Όταν φυσά μελτέμι: πηγαίνετε ανατολικά",
          "Quando soffia il meltemi: vai a est",
          "Quand le meltemi souffle : allez à l'est",
          "Wenn der Meltemi weht: nach Osten",
        ),
        body: ls(
          "This is the single most useful thing to know about beaches on Naxos. The meltemi comes from the north-northeast, and the entire west coast  -  every beach above  -  is exposed to it. On a 6–7 Beaufort day, sand blows, umbrellas fold and the water goes choppy from Agios Prokopios all the way to Pyrgaki. Meanwhile the east coast is in the lee of the mountains and completely calm. Drive to Moutsouna (55 minutes over the pass, and a spectacular drive in itself) or Panormos in the far south-east, and you will find flat water and almost nobody. Check any wind app each morning: if it shows more than 5 Beaufort from the north, the day plans itself.",
          "Αυτό είναι το πιο χρήσιμο που πρέπει να ξέρετε. Το μελτέμι έρχεται από βορειοανατολικά και όλη η δυτική ακτή είναι εκτεθειμένη. Με 6–7 μποφόρ, η άμμος σηκώνεται και τα νερά ταράζονται. Η ανατολική ακτή όμως είναι υπήνεμη. Οδηγήστε στη Μουτσούνα (55 λεπτά) ή στον Πάνορμο και θα βρείτε ήρεμα νερά και σχεδόν κανέναν.",
          "È la cosa più utile da sapere. Il meltemi arriva da nord-nordest e tutta la costa ovest è esposta. Con 6–7 Beaufort la sabbia vola e il mare si increspa. La costa est però è sottovento. Guida fino a Moutsouna (55 minuti) o Panormos e troverai acqua piatta e quasi nessuno.",
          "C'est la chose la plus utile à savoir. Le meltemi vient du nord-nord-est et toute la côte ouest y est exposée. À 6–7 Beaufort, le sable vole et la mer se forme. La côte est, elle, est sous le vent. Roulez jusqu'à Moutsouna (55 minutes) ou Panormos : eau plate et presque personne.",
          "Das ist das Nützlichste, was Sie wissen können. Der Meltemi kommt aus Nordnordost, und die gesamte Westküste liegt frei. Bei 6–7 Beaufort fliegt der Sand und das Wasser wird kabbelig. Die Ostküste liegt jedoch im Windschatten. Fahren Sie nach Moutsouna (55 Minuten) oder Panormos: glattes Wasser und fast niemand.",
        ),
      },
    ],
    faq: [
      {
        q: ls(
          "Which is the best beach in Naxos?",
          "Ποια είναι η καλύτερη παραλία της Νάξου;",
          "Qual è la spiaggia più bella di Naxos?",
          "Quelle est la plus belle plage de Naxos ?",
          "Welcher ist der beste Strand auf Naxos?",
        ),
        a: ls(
          "Agios Prokopios for the best all-round day, Alyko for the most beautiful setting. Prokopios has the sand, the shallow water and somewhere to eat; Alyko has the cedar forest, the painted hotel and no facilities at all. Most visitors should do both.",
          "Ο Άγιος Προκόπιος για την καλύτερη συνολικά ημέρα, το Αλυκό για το ομορφότερο τοπίο. Ο Προκόπιος έχει άμμο, ρηχά νερά και φαγητό· το Αλυκό έχει το κεδρόδασος και καμία παροχή.",
          "Agios Prokopios per la giornata migliore, Alyko per lo scenario più bello. Prokopios ha sabbia, acqua bassa e dove mangiare; Alyko ha la foresta di cedri e nessun servizio.",
          "Agios Prokopios pour la meilleure journée, Alyko pour le plus beau décor. Prokopios a le sable, l'eau peu profonde et de quoi manger ; Alyko a la forêt de cèdres et aucun service.",
          "Agios Prokopios für den besten Gesamttag, Alyko für die schönste Kulisse. Prokopios hat Sand, flaches Wasser und Essen; Alyko den Zedernwald und keinerlei Einrichtungen.",
        ),
      },
      {
        q: ls(
          "Are Naxos beaches sandy or pebbly?",
          "Οι παραλίες της Νάξου είναι αμμώδεις ή με βότσαλα;",
          "Le spiagge di Naxos sono sabbiose o di ciottoli?",
          "Les plages de Naxos sont-elles de sable ou de galets ?",
          "Sind die Strände auf Naxos sandig oder kiesig?",
        ),
        a: ls(
          "Overwhelmingly sandy, and this is what sets Naxos apart from Santorini and much of Mykonos. The whole west coast from Agios Georgios to Pyrgaki is fine pale sand with a gentle shelf. A few east-coast and northern beaches have pebbles, but the ones people visit do not.",
          "Κατά κύριο λόγο αμμώδεις, και αυτό ξεχωρίζει τη Νάξο από τη Σαντορίνη. Όλη η δυτική ακτή από τον Άγιο Γεώργιο έως το Πυργάκι είναι ψιλή άμμος με ήπια κλίση.",
          "Prevalentemente sabbiose, ed è ciò che distingue Naxos da Santorini. Tutta la costa ovest da Agios Georgios a Pyrgaki è sabbia fine con fondale dolce.",
          "Très majoritairement sableuses, et c'est ce qui distingue Naxos de Santorin. Toute la côte ouest d'Agios Georgios à Pyrgaki est du sable fin en pente douce.",
          "Ganz überwiegend sandig  -  das unterscheidet Naxos von Santorin. Die gesamte Westküste von Agios Georgios bis Pyrgaki ist feiner Sand mit flachem Einstieg.",
        ),
      },
      {
        q: ls(
          "Can you get to Naxos beaches by bus?",
          "Μπορείτε να πάτε στις παραλίες της Νάξου με λεωφορείο;",
          "Si raggiungono le spiagge di Naxos in autobus?",
          "Peut-on rejoindre les plages de Naxos en bus ?",
          "Erreicht man die Strände von Naxos mit dem Bus?",
        ),
        a: ls(
          "Agios Georgios, Agios Prokopios and Agia Anna, yes  -  hourly in July and August. Plaka has limited service that varies by season. Kastraki, Mikri Vigla, Alyko, Pyrgaki, Moutsouna and Panormos have no useful bus service at all, and those are five of the best beaches on the island.",
          "Στον Άγιο Γεώργιο, τον Άγιο Προκόπιο και την Αγία Άννα ναι, κάθε ώρα τον Ιούλιο και τον Αύγουστο. Η Πλάκα έχει περιορισμένα δρομολόγια. Καστράκι, Μικρή Βίγλα, Αλυκό, Πυργάκι, Μουτσούνα και Πάνορμος δεν εξυπηρετούνται.",
          "Agios Georgios, Agios Prokopios e Agia Anna sì, ogni ora a luglio e agosto. Plaka ha corse limitate. Kastraki, Mikri Vigla, Alyko, Pyrgaki, Moutsouna e Panormos non sono serviti.",
          "Agios Georgios, Agios Prokopios et Agia Anna oui, toutes les heures en juillet-août. Plaka a un service limité. Kastraki, Mikri Vigla, Alyko, Pyrgaki, Moutsouna et Panormos ne sont pas desservis.",
          "Agios Georgios, Agios Prokopios und Agia Anna ja, im Juli und August stündlich. Plaka hat eingeschränkten Verkehr. Kastraki, Mikri Vigla, Alyko, Pyrgaki, Moutsouna und Panormos werden nicht bedient.",
        ),
      },
      {
        q: ls(
          "Which Naxos beach is best for young children?",
          "Ποια παραλία της Νάξου είναι καλύτερη για μικρά παιδιά;",
          "Quale spiaggia di Naxos è migliore per bambini piccoli?",
          "Quelle plage de Naxos convient le mieux aux jeunes enfants ?",
          "Welcher Strand auf Naxos eignet sich für kleine Kinder?",
        ),
        a: ls(
          "Agia Anna. The water is shallow for a long way out, the tavernas are directly on the sand so lunch and shade are twenty steps away, and the small harbour breaks up the swell. Agios Georgios in Chora is the runner-up and is walkable from most town accommodation.",
          "Η Αγία Άννα. Τα νερά είναι ρηχά για μεγάλη απόσταση, οι ταβέρνες βρίσκονται πάνω στην άμμο και το μικρό λιμάνι κόβει τον κυματισμό. Δεύτερος ο Άγιος Γεώργιος στη Χώρα.",
          "Agia Anna. L'acqua resta bassa a lungo, le taverne sono sulla sabbia e il porticciolo smorza le onde. Secondo posto Agios Georgios a Chora.",
          "Agia Anna. L'eau reste peu profonde très loin, les tavernes sont sur le sable et le petit port casse la houle. Agios Georgios à Chora arrive second.",
          "Agia Anna. Das Wasser bleibt lange flach, die Tavernen stehen direkt am Sand und der kleine Hafen bricht die Wellen. Zweiter ist Agios Georgios in Chora.",
        ),
      },
      {
        q: ls(
          "Are there nudist beaches in Naxos?",
          "Υπάρχουν παραλίες γυμνιστών στη Νάξο;",
          "Ci sono spiagge naturiste a Naxos?",
          "Y a-t-il des plages naturistes à Naxos ?",
          "Gibt es FKK-Strände auf Naxos?",
        ),
        a: ls(
          "Yes, by long-standing local convention rather than formal designation: the southern half of Plaka, parts of Alyko and the quieter stretches of Kastraki. Nobody minds either way, and the convention is well understood locally.",
          "Ναι, βάσει μακροχρόνιας τοπικής συνήθειας παρά επίσημου χαρακτηρισμού: το νότιο μισό της Πλάκας, τμήματα του Αλυκού και τα πιο ήσυχα σημεία του Καστρακίου.",
          "Sì, per consuetudine locale più che per designazione ufficiale: la metà sud di Plaka, parti di Alyko e i tratti più tranquilli di Kastraki.",
          "Oui, par convention locale plutôt que par désignation officielle : la moitié sud de Plaka, des parties d'Alyko et les portions calmes de Kastraki.",
          "Ja, aus langjähriger örtlicher Gewohnheit statt offizieller Ausweisung: die Südhälfte von Plaka, Teile von Alyko und die ruhigeren Abschnitte von Kastraki.",
        ),
      },
      {
        q: ls(
          "Is the sea warm enough to swim in Naxos in May or October?",
          "Είναι αρκετά ζεστή η θάλασσα για κολύμπι τον Μάιο ή τον Οκτώβριο;",
          "Il mare è abbastanza caldo per nuotare a Naxos a maggio o ottobre?",
          "La mer est-elle assez chaude pour nager à Naxos en mai ou octobre ?",
          "Ist das Meer im Mai oder Oktober warm genug zum Schwimmen?",
        ),
        a: ls(
          "In October, yes  -  the sea holds around 22–23°C into mid-month after a summer of heating, which is warmer than most of the Mediterranean in June. Early May is around 18–19°C: swimmable for the hardy, brisk for everyone else. Late May onwards is comfortable.",
          "Τον Οκτώβριο ναι  -  η θάλασσα κρατά περίπου 22–23°C έως τα μέσα του μήνα. Στις αρχές Μαΐου είναι περίπου 18–19°C: κολυμπάτε αν αντέχετε. Από τα τέλη Μαΐου και μετά είναι άνετα.",
          "A ottobre sì  -  il mare resta sui 22–23°C fino a metà mese. A inizio maggio è sui 18–19°C: si nuota se si è coraggiosi. Da fine maggio in poi è confortevole.",
          "En octobre oui  -  la mer reste vers 22–23 °C jusqu'à la mi-mois. Début mai, elle est à 18–19 °C : baignable pour les courageux. À partir de fin mai, c'est confortable.",
          "Im Oktober ja  -  das Meer hält bis Monatsmitte rund 22–23 °C. Anfang Mai sind es 18–19 °C: für Hartgesottene. Ab Ende Mai ist es angenehm.",
        ),
      },
    ],
  },
  {
    slug: "naxos-villages",
    cluster: "explore",
    title: ls(
      "Naxos mountain villages: Chalki, Filoti, Apeiranthos and the Tragea",
      "Τα ορεινά χωριά της Νάξου: Χαλκί, Φιλώτι, Απείρανθος και η Τραγαία",
      "I villaggi di montagna di Naxos: Chalki, Filoti, Apeiranthos e la Tragea",
      "Les villages de montagne de Naxos : Chalki, Filoti, Apeiranthos et la Tragea",
      "Die Bergdörfer von Naxos: Chalki, Filoti, Apeiranthos und das Tragea",
    ),
    excerpt: ls(
      "The interior is where Naxos stops resembling a beach island. A village-by-village guide with the drive times, what to see in each and where the road gets narrow.",
      "Η ενδοχώρα είναι εκεί που η Νάξος παύει να μοιάζει με νησί παραλιών. Οδηγός χωριό προς χωριό με χρόνους διαδρομής και τι να δείτε.",
      "L'entroterra è dove Naxos smette di sembrare un'isola di spiagge. Guida villaggio per villaggio con tempi di percorrenza e cosa vedere.",
      "L'intérieur est là où Naxos cesse d'être une île de plages. Un guide village par village avec les temps de trajet et ce qu'il faut voir.",
      "Im Landesinneren hört Naxos auf, eine Stranddestination zu sein. Ein Dorf-für-Dorf-Guide mit Fahrzeiten und Sehenswertem.",
    ),
    answer: ls(
      "The essential loop is Chalki (22 min from Chora), Moni and the Panagia Drosiani church, Filoti (28 min) and Apeiranthos (45 min), covering the Tragea valley's Byzantine churches and marble-paved streets. Allow a full day, drive it in the morning, and expect narrow roads with switchbacks above Filoti. Apollonas in the far north is a separate half-day.",
      "Η βασική διαδρομή είναι Χαλκί (22 λεπτά από τη Χώρα), Μονή και Παναγία Δροσιανή, Φιλώτι (28 λεπτά) και Απείρανθος (45 λεπτά), καλύπτοντας τις βυζαντινές εκκλησίες της Τραγαίας. Υπολογίστε μία ολόκληρη ημέρα και ξεκινήστε πρωί. Ο Απόλλωνας είναι ξεχωριστή μισή ημέρα.",
      "Il giro essenziale è Chalki (22 min da Chora), Moni e Panagia Drosiani, Filoti (28 min) e Apeiranthos (45 min), coprendo le chiese bizantine della Tragea. Prevedi una giornata intera e parti la mattina. Apollonas è mezza giornata a parte.",
      "La boucle essentielle : Chalki (22 min de Chora), Moni et Panagia Drosiani, Filoti (28 min) et Apeiranthos (45 min), couvrant les églises byzantines de la Tragea. Comptez une journée entière et partez le matin. Apollonas est une demi-journée à part.",
      "Die Kernrunde ist Chalki (22 Min. ab Chora), Moni mit Panagia Drosiani, Filoti (28 Min.) und Apeiranthos (45 Min.) mit den byzantinischen Kirchen des Tragea. Planen Sie einen ganzen Tag und starten Sie morgens. Apollonas ist ein eigener halber Tag.",
    ),
    hero: "/images/naxos/apiranthos.jpg",
    publishedAt: "2026-08-22",
    updatedAt: "2026-08-22",
    readingTime: 11,
    keywords: [
      "naxos villages",
      "apeiranthos naxos",
      "filoti naxos",
      "chalki naxos",
      "halki naxos",
      "naxos mountain villages",
      "tragea naxos",
    ],
    related: ["things-to-do-in-naxos", "naxos-itinerary", "mount-zas-and-hiking", "naxos-food-and-tavernas"],
    vehiclePicks: ["hyundai-i10", "peugeot-208", "suzuki-jimny"],
    locationPicks: ["chalki", "filoti", "apeiranthos", "apollonas"],
    sections: [
      {
        heading: ls(
          "Chalki  -  the capital of the Tragea",
          "Χαλκί  -  η πρωτεύουσα της Τραγαίας",
          "Chalki  -  la capitale della Tragea",
          "Chalki  -  la capitale de la Tragea",
          "Chalki  -  die Hauptstadt des Tragea",
        ),
        body: ls(
          "Chalki (often written Halki) was the commercial centre of the island's interior when olive oil and citron were the economy, and its neoclassical merchant houses and Venetian towers still show it. It is small, flat, entirely walkable and the easiest of the villages to enjoy with no plan at all: a square with two cafés under plane trees, a handful of craft shops in restored buildings, and the Vallindras distillery, which has been making kitron  -  a citrus-leaf liqueur unique to Naxos  -  in the same copper stills since 1896 and gives free tastings. The Byzantine church of Panagia Protothronos sits on the square with frescoes in five layers spanning six centuries. Twenty-two minutes from Chora on a good road.",
          "Το Χαλκί ήταν το εμπορικό κέντρο της ενδοχώρας όταν το λάδι και το κίτρο ήταν η οικονομία, και τα νεοκλασικά αρχοντικά του το δείχνουν ακόμη. Είναι μικρό, επίπεδο και εύκολο στο περπάτημα: μια πλατεία με δύο καφενεία κάτω από πλατάνια, εργαστήρια σε αναπαλαιωμένα κτίρια και το αποστακτήριο Βαλληνδρά, που φτιάχνει κίτρο από το 1896. Η Παναγία Πρωτόθρονος έχει τοιχογραφίες σε πέντε στρώσεις.",
          "Chalki era il centro commerciale dell'entroterra quando l'olio e il cedro erano l'economia, e le case neoclassiche lo mostrano ancora. È piccola, pianeggiante e facile da girare a piedi: una piazza con due caffè sotto i platani, botteghe artigiane e la distilleria Vallindras, che produce kitron dal 1896. Panagia Protothronos ha affreschi su cinque strati.",
          "Chalki était le centre commercial de l'intérieur quand l'huile et le cédrat faisaient l'économie, et ses maisons néoclassiques le montrent encore. Petit, plat et facile à parcourir : une place avec deux cafés sous les platanes, des ateliers d'artisans et la distillerie Vallindras, qui produit du kitron depuis 1896. Panagia Protothronos a des fresques sur cinq couches.",
          "Chalki war das Handelszentrum des Inselinneren, als Olivenöl und Zitronat die Wirtschaft trugen  -  die klassizistischen Kaufmannshäuser zeigen es noch. Klein, flach und leicht zu Fuß zu erkunden: ein Platz mit zwei Cafés unter Platanen, Kunsthandwerk in restaurierten Häusern und die Vallindras-Destillerie, die seit 1896 Kitron brennt. Panagia Protothronos hat Fresken in fünf Schichten.",
        ),
      },
      {
        heading: ls(
          "Panagia Drosiani  -  the oldest church you can walk into",
          "Παναγία Δροσιανή  -  η αρχαιότερη εκκλησία που μπορείτε να επισκεφθείτε",
          "Panagia Drosiani  -  la chiesa più antica in cui puoi entrare",
          "Panagia Drosiani  -  la plus ancienne église où l'on peut entrer",
          "Panagia Drosiani  -  die älteste begehbare Kirche",
        ),
        body: ls(
          "Two kilometres beyond Chalki on the road to Moni stands a low, irregular stone church with three apses that looks more like a farm building than a monument. Parts of Panagia Drosiani date to the 6th century, which makes it one of the oldest churches in the Balkans still in continuous use, and the frescoes inside are layered across a millennium  -  including a rare and unsettling depiction of Christ as a young man rather than the standard bearded Pantocrator. There is usually a caretaker with a key; a small donation is appropriate. Ten minutes and easily the most historically remarkable stop on the loop.",
          "Δύο χιλιόμετρα μετά το Χαλκί, στον δρόμο για τη Μονή, στέκει μια χαμηλή πέτρινη εκκλησία με τρεις αψίδες. Τμήματα της Παναγίας Δροσιανής χρονολογούνται στον 6ο αιώνα, καθιστώντας τη μία από τις αρχαιότερες εν λειτουργία εκκλησίες των Βαλκανίων. Οι τοιχογραφίες καλύπτουν μια χιλιετία, με σπάνια απεικόνιση του Χριστού ως νέου. Συνήθως υπάρχει φύλακας με κλειδί.",
          "Due chilometri oltre Chalki, sulla strada per Moni, sorge una bassa chiesa in pietra a tre absidi. Parti di Panagia Drosiani risalgono al VI secolo, tra le più antiche dei Balcani ancora in uso. Gli affreschi coprono un millennio, con una rara raffigurazione di Cristo giovane. Di solito c'è un custode con la chiave.",
          "À deux kilomètres après Chalki, sur la route de Moni, se dresse une église basse en pierre à trois absides. Des parties de Panagia Drosiani datent du VIe siècle, parmi les plus anciennes des Balkans encore en usage. Les fresques couvrent un millénaire, avec une rare représentation du Christ jeune. Un gardien détient généralement la clé.",
          "Zwei Kilometer hinter Chalki an der Straße nach Moni steht eine niedrige Steinkirche mit drei Apsiden. Teile von Panagia Drosiani stammen aus dem 6. Jahrhundert  -  eine der ältesten durchgehend genutzten Kirchen des Balkans. Die Fresken umspannen ein Jahrtausend, darunter eine seltene Darstellung Christi als junger Mann. Meist ist ein Küster mit Schlüssel vor Ort.",
        ),
      },
      {
        heading: ls(
          "Filoti  -  the biggest village and the base for Mount Zas",
          "Φιλώτι  -  το μεγαλύτερο χωριό και η βάση για τον Ζα",
          "Filoti  -  il villaggio più grande e base per il Monte Zas",
          "Filoti  -  le plus grand village et la base du mont Zas",
          "Filoti  -  das größte Dorf und Basis für den Mount Zas",
        ),
        body: ls(
          "Filoti spreads across the lower slopes of Mount Zas and is the largest village on Naxos after Chora, with around 1,500 residents  -  which means it functions as a real place: a bakery, a butcher, a pharmacy, several tavernas that are not aimed at visitors. The plateia under the plane trees on a weekday evening, with old men playing tavli and nobody in a hurry, is the most straightforwardly Greek scene on the island and costs the price of a coffee. The Agia Marina trailhead for Mount Zas is a ten-minute drive above the village. The 15 August festival here is one of the biggest in the Cyclades.",
          "Το Φιλώτι απλώνεται στις πλαγιές του Ζα και είναι το μεγαλύτερο χωριό μετά τη Χώρα, με περίπου 1.500 κατοίκους: φούρνος, κρεοπωλείο, φαρμακείο, ταβέρνες που δεν απευθύνονται σε τουρίστες. Η πλατεία κάτω από τα πλατάνια ένα καθημερινό βράδυ είναι η πιο αυθεντικά ελληνική σκηνή του νησιού. Το μονοπάτι για τον Ζα ξεκινά δέκα λεπτά πιο πάνω. Το πανηγύρι της 15ης Αυγούστου είναι από τα μεγαλύτερα των Κυκλάδων.",
          "Filoti si distende sulle pendici del Monte Zas ed è il villaggio più grande dopo Chora, con circa 1.500 abitanti: panetteria, macelleria, farmacia, taverne non turistiche. La piazza sotto i platani in una sera feriale è la scena più autenticamente greca dell'isola. Il sentiero per lo Zas parte dieci minuti più su. La festa del 15 agosto è tra le maggiori delle Cicladi.",
          "Filoti s'étale sur les pentes du mont Zas et c'est le plus grand village après Chora, avec environ 1 500 habitants : boulangerie, boucherie, pharmacie, tavernes non touristiques. La place sous les platanes un soir de semaine est la scène la plus authentiquement grecque de l'île. Le sentier du Zas part dix minutes plus haut. La fête du 15 août est l'une des plus grandes des Cyclades.",
          "Filoti erstreckt sich über die Hänge des Mount Zas und ist nach Chora das größte Dorf mit rund 1.500 Einwohnern: Bäckerei, Metzgerei, Apotheke, Tavernen ohne Touristenausrichtung. Der Dorfplatz unter den Platanen an einem Wochentagabend ist die griechischste Szene der Insel. Der Zas-Wanderweg beginnt zehn Minuten oberhalb. Das Fest am 15. August gehört zu den größten der Kykladen.",
        ),
      },
      {
        heading: ls(
          "Apeiranthos  -  marble streets and four museums",
          "Απείρανθος  -  μαρμάρινα σοκάκια και τέσσερα μουσεία",
          "Apeiranthos  -  vie di marmo e quattro musei",
          "Apeiranthos  -  rues de marbre et quatre musées",
          "Apeiranthos  -  Marmorgassen und vier Museen",
        ),
        body: ls(
          "The climb from Filoti to Apeiranthos is 25 minutes of switchbacks with the Tragea spread out below, and most people stop at least twice for the view. The village itself sits at 600 m, is paved throughout in local marble, and was settled by Cretan refugees in the 17th century who brought a dialect still audible today. Four small museums line the single main street  -  archaeological, geological, folk art and natural history  -  which for a village of 700 people says something about how seriously it takes itself. Park at the entrance and walk; the lanes are not driveable. Lunch here, order the goat, and allow longer than you planned.",
          "Η ανάβαση από το Φιλώτι στην Απείρανθο είναι 25 λεπτά στροφών με θέα στην Τραγαία. Το χωριό βρίσκεται στα 600 μ., είναι μαρμαροστρωμένο και κατοικήθηκε από Κρητικούς τον 17ο αιώνα, με διάλεκτο που ακούγεται ακόμη. Τέσσερα μικρά μουσεία σε έναν κεντρικό δρόμο. Παρκάρετε στην είσοδο και περπατήστε. Φάτε εδώ και ζητήστε κατσίκι.",
          "La salita da Filoti ad Apeiranthos è di 25 minuti di tornanti con vista sulla Tragea. Il villaggio è a 600 m, lastricato in marmo, fondato da cretesi nel XVII secolo con un dialetto ancora udibile. Quattro piccoli musei su un'unica via. Parcheggia all'ingresso e cammina. Pranza qui e chiedi il capretto.",
          "La montée de Filoti à Apeiranthos, c'est 25 minutes de lacets avec vue sur la Tragea. Le village est à 600 m, pavé de marbre, fondé par des Crétois au XVIIe siècle avec un dialecte encore perceptible. Quatre petits musées sur une seule rue. Garez-vous à l'entrée et marchez. Déjeunez ici et demandez le chevreau.",
          "Der Aufstieg von Filoti nach Apeiranthos dauert 25 Minuten in Serpentinen mit Blick über das Tragea. Das Dorf liegt auf 600 m, ist durchgehend mit Marmor gepflastert und wurde im 17. Jahrhundert von Kretern besiedelt, deren Dialekt noch hörbar ist. Vier kleine Museen an einer Straße. Am Ortseingang parken und laufen. Hier zu Mittag essen und Ziege bestellen.",
        ),
      },
      {
        heading: ls(
          "Koronos, Apollonas and the road north",
          "Κόρωνος, Απόλλωνας και ο δρόμος του βορρά",
          "Koronos, Apollonas e la strada verso nord",
          "Koronos, Apollonas et la route du nord",
          "Koronos, Apollonas und die Straße nach Norden",
        ),
        body: ls(
          "North of Apeiranthos the road drops into Koronos, a village built vertically down a ravine that made its money from emery mining  -  the abandoned aerial cableway towers still stand on the hillsides. It is the most atmospheric village on Naxos and the least visited. Beyond it the road runs 20 km down to Apollonas on the north coast, a small fishing village with a pebble beach, a row of fish tavernas and the 10.7 m Kouros lying in the quarry above. The full round trip from Chora is a two-hour drive plus stops, so treat it as a half or full day. The road is paved throughout but narrow and single-lane in places  -  fine in a small car, unpleasant in the dark.",
          "Βόρεια της Απειράνθου ο δρόμος κατεβαίνει στον Κόρωνο, χωριό χτισμένο κάθετα σε φαράγγι, με πλούτο από τη σμύριδα  -  οι πύργοι του εναέριου σε βλέπουν ακόμη από τις πλαγιές. Πιο πέρα, 20 χλμ. κάτω, ο Απόλλωνας: ψαροχώρι με βοτσαλωτή παραλία, ψαροταβέρνες και τον Κούρο 10,7 μ. Ο γύρος από τη Χώρα είναι δίωρη οδήγηση συν στάσεις.",
          "A nord di Apeiranthos la strada scende a Koronos, villaggio costruito in verticale in una gola, arricchito dallo smeriglio  -  le torri della teleferica sono ancora sui pendii. Oltre, 20 km più giù, Apollonas: villaggio di pescatori con spiaggia di ciottoli, taverne di pesce e il Kouros di 10,7 m. Il giro da Chora è di due ore di guida più soste.",
          "Au nord d'Apeiranthos, la route descend vers Koronos, village bâti à la verticale dans un ravin, enrichi par l'émeri  -  les tours du câble aérien sont encore sur les pentes. Plus loin, 20 km plus bas, Apollonas : village de pêcheurs avec plage de galets, tavernes de poisson et le Kouros de 10,7 m. La boucle depuis Chora fait deux heures de route plus les arrêts.",
          "Nördlich von Apeiranthos fällt die Straße nach Koronos ab, einem senkrecht in eine Schlucht gebauten Dorf, reich geworden durch Schmirgel  -  die Türme der Seilbahn stehen noch an den Hängen. Weiter, 20 km tiefer, liegt Apollonas: ein Fischerdorf mit Kiesstrand, Fischtavernen und dem 10,7 m langen Kouros. Die Runde ab Chora sind zwei Stunden Fahrt plus Stopps.",
        ),
      },
    ],
    faq: [
      {
        q: ls(
          "Which is the most beautiful village in Naxos?",
          "Ποιο είναι το ομορφότερο χωριό της Νάξου;",
          "Qual è il villaggio più bello di Naxos?",
          "Quel est le plus beau village de Naxos ?",
          "Welches ist das schönste Dorf auf Naxos?",
        ),
        a: ls(
          "Apeiranthos, for the marble streets, the altitude and the Cretan character. Koronos is the more atmospheric and far less visited alternative, built vertically down a ravine. Chalki is the easiest and most pleasant to spend an unplanned hour in.",
          "Η Απείρανθος, για τα μαρμάρινα σοκάκια, το υψόμετρο και τον κρητικό χαρακτήρα. Ο Κόρωνος είναι πιο ατμοσφαιρικός και πολύ λιγότερο επισκέψιμος. Το Χαλκί είναι το πιο εύκολο και ευχάριστο για μια ώρα χωρίς πρόγραμμα.",
          "Apeiranthos, per le vie di marmo, l'altitudine e il carattere cretese. Koronos è più suggestivo e molto meno visitato. Chalki è il più facile e piacevole per un'ora senza programmi.",
          "Apeiranthos, pour ses rues de marbre, son altitude et son caractère crétois. Koronos est plus atmosphérique et bien moins visité. Chalki est le plus facile et agréable pour une heure sans programme.",
          "Apeiranthos, wegen der Marmorgassen, der Höhe und des kretischen Charakters. Koronos ist stimmungsvoller und weit weniger besucht. Chalki ist am einfachsten und angenehmsten für eine ungeplante Stunde.",
        ),
      },
      {
        q: ls(
          "How long does it take to drive to Apeiranthos from Naxos Town?",
          "Πόσο διαρκεί η διαδρομή από τη Χώρα στην Απείρανθο;",
          "Quanto ci vuole da Chora ad Apeiranthos?",
          "Combien de temps de Chora à Apeiranthos ?",
          "Wie lange dauert die Fahrt von Chora nach Apeiranthos?",
        ),
        a: ls(
          "About 45 minutes for 27 km. The first two-thirds to Filoti are straightforward; the last stretch is continuous switchbacks averaging 25–30 km/h. Allow an hour if you stop for photographs, which you will.",
          "Περίπου 45 λεπτά για 27 χλμ. Τα δύο τρίτα έως το Φιλώτι είναι εύκολα· το τελευταίο κομμάτι είναι συνεχείς στροφές με μέση ταχύτητα 25–30 χλμ/ώρα. Υπολογίστε μία ώρα με στάσεις.",
          "Circa 45 minuti per 27 km. I primi due terzi fino a Filoti sono facili; l'ultimo tratto è tutto tornanti a 25–30 km/h. Conta un'ora con le soste per le foto.",
          "Environ 45 minutes pour 27 km. Les deux premiers tiers jusqu'à Filoti sont faciles ; la dernière portion est en lacets à 25–30 km/h. Comptez une heure avec les arrêts photo.",
          "Etwa 45 Minuten für 27 km. Die ersten zwei Drittel bis Filoti sind unkompliziert; der letzte Abschnitt besteht aus Serpentinen mit 25–30 km/h. Mit Fotostopps eine Stunde.",
        ),
      },
      {
        q: ls(
          "Can you reach the Naxos villages by bus?",
          "Μπορείτε να φτάσετε στα χωριά της Νάξου με λεωφορείο;",
          "Si raggiungono i villaggi di Naxos in autobus?",
          "Peut-on rejoindre les villages de Naxos en bus ?",
          "Erreicht man die Dörfer von Naxos mit dem Bus?",
        ),
        a: ls(
          "Chalki, Filoti, Apeiranthos and Apollonas have three to four buses a day in summer, with the last return from inland typically at 16:00–17:00. That works if you commit to one village. It does not work for the loop, and it does not reach Moni, Panagia Drosiani, Flerio or the Temple of Demeter.",
          "Το Χαλκί, το Φιλώτι, η Απείρανθος και ο Απόλλωνας έχουν τρία-τέσσερα δρομολόγια ημερησίως το καλοκαίρι, με τελευταία επιστροφή συνήθως 16:00–17:00. Λειτουργεί για ένα χωριό, όχι για τη διαδρομή, και δεν φτάνει στη Μονή, την Παναγία Δροσιανή ή το Φλεριό.",
          "Chalki, Filoti, Apeiranthos e Apollonas hanno tre-quattro corse al giorno d'estate, ultimo rientro tipicamente 16:00–17:00. Funziona per un solo villaggio, non per il giro, e non raggiunge Moni, Panagia Drosiani o Flerio.",
          "Chalki, Filoti, Apeiranthos et Apollonas ont trois à quatre bus par jour l'été, dernier retour vers 16h–17h. Cela marche pour un seul village, pas pour la boucle, et ne dessert ni Moni, ni Panagia Drosiani, ni Flerio.",
          "Chalki, Filoti, Apeiranthos und Apollonas haben im Sommer drei bis vier Busse täglich, letzte Rückfahrt meist 16:00–17:00 Uhr. Für ein Dorf reicht das, für die Runde nicht  -  und Moni, Panagia Drosiani und Flerio werden nicht bedient.",
        ),
      },
      {
        q: ls(
          "Is the drive to the Naxos mountain villages difficult?",
          "Είναι δύσκολη η διαδρομή προς τα ορεινά χωριά;",
          "È difficile guidare verso i villaggi di montagna?",
          "La route vers les villages de montagne est-elle difficile ?",
          "Ist die Fahrt zu den Bergdörfern schwierig?",
        ),
        a: ls(
          "Not difficult, but slow and narrow. Everything is paved. The Filoti–Apeiranthos–Koronos stretch has continuous bends, occasional single-lane sections and no barriers in places. A small car is ideal. Drive it in daylight  -  there is no street lighting at all above Filoti.",
          "Όχι δύσκολη, αλλά αργή και στενή. Όλα είναι ασφαλτοστρωμένα. Το τμήμα Φιλώτι–Απείρανθος–Κόρωνος έχει συνεχείς στροφές και σημεία μονής λωρίδας. Ένα μικρό αυτοκίνητο είναι ιδανικό. Οδηγήστε με φως ημέρας  -  δεν υπάρχει καθόλου φωτισμός πάνω από το Φιλώτι.",
          "Non difficile, ma lenta e stretta. Tutto asfaltato. Il tratto Filoti–Apeiranthos–Koronos ha curve continue e punti a corsia unica. Un'auto piccola è ideale. Guida di giorno  -  sopra Filoti non c'è illuminazione.",
          "Pas difficile, mais lente et étroite. Tout est goudronné. La portion Filoti–Apeiranthos–Koronos enchaîne les virages avec des passages à voie unique. Une petite voiture est idéale. Roulez de jour  -  aucun éclairage au-dessus de Filoti.",
          "Nicht schwierig, aber langsam und eng. Alles asphaltiert. Der Abschnitt Filoti–Apeiranthos–Koronos hat durchgehend Kurven und stellenweise nur eine Spur. Ein Kleinwagen ist ideal. Fahren Sie bei Tageslicht  -  oberhalb von Filoti gibt es keine Beleuchtung.",
        ),
      },
      {
        q: ls(
          "What is the Tragea valley?",
          "Τι είναι η Τραγαία;",
          "Cos'è la valle di Tragea?",
          "Qu'est-ce que la vallée de Tragea ?",
          "Was ist das Tragea-Tal?",
        ),
        a: ls(
          "A broad inland plateau of ancient olive groves between Chalki and Filoti, sometimes called the largest olive forest in the Cyclades. It holds more than thirty Byzantine churches within a few kilometres, several with frescoes from the 9th to 13th centuries, and it is the reason the interior of Naxos is worth a full day.",
          "Ένα πλατύ οροπέδιο με αιωνόβιους ελαιώνες ανάμεσα στο Χαλκί και το Φιλώτι, γνωστό και ως το μεγαλύτερο ελαιοδάσος των Κυκλάδων. Περιλαμβάνει πάνω από τριάντα βυζαντινές εκκλησίες, αρκετές με τοιχογραφίες 9ου–13ου αιώνα.",
          "Un ampio altopiano di uliveti secolari tra Chalki e Filoti, detto anche il più grande bosco di ulivi delle Cicladi. Contiene oltre trenta chiese bizantine, molte con affreschi dal IX al XIII secolo.",
          "Un large plateau d'oliveraies anciennes entre Chalki et Filoti, parfois appelé la plus grande forêt d'oliviers des Cyclades. Il abrite plus de trente églises byzantines, plusieurs avec des fresques du IXe au XIIIe siècle.",
          "Eine weite Hochebene mit uralten Olivenhainen zwischen Chalki und Filoti, mitunter der größte Olivenwald der Kykladen genannt. Sie birgt über dreißig byzantinische Kirchen, mehrere mit Fresken vom 9. bis 13. Jahrhundert.",
        ),
      },
    ],
  },
  {
    slug: "mount-zas-and-hiking",
    cluster: "explore",
    title: ls(
      "Mount Zas and hiking in Naxos: the Zeus cave, the summit and the trails",
      "Ο Ζας και η πεζοπορία στη Νάξο: η σπηλιά του Δία, η κορυφή και τα μονοπάτια",
      "Monte Zas ed escursioni a Naxos: la grotta di Zeus, la vetta e i sentieri",
      "Le mont Zas et la randonnée à Naxos : la grotte de Zeus, le sommet et les sentiers",
      "Mount Zas und Wandern auf Naxos: die Zeus-Höhle, der Gipfel und die Wege",
    ),
    excerpt: ls(
      "The highest peak in the Cyclades, the cave where Zeus was supposedly raised, and four other walks worth doing  -  with trailheads, timings and where to park.",
      "Η ψηλότερη κορυφή των Κυκλάδων, η σπηλιά όπου κατά τον μύθο μεγάλωσε ο Δίας, και τέσσερις ακόμη διαδρομές  -  με αφετηρίες, χρόνους και σημεία στάθμευσης.",
      "La vetta più alta delle Cicladi, la grotta dove secondo il mito crebbe Zeus, e altre quattro camminate  -  con partenze, tempi e parcheggi.",
      "Le plus haut sommet des Cyclades, la grotte où Zeus aurait grandi, et quatre autres marches  -  avec départs, durées et stationnement.",
      "Der höchste Gipfel der Kykladen, die Höhle, in der Zeus aufgewachsen sein soll, und vier weitere Wanderungen  -  mit Startpunkten, Zeiten und Parkplätzen.",
    ),
    answer: ls(
      "Mount Zas is 1,004 m and the highest point in the Cyclades. The standard route starts at the Agia Marina chapel above Filoti, takes about three hours return, and is a steady rocky climb rather than a technical one. The Zeus cave sits on the alternative Aria Spring path. Start before 09:00, carry two litres of water per person, and wear proper shoes  -  not sandals.",
      "Ο Ζας είναι 1.004 μ. και η ψηλότερη κορυφή των Κυκλάδων. Η κλασική διαδρομή ξεκινά από το εκκλησάκι της Αγίας Μαρίνας πάνω από το Φιλώτι, διαρκεί περίπου τρεις ώρες συνολικά και είναι σταθερή πετρώδης ανάβαση χωρίς τεχνικές δυσκολίες. Ξεκινήστε πριν τις 09:00 με δύο λίτρα νερό και κατάλληλα παπούτσια.",
      "Il Monte Zas è alto 1.004 m, la cima più alta delle Cicladi. Il percorso classico parte dalla cappella di Agia Marina sopra Filoti, richiede circa tre ore andata e ritorno ed è una salita rocciosa costante, non tecnica. Parti prima delle 09:00 con due litri d'acqua e scarpe adatte.",
      "Le mont Zas culmine à 1 004 m, plus haut sommet des Cyclades. L'itinéraire classique part de la chapelle Agia Marina au-dessus de Filoti, dure environ trois heures aller-retour et constitue une montée rocheuse régulière, non technique. Partez avant 9h avec deux litres d'eau et de bonnes chaussures.",
      "Der Mount Zas ist mit 1.004 m der höchste Punkt der Kykladen. Die Standardroute beginnt an der Kapelle Agia Marina oberhalb von Filoti, dauert rund drei Stunden hin und zurück und ist ein stetiger felsiger Anstieg ohne technische Schwierigkeiten. Starten Sie vor 9:00 Uhr mit zwei Litern Wasser und festen Schuhen.",
    ),
    hero: "/images/naxos/gallery/naxos-mountain.jpg",
    publishedAt: "2026-08-22",
    updatedAt: "2026-08-22",
    readingTime: 9,
    keywords: [
      "mount zas naxos",
      "zeus cave naxos",
      "naxos hiking",
      "zas hike",
      "naxos trails",
      "mount zeus naxos",
    ],
    related: ["naxos-villages", "things-to-do-in-naxos", "naxos-itinerary", "best-time-to-visit-naxos"],
    vehiclePicks: ["suzuki-jimny", "dacia-duster", "hyundai-i10"],
    locationPicks: ["filoti", "apeiranthos"],
    sections: [
      {
        heading: ls(
          "The standard route from Agia Marina",
          "Η κλασική διαδρομή από την Αγία Μαρίνα",
          "Il percorso classico da Agia Marina",
          "L'itinéraire classique depuis Agia Marina",
          "Die Standardroute ab Agia Marina",
        ),
        body: ls(
          "Drive up from Filoti towards Danakos and follow signs to the Agia Marina chapel; there is a rough parking area beside it with room for perhaps a dozen cars. The trail leaves from behind the chapel and is marked with red paint splashes and cairns. It climbs steadily over open rock and low scrub for about 75 minutes to the summit trig point at 1,004 m, with no scrambling and no exposure  -  but also no shade whatsoever and a loose, stony surface that punishes flat-soled shoes. Come down the same way in about 55 minutes. On a clear morning the summit gives you Paros, Ios, Amorgos, Santorini and occasionally the mountains of Crete on the horizon.",
          "Ανεβείτε από το Φιλώτι προς Δανακό και ακολουθήστε τις πινακίδες για το εκκλησάκι της Αγίας Μαρίνας, όπου υπάρχει πρόχειρος χώρος στάθμευσης. Το μονοπάτι ξεκινά πίσω από το εκκλησάκι με κόκκινες σημάνσεις. Ανεβαίνει σταθερά για περίπου 75 λεπτά ως την κορυφή στα 1.004 μ., χωρίς αναρρίχηση αλλά και χωρίς καθόλου σκιά. Η κατάβαση διαρκεί περίπου 55 λεπτά.",
          "Sali da Filoti verso Danakos e segui le indicazioni per la cappella di Agia Marina, dove c'è un parcheggio sterrato. Il sentiero parte dietro la cappella, segnato in rosso. Sale costantemente per circa 75 minuti fino alla vetta a 1.004 m, senza arrampicata ma senza alcuna ombra. La discesa richiede circa 55 minuti.",
          "Montez de Filoti vers Danakos et suivez les panneaux vers la chapelle Agia Marina, où se trouve un parking sommaire. Le sentier part derrière la chapelle, balisé en rouge. Il grimpe régulièrement pendant environ 75 minutes jusqu'au sommet à 1 004 m, sans escalade mais sans aucune ombre. La descente prend environ 55 minutes.",
          "Fahren Sie von Filoti Richtung Danakos und folgen Sie den Schildern zur Kapelle Agia Marina, wo ein einfacher Parkplatz liegt. Der Weg beginnt hinter der Kapelle, rot markiert. Er steigt rund 75 Minuten stetig bis zum Gipfel auf 1.004 m  -  ohne Kletterei, aber auch ohne jeden Schatten. Der Abstieg dauert etwa 55 Minuten.",
        ),
      },
      {
        heading: ls(
          "The Zeus cave and the Aria spring",
          "Η σπηλιά του Δία και η πηγή Αριά",
          "La grotta di Zeus e la sorgente Aria",
          "La grotte de Zeus et la source Aria",
          "Die Zeus-Höhle und die Aria-Quelle",
        ),
        body: ls(
          "The cave that mythology names as the place Zeus was raised sits on the alternative approach, reached from the Aria spring trailhead lower down. It is a genuine cave  -  around 115 m deep, with a wide entrance chamber you can walk into without equipment  -  and archaeologists have found Neolithic and Mycenaean material inside, so people really did use it for millennia. Bring a torch; the light dies quickly past the entrance. Combining the cave with the summit makes a circuit of roughly four hours. If you only want the cave, it is a 40-minute walk from the spring and much the easier option with children.",
          "Η σπηλιά που η μυθολογία ταυτίζει με τον τόπο ανατροφής του Δία βρίσκεται στην εναλλακτική διαδρομή, από την πηγή Αριά. Είναι πραγματική σπηλιά, περίπου 115 μ. βάθους, με ευρύχωρο θάλαμο εισόδου. Αρχαιολογικά ευρήματα δείχνουν νεολιθική και μυκηναϊκή χρήση. Πάρτε φακό. Ο συνδυασμός σπηλιάς και κορυφής κάνει περίπου τέσσερις ώρες.",
          "La grotta che il mito indica come luogo in cui crebbe Zeus si trova sul percorso alternativo, dalla sorgente Aria. È una grotta vera, profonda circa 115 m, con un'ampia camera d'ingresso. Reperti neolitici e micenei ne attestano l'uso millenario. Porta una torcia. Grotta più vetta fanno circa quattro ore.",
          "La grotte que le mythe désigne comme le lieu où Zeus fut élevé se trouve sur l'itinéraire alternatif, depuis la source Aria. C'est une vraie grotte, profonde d'environ 115 m, avec une large chambre d'entrée. Des vestiges néolithiques et mycéniens attestent un usage millénaire. Prenez une lampe. Grotte plus sommet : environ quatre heures.",
          "Die Höhle, die der Mythos als Aufwachsort des Zeus nennt, liegt an der Alternativroute ab der Aria-Quelle. Sie ist eine echte Höhle, rund 115 m tief, mit weiter Eingangskammer. Neolithische und mykenische Funde belegen jahrtausendelange Nutzung. Nehmen Sie eine Lampe mit. Höhle plus Gipfel ergeben etwa vier Stunden.",
        ),
      },
      {
        heading: ls(
          "Four other walks worth the drive",
          "Τέσσερις ακόμη διαδρομές που αξίζουν",
          "Altre quattro camminate che valgono il viaggio",
          "Quatre autres marches qui valent le déplacement",
          "Vier weitere lohnende Wanderungen",
        ),
        body: ls(
          "The Flerio kouroi walk near Melanes is fifteen easy minutes through olive groves to two colossal unfinished statues, with a stream and a tiny taverna  -  the best short walk on the island and fine for all ages. The Alyko cedar forest loop takes about an hour through juniper dunes to the painted abandoned hotel and back. The old marble path from Apeiranthos down to Moutsouna is a serious 3.5-hour descent following the route the emery was carried on, and needs a lift back. And the Routsouna waterfall walk near Keramoti is a short, shaded stroll that actually has running water into early summer  -  unexpected on a Cycladic island.",
          "Η διαδρομή προς τους Κούρους του Φλεριού κοντά στις Μέλανες είναι δεκαπέντε εύκολα λεπτά μέσα από ελαιώνες  -  η καλύτερη σύντομη βόλτα του νησιού. Ο κύκλος στο κεδρόδασος του Αλυκού διαρκεί περίπου μία ώρα. Το παλιό μαρμάρινο μονοπάτι από την Απείρανθο στη Μουτσούνα είναι σοβαρή κατάβαση 3,5 ωρών. Και ο καταρράκτης της Ρουτσούνας κοντά στην Κεραμωτή έχει τρεχούμενο νερό ως τις αρχές του καλοκαιριού.",
          "Il sentiero dei kouroi di Flerio vicino a Melanes è di quindici minuti facili tra gli uliveti  -  la migliore passeggiata breve dell'isola. L'anello nella foresta di cedri di Alyko dura circa un'ora. L'antico sentiero in marmo da Apeiranthos a Moutsouna è una discesa impegnativa di 3,5 ore. E la cascata di Routsouna vicino a Keramoti ha acqua corrente fino a inizio estate.",
          "Le sentier des kouroï de Flerio près de Melanes fait quinze minutes faciles à travers les oliveraies  -  la meilleure courte marche de l'île. La boucle de la forêt de cèdres d'Alyko dure environ une heure. L'ancien chemin de marbre d'Apeiranthos à Moutsouna est une descente sérieuse de 3h30. Et la cascade de Routsouna près de Keramoti coule jusqu'au début de l'été.",
          "Der Weg zu den Kouroi von Flerio bei Melanes dauert fünfzehn leichte Minuten durch Olivenhaine  -  die beste kurze Wanderung der Insel. Die Runde im Zedernwald von Alyko dauert etwa eine Stunde. Der alte Marmorweg von Apeiranthos nach Moutsouna ist ein anspruchsvoller 3,5-Stunden-Abstieg. Und der Routsouna-Wasserfall bei Keramoti führt bis zum Frühsommer Wasser.",
        ),
      },
      {
        heading: ls(
          "When to hike, and when not to",
          "Πότε να πεζοπορήσετε και πότε όχι",
          "Quando fare escursioni e quando no",
          "Quand randonner, et quand s'abstenir",
          "Wann wandern  -  und wann nicht",
        ),
        body: ls(
          "April to early June and mid-September to early November are the hiking seasons on Naxos, when temperatures sit in the low twenties and the island is green. July and August are genuinely hazardous on Zas after about 10:00: the route is entirely unshaded, ground temperatures on the rock exceed air temperature substantially, and mountain rescue on Naxos is a volunteer operation. If you must climb in high summer, be at the trailhead at 07:00 and down by 11:00. Never start Zas in the afternoon in any month  -  the descent over loose stone in fading light is where the injuries happen.",
          "Απρίλιος έως αρχές Ιουνίου και μέσα Σεπτεμβρίου έως αρχές Νοεμβρίου είναι οι εποχές πεζοπορίας. Ο Ιούλιος και ο Αύγουστος είναι πραγματικά επικίνδυνοι στον Ζα μετά τις 10:00: η διαδρομή δεν έχει καθόλου σκιά. Αν πρέπει, ξεκινήστε στις 07:00 και κατεβείτε ως τις 11:00. Ποτέ μην ξεκινάτε απόγευμα  -  η κατάβαση σε χαλαρή πέτρα με λίγο φως προκαλεί τα ατυχήματα.",
          "Da aprile a inizio giugno e da metà settembre a inizio novembre sono le stagioni ideali. Luglio e agosto sono davvero rischiosi sullo Zas dopo le 10:00: il percorso è senza ombra. Se devi, parti alle 07:00 e scendi entro le 11:00. Mai iniziare nel pomeriggio  -  la discesa su pietrisco con poca luce è dove avvengono gli infortuni.",
          "D'avril à début juin et de mi-septembre à début novembre : les saisons de randonnée. Juillet et août sont réellement dangereux sur le Zas après 10h : l'itinéraire est sans ombre. Si vous devez y aller, partez à 7h et redescendez avant 11h. Ne commencez jamais l'après-midi  -  la descente sur pierraille en lumière déclinante est source d'accidents.",
          "April bis Anfang Juni und Mitte September bis Anfang November sind die Wandersaisons. Juli und August sind auf dem Zas nach 10:00 Uhr wirklich gefährlich: Der Weg hat keinerlei Schatten. Wenn es sein muss, um 7:00 Uhr starten und bis 11:00 Uhr unten sein. Nie am Nachmittag beginnen  -  der Abstieg über loses Geröll bei schwindendem Licht führt zu den Unfällen.",
        ),
      },
    ],
    faq: [
      {
        q: ls(
          "How hard is the Mount Zas hike?",
          "Πόσο δύσκολη είναι η ανάβαση στον Ζα;",
          "Quanto è difficile l'escursione sul Monte Zas?",
          "Le mont Zas est-il difficile à monter ?",
          "Wie schwierig ist die Wanderung auf den Mount Zas?",
        ),
        a: ls(
          "Moderate. There is no scrambling, no exposure and the path is marked, but it climbs about 450 m over loose rock with zero shade and takes roughly 75 minutes up. Anyone reasonably fit in proper shoes will manage it; it is not a walk for sandals or for the middle of an August afternoon.",
          "Μέτρια. Δεν υπάρχει αναρρίχηση ούτε έκθεση και το μονοπάτι είναι σημασμένο, αλλά ανεβαίνει περίπου 450 μ. σε χαλαρή πέτρα χωρίς σκιά, σε περίπου 75 λεπτά. Δεν είναι διαδρομή για σανδάλια ή για απόγευμα Αυγούστου.",
          "Moderata. Nessuna arrampicata, sentiero segnato, ma sale circa 450 m su pietrisco senza ombra in circa 75 minuti. Non è una camminata per sandali né per un pomeriggio d'agosto.",
          "Modérée. Pas d'escalade, sentier balisé, mais 450 m de dénivelé sur pierraille sans ombre en environ 75 minutes. Ce n'est pas une marche en sandales ni un après-midi d'août.",
          "Mittel. Keine Kletterei, markierter Weg, aber rund 450 Höhenmeter über loses Gestein ohne Schatten in etwa 75 Minuten. Nichts für Sandalen oder einen Augustnachmittag.",
        ),
      },
      {
        q: ls(
          "Can you drive to Mount Zas?",
          "Μπορείτε να φτάσετε με αυτοκίνητο στον Ζα;",
          "Si può arrivare in auto al Monte Zas?",
          "Peut-on aller en voiture au mont Zas ?",
          "Kann man zum Mount Zas fahren?",
        ),
        a: ls(
          "You can drive to the Agia Marina trailhead at around 550 m, which is where the walk starts  -  a paved road from Filoti with a rough parking area at the end. You cannot drive any higher; the summit is on foot only. Any small car handles the approach fine.",
          "Μπορείτε να φτάσετε με αυτοκίνητο στην αφετηρία της Αγίας Μαρίνας, γύρω στα 550 μ., όπου ξεκινά η πεζοπορία  -  ασφαλτοστρωμένος δρόμος από το Φιλώτι με πρόχειρο πάρκινγκ. Πιο ψηλά μόνο με τα πόδια.",
          "Puoi arrivare in auto alla partenza di Agia Marina, a circa 550 m  -  strada asfaltata da Filoti con parcheggio sterrato. Più in alto solo a piedi.",
          "Vous pouvez rejoindre en voiture le départ d'Agia Marina, vers 550 m  -  route goudronnée depuis Filoti avec un parking sommaire. Au-delà, uniquement à pied.",
          "Sie können bis zum Startpunkt Agia Marina auf etwa 550 m fahren  -  asphaltierte Straße ab Filoti mit einfachem Parkplatz. Höher geht es nur zu Fuß.",
        ),
      },
      {
        q: ls(
          "Is the Zeus cave in Naxos worth visiting?",
          "Αξίζει η σπηλιά του Δία στη Νάξο;",
          "Vale la pena visitare la grotta di Zeus a Naxos?",
          "La grotte de Zeus à Naxos vaut-elle la visite ?",
          "Lohnt die Zeus-Höhle auf Naxos?",
        ),
        a: ls(
          "Yes, if you take a torch and adjust your expectations: it is an unlit natural cave rather than a managed site, with a large entrance chamber and genuine Neolithic and Mycenaean archaeology. The forty-minute walk in from the Aria spring is pleasant and shaded in parts, and it works well with children where the summit does not.",
          "Ναι, αν πάρετε φακό και προσαρμόσετε τις προσδοκίες: είναι αφώτιστη φυσική σπηλιά, όχι οργανωμένος χώρος, με μεγάλο θάλαμο εισόδου και πραγματικά νεολιθικά και μυκηναϊκά ευρήματα. Η σαρανταλεπτη διαδρομή από την Αριά είναι ευχάριστη και κατάλληλη για παιδιά.",
          "Sì, se porti una torcia e adegui le aspettative: è una grotta naturale non illuminata, con un'ampia camera d'ingresso e reperti neolitici e micenei autentici. La camminata di quaranta minuti dalla sorgente Aria è piacevole e adatta ai bambini.",
          "Oui, avec une lampe et des attentes ajustées : c'est une grotte naturelle non éclairée, avec une vaste chambre d'entrée et de véritables vestiges néolithiques et mycéniens. La marche de quarante minutes depuis la source Aria est agréable et convient aux enfants.",
          "Ja, mit Lampe und angepassten Erwartungen: eine unbeleuchtete Naturhöhle mit großer Eingangskammer und echten neolithischen und mykenischen Funden. Der vierzigminütige Weg ab der Aria-Quelle ist angenehm und auch mit Kindern machbar.",
        ),
      },
      {
        q: ls(
          "How high is Mount Zas?",
          "Πόσο ψηλός είναι ο Ζας;",
          "Quanto è alto il Monte Zas?",
          "Quelle est la hauteur du mont Zas ?",
          "Wie hoch ist der Mount Zas?",
        ),
        a: ls(
          "1,004 metres, which makes it the highest point in the entire Cyclades archipelago. The name is generally taken to derive from Zeus, and an inscription on a rock near the summit path reads 'Oros Dios Melosiou'  -  boundary of Zeus Melosios.",
          "1.004 μέτρα, το υψηλότερο σημείο ολόκληρου του κυκλαδικού αρχιπελάγους. Το όνομα αποδίδεται στον Δία, και επιγραφή σε βράχο κοντά στο μονοπάτι γράφει «Όρος Διός Μηλωσίου».",
          "1.004 metri, il punto più alto dell'intero arcipelago delle Cicladi. Il nome deriva da Zeus, e un'iscrizione su una roccia vicino al sentiero recita «Oros Dios Melosiou».",
          "1 004 mètres, le point culminant de tout l'archipel des Cyclades. Le nom dérive de Zeus, et une inscription sur un rocher près du sentier indique « Oros Dios Melosiou ».",
          "1.004 Meter  -  der höchste Punkt des gesamten Kykladen-Archipels. Der Name leitet sich von Zeus ab; eine Inschrift an einem Felsen nahe dem Weg lautet „Oros Dios Melosiou“.",
        ),
      },
    ],
  },
];
