import type { NaxosGuideArticle } from "@/types/content";
import { ls } from "./_shared";

/**
 * "Plan" cluster — the top-of-funnel articles that carry the parent topic
 * "naxos greece" (traffic potential ~7,200 at KD 0–2). Each one routes into the
 * fleet and location pages per seo-os Law 2.
 */
export const PLAN_ARTICLES: NaxosGuideArticle[] = [
  {
    slug: "naxos-travel-guide",
    cluster: "plan",
    title: ls(
      "Naxos travel guide 2026: everything you need before you go",
      "Οδηγός ταξιδιού για τη Νάξο 2026: όλα όσα πρέπει να ξέρετε",
      "Guida di viaggio a Naxos 2026: tutto quello che serve sapere",
      "Guide de voyage Naxos 2026 : tout ce qu'il faut savoir avant de partir",
      "Naxos Reiseführer 2026: alles, was Sie vorher wissen müssen",
    ),
    excerpt: ls(
      "The largest island in the Cyclades, written up by people who drive it every day  -  beaches, villages, food, costs, timing, and how to get around once you land.",
      "Το μεγαλύτερο νησί των Κυκλάδων, από ανθρώπους που το οδηγούν καθημερινά: παραλίες, χωριά, φαγητό, κόστος και μετακινήσεις.",
      "L'isola più grande delle Cicladi, raccontata da chi la percorre ogni giorno: spiagge, villaggi, cibo, costi e spostamenti.",
      "La plus grande île des Cyclades, racontée par ceux qui la parcourent chaque jour : plages, villages, cuisine, budget et déplacements.",
      "Die größte Insel der Kykladen, beschrieben von Menschen, die sie täglich befahren: Strände, Dörfer, Essen, Kosten und Fortbewegung.",
    ),
    answer: ls(
      "Naxos is the largest and most self-sufficient island in the Cyclades: 430 km² with over 40 beaches, a Venetian old town, marble mountain villages and the highest peak in the archipelago. Allow five to seven days, visit between late May and early October, and rent a car  -  the island is far too big for buses alone.",
      "Η Νάξος είναι το μεγαλύτερο και πιο αυτάρκες νησί των Κυκλάδων: 430 τ.χλμ. με πάνω από 40 παραλίες, βενετσιάνικο Κάστρο, μαρμάρινα ορεινά χωριά και την ψηλότερη κορυφή του αρχιπελάγους. Υπολογίστε πέντε έως επτά ημέρες, από τα τέλη Μαΐου έως τις αρχές Οκτωβρίου, και νοικιάστε αυτοκίνητο.",
      "Naxos è l'isola più grande e autosufficiente delle Cicladi: 430 km² con oltre 40 spiagge, un centro storico veneziano, villaggi di montagna in marmo e la vetta più alta dell'arcipelago. Prevedi cinque-sette giorni, da fine maggio a inizio ottobre, e noleggia un'auto.",
      "Naxos est la plus grande et la plus autonome des Cyclades : 430 km², plus de 40 plages, une vieille ville vénitienne, des villages de montagne en marbre et le plus haut sommet de l'archipel. Comptez cinq à sept jours, de fin mai à début octobre, et louez une voiture.",
      "Naxos ist die größte und eigenständigste Insel der Kykladen: 430 km² mit über 40 Stränden, einer venezianischen Altstadt, Bergdörfern aus Marmor und dem höchsten Gipfel des Archipels. Planen Sie fünf bis sieben Tage von Ende Mai bis Anfang Oktober und mieten Sie ein Auto.",
    ),
    hero: "/images/naxos/portara-detail.jpg",
    publishedAt: "2026-08-22",
    updatedAt: "2026-08-22",
    readingTime: 12,
    keywords: [
      "naxos travel guide",
      "naxos guide",
      "naxos greece",
      "visiting naxos",
      "naxos island guide",
    ],
    related: ["things-to-do-in-naxos", "naxos-itinerary", "best-time-to-visit-naxos", "how-to-get-to-naxos"],
    vehiclePicks: ["hyundai-i10", "peugeot-208", "dacia-duster"],
    locationPicks: ["naxos-town", "agios-prokopios", "airport-pickup"],
    sections: [
      {
        heading: ls(
          "What Naxos actually is",
          "Τι είναι πραγματικά η Νάξος",
          "Cos'è davvero Naxos",
          "Ce qu'est vraiment Naxos",
          "Was Naxos wirklich ist",
        ),
        body: ls(
          "Naxos is the Cyclades island that does not depend on tourism to exist. It has its own agriculture  -  potatoes that Greeks genuinely queue for, a protected graviera cheese, citron liqueur, olive groves and cattle grazing on green hillsides that look nothing like the bare rock of Mykonos or Santorini. That single fact shapes the whole visit: prices are lower because locals also shop here, tavernas cook for a year-round population, and the island stays inhabited in February. At 430 km² it is roughly five times the size of Santorini, which is why almost every mistake first-time visitors make comes down to underestimating distance. Chora to Apollonas is 48 km of mountain road and takes an hour each way. Chora to Pyrgaki is 22 km and takes 35 minutes. You cannot see Naxos from a beach lounger in Agios Prokopios, and that is exactly the point.",
          "Η Νάξος είναι το κυκλαδονήσι που δεν εξαρτάται από τον τουρισμό για να υπάρχει. Έχει δική της γεωργία: πατάτες, γραβιέρα ΠΟΠ, κίτρο, ελαιώνες και κτηνοτροφία σε καταπράσινες πλαγιές. Αυτό διαμορφώνει όλη την επίσκεψη  -  οι τιμές είναι χαμηλότερες, οι ταβέρνες μαγειρεύουν για μόνιμους κατοίκους και το νησί ζει και τον Φεβρουάριο. Με 430 τ.χλμ. είναι περίπου πέντε φορές μεγαλύτερο από τη Σαντορίνη, γι' αυτό και το συνηθέστερο λάθος είναι η υποτίμηση των αποστάσεων.",
          "Naxos è l'isola delle Cicladi che non dipende dal turismo per esistere. Ha un'agricoltura propria: patate, graviera DOP, liquore di cedro, uliveti e pascoli su colline verdi. Questo modella tutta la visita: prezzi più bassi, taverne che cucinano per residenti tutto l'anno, un'isola viva anche a febbraio. Con 430 km² è circa cinque volte Santorini, ed è per questo che l'errore più comune è sottovalutare le distanze.",
          "Naxos est l'île des Cyclades qui ne dépend pas du tourisme pour exister. Elle a sa propre agriculture : pommes de terre, graviéra AOP, liqueur de cédrat, oliveraies et élevage sur des collines verdoyantes. Cela façonne tout le séjour : des prix plus bas, des tavernes qui cuisinent pour des résidents à l'année, une île habitée même en février. Avec 430 km², elle fait environ cinq fois Santorin, d'où l'erreur la plus fréquente : sous-estimer les distances.",
          "Naxos ist die Kykladeninsel, die für ihre Existenz nicht vom Tourismus abhängt. Sie hat eigene Landwirtschaft: Kartoffeln, geschützten Graviera-Käse, Zitronatlikör, Olivenhaine und Viehweiden auf grünen Hängen. Das prägt den ganzen Aufenthalt: niedrigere Preise, Tavernen, die für Ganzjahresbewohner kochen, eine Insel, die auch im Februar lebt. Mit 430 km² ist sie etwa fünfmal so groß wie Santorin  -  weshalb der häufigste Fehler das Unterschätzen der Entfernungen ist.",
        ),
      },
      {
        heading: ls(
          "How long should you stay in Naxos?",
          "Πόσες μέρες χρειάζεται η Νάξος;",
          "Quanti giorni servono a Naxos?",
          "Combien de temps rester à Naxos ?",
          "Wie lange sollte man auf Naxos bleiben?",
        ),
        body: ls(
          "Five to seven nights is the honest answer, and it is longer than most itineraries allow. Three nights covers Chora, two or three west-coast beaches and one mountain drive  -  enough to enjoy but not enough to understand the island. Five nights adds Apollonas in the north, a proper day in the Tragea valley, and time to find a beach you like enough to return to. Seven lets you add Mount Zas, a boat trip to the Small Cyclades, and the unhurried second visit to a taverna that is usually the memory people take home. If you only have two nights, Naxos still beats a rushed Santorini stop  -  but base yourself in Chora and accept that you are seeing a fraction.",
          "Πέντε έως επτά διανυκτερεύσεις είναι η ειλικρινής απάντηση. Τρεις νύχτες καλύπτουν τη Χώρα, δύο-τρεις δυτικές παραλίες και μία ορεινή διαδρομή. Πέντε προσθέτουν τον Απόλλωνα, μια πλήρη ημέρα στην Τραγαία και χρόνο να βρείτε την παραλία σας. Επτά επιτρέπουν τον Ζα, μια εκδρομή στις Μικρές Κυκλάδες και τη δεύτερη, χαλαρή επίσκεψη στην ταβέρνα που τελικά μένει στη μνήμη.",
          "Cinque-sette notti è la risposta onesta. Tre notti coprono Chora, due o tre spiagge occidentali e un giro in montagna. Cinque aggiungono Apollonas, una giornata piena nella valle di Tragea e il tempo di trovare la tua spiaggia. Sette permettono il Monte Zas, una gita alle Piccole Cicladi e la seconda visita senza fretta alla taverna che poi resta nei ricordi.",
          "Cinq à sept nuits, c'est la réponse honnête. Trois nuits couvrent Chora, deux ou trois plages de la côte ouest et une virée en montagne. Cinq ajoutent Apollonas, une journée entière dans la vallée de Tragea et le temps de trouver votre plage. Sept permettent le mont Zas, une excursion aux Petites Cyclades et cette deuxième visite tranquille à la taverne dont on se souvient.",
          "Fünf bis sieben Nächte ist die ehrliche Antwort. Drei Nächte reichen für Chora, zwei bis drei Weststrände und eine Bergtour. Fünf ergänzen Apollonas, einen ganzen Tag im Tragea-Tal und Zeit, den eigenen Lieblingsstrand zu finden. Sieben erlauben den Mount Zas, einen Ausflug zu den Kleinen Kykladen und den zweiten, entspannten Besuch in der Taverne, an den man sich später erinnert.",
        ),
      },
      {
        heading: ls(
          "Where to base yourself",
          "Πού να μείνετε",
          "Dove alloggiare",
          "Où loger",
          "Wo Sie wohnen sollten",
        ),
        body: ls(
          "Chora (Naxos Town) is the default and the right choice for most first visits: the port, the Kastro, the Portara, the best restaurant density and Agios Georgios beach are all walkable, and every road on the island starts here. Agios Prokopios and Agia Anna are 10 minutes south and trade the town atmosphere for a better beach at your door  -  ideal with small children. Plaka suits people who want a long quiet beach and a car. Stelida sits on the hill between Chora and the beaches with the island's best sunset views and the newer hotels. Mikri Vigla is for kitesurfers and nobody else. The mountain villages  -  Chalki, Filoti, Apeiranthos  -  are extraordinary to visit and a genuine commitment to sleep in: 30–45 minutes of switchbacks from the nearest swimmable beach.",
          "Η Χώρα είναι η προεπιλογή και η σωστή επιλογή για την πρώτη επίσκεψη: λιμάνι, Κάστρο, Πορτάρα, εστιατόρια και ο Άγιος Γεώργιος με τα πόδια. Ο Άγιος Προκόπιος και η Αγία Άννα απέχουν 10 λεπτά και προσφέρουν καλύτερη παραλία  -  ιδανικά με μικρά παιδιά. Η Πλάκα ταιριάζει σε όσους θέλουν μεγάλη ήσυχη παραλία και αυτοκίνητο. Η Στελίδα έχει την καλύτερη θέα ηλιοβασιλέματος. Τα ορεινά χωριά είναι εξαιρετικά για επίσκεψη αλλά απαιτητικά για διαμονή.",
          "Chora è la scelta predefinita e giusta per la prima visita: porto, Kastro, Portara, ristoranti e la spiaggia di Agios Georgios a piedi. Agios Prokopios e Agia Anna distano 10 minuti e offrono una spiaggia migliore  -  ideali con bambini piccoli. Plaka è per chi vuole una spiaggia lunga e tranquilla e ha l'auto. Stelida ha i tramonti migliori. I villaggi di montagna sono splendidi da visitare ma impegnativi per dormirci.",
          "Chora est le choix par défaut et le bon pour une première visite : port, Kastro, Portara, restaurants et la plage d'Agios Georgios à pied. Agios Prokopios et Agia Anna sont à 10 minutes et offrent une meilleure plage  -  idéal avec de jeunes enfants. Plaka convient à ceux qui veulent une longue plage tranquille et une voiture. Stelida offre les plus beaux couchers de soleil. Les villages de montagne sont superbes à visiter mais exigeants pour y dormir.",
          "Chora ist die Standardwahl und für den ersten Besuch die richtige: Hafen, Kastro, Portara, Restaurants und der Strand Agios Georgios sind zu Fuß erreichbar. Agios Prokopios und Agia Anna liegen 10 Minuten entfernt und bieten den besseren Strand  -  ideal mit kleinen Kindern. Plaka passt zu langen, ruhigen Stränden und einem Auto. Stelida hat die besten Sonnenuntergänge. Die Bergdörfer sind großartig zum Besuchen, aber anspruchsvoll zum Übernachten.",
        ),
      },
      {
        heading: ls(
          "What a week in Naxos costs",
          "Πόσο κοστίζει μια εβδομάδα στη Νάξο",
          "Quanto costa una settimana a Naxos",
          "Combien coûte une semaine à Naxos",
          "Was eine Woche auf Naxos kostet",
        ),
        body: ls(
          "Naxos is one of the better-value Cyclades islands, meaningfully cheaper than Mykonos or Santorini and roughly level with Paros. In shoulder season expect €60–110 a night for a good double room, €12–20 per person for a taverna dinner with wine, €4 for a coffee, €8–12 for a beach sunbed pair and €30–45 a day for a small rental car. In peak August the accommodation figure roughly doubles while food and car hire rise more modestly. A realistic mid-range budget for two people in June, excluding flights and ferries, lands around €160–200 a day all-in. The single biggest saving available is travelling in the second half of September, when the sea is at its warmest, the meltemi has eased and prices have dropped back to shoulder rates.",
          "Η Νάξος είναι από τα πιο οικονομικά νησιά των Κυκλάδων. Στη μέση περίοδο υπολογίστε €60–110 τη νύχτα για καλό δίκλινο, €12–20 ανά άτομο για δείπνο σε ταβέρνα, €4 για καφέ, €8–12 για δύο ξαπλώστρες και €30–45 την ημέρα για μικρό αυτοκίνητο. Τον Αύγουστο η διαμονή περίπου διπλασιάζεται. Η μεγαλύτερη οικονομία είναι το δεύτερο δεκαπενθήμερο του Σεπτεμβρίου.",
          "Naxos è tra le isole più convenienti delle Cicladi. In media stagione: €60–110 a notte per una buona doppia, €12–20 a persona per una cena in taverna, €4 per un caffè, €8–12 per due lettini e €30–45 al giorno per un'auto piccola. Ad agosto l'alloggio raddoppia. Il risparmio maggiore è la seconda metà di settembre.",
          "Naxos est l'une des Cyclades les plus abordables. En moyenne saison : €60–110 la nuit pour une bonne chambre double, €12–20 par personne pour un dîner en taverne, €4 le café, €8–12 pour deux transats et €30–45 par jour pour une petite voiture. En août, l'hébergement double. La meilleure économie : la seconde moitié de septembre.",
          "Naxos gehört zu den günstigeren Kykladeninseln. In der Nebensaison: €60–110 pro Nacht für ein gutes Doppelzimmer, €12–20 pro Person für ein Taverne-Abendessen, €4 für einen Kaffee, €8–12 für zwei Liegen und €30–45 pro Tag für einen Kleinwagen. Im August verdoppelt sich der Übernachtungspreis. Die größte Ersparnis liegt in der zweiten Septemberhälfte.",
        ),
      },
      {
        heading: ls(
          "Getting around once you arrive",
          "Μετακινήσεις στο νησί",
          "Spostarsi una volta arrivati",
          "Se déplacer une fois sur place",
          "Fortbewegung nach der Ankunft",
        ),
        body: ls(
          "KTEL buses run frequently from the Chora port to Agios Prokopios, Agia Anna and Plaka through July and August, and three to four times daily to Filoti, Apeiranthos and Apollonas with the last inland return typically at 16:00–17:00. That covers perhaps a fifth of the island. Mikri Vigla, Alyko, Pyrgaki, Kastraki, the Tragea churches and every roadside taverna worth stopping at are not on a bus route. Taxis exist but are few  -  around 20 for the whole island  -  and effectively unobtainable at peak times. A rental car is not a luxury here; it is the difference between seeing Naxos and seeing three beaches. We deliver free to the port, the airport and any hotel on the island, which also solves the awkward part: arriving on a 23:00 ferry when every rental counter is closed.",
          "Τα ΚΤΕΛ εκτελούν συχνά δρομολόγια προς Άγιο Προκόπιο, Αγία Άννα και Πλάκα, και τρία-τέσσερα ημερησίως προς Φιλώτι, Απείρανθο και Απόλλωνα με τελευταία επιστροφή συνήθως 16:00–17:00. Καλύπτουν περίπου το ένα πέμπτο του νησιού. Η Μικρή Βίγλα, το Αλυκό, το Πυργάκι και οι εκκλησίες της Τραγαίας δεν εξυπηρετούνται. Τα ταξί είναι λίγα. Παραδίδουμε δωρεάν σε λιμάνι, αεροδρόμιο και ξενοδοχεία.",
          "Gli autobus KTEL collegano spesso Agios Prokopios, Agia Anna e Plaka, e tre-quattro volte al giorno Filoti, Apeiranthos e Apollonas con ultimo rientro tipicamente alle 16:00–17:00. Coprono circa un quinto dell'isola. Mikri Vigla, Alyko, Pyrgaki e le chiese di Tragea non sono serviti. I taxi sono pochi. Consegniamo gratis a porto, aeroporto e hotel.",
          "Les bus KTEL desservent fréquemment Agios Prokopios, Agia Anna et Plaka, et trois à quatre fois par jour Filoti, Apeiranthos et Apollonas, dernier retour vers 16h–17h. Cela couvre environ un cinquième de l'île. Mikri Vigla, Alyko, Pyrgaki et les églises de Tragea ne sont pas desservis. Les taxis sont rares. Nous livrons gratuitement au port, à l'aéroport et à l'hôtel.",
          "KTEL-Busse fahren häufig nach Agios Prokopios, Agia Anna und Plaka sowie drei- bis viermal täglich nach Filoti, Apeiranthos und Apollonas, letzte Rückfahrt meist 16:00–17:00 Uhr. Das deckt etwa ein Fünftel der Insel ab. Mikri Vigla, Alyko, Pyrgaki und die Tragea-Kirchen werden nicht bedient. Taxis sind rar. Wir liefern kostenlos an Hafen, Flughafen und Hotel.",
        ),
      },
    ],
    faq: [
      {
        q: ls(
          "Is Naxos worth visiting?",
          "Αξίζει να επισκεφθείτε τη Νάξο;",
          "Vale la pena visitare Naxos?",
          "Naxos vaut-elle le détour ?",
          "Lohnt sich ein Besuch auf Naxos?",
        ),
        a: ls(
          "Yes  -  particularly if you want a Greek island that still functions as a real place. Naxos combines the best sandy beaches in the Cyclades with mountain villages, ancient sites and genuinely good food, at noticeably lower prices than Mykonos or Santorini, and it is large enough that it never feels crowded even in August.",
          "Ναι, ιδιαίτερα αν θέλετε ένα ελληνικό νησί που λειτουργεί ως πραγματικός τόπος. Συνδυάζει τις καλύτερες αμμώδεις παραλίες των Κυκλάδων με ορεινά χωριά, αρχαιολογικούς χώρους και εξαιρετικό φαγητό, σε αισθητά χαμηλότερες τιμές από Μύκονο ή Σαντορίνη.",
          "Sì, soprattutto se cerchi un'isola greca che funziona ancora come luogo reale. Unisce le migliori spiagge sabbiose delle Cicladi a villaggi di montagna, siti antichi e ottima cucina, a prezzi nettamente inferiori a Mykonos o Santorini.",
          "Oui, surtout si vous cherchez une île grecque qui reste un lieu de vie. Elle combine les meilleures plages de sable des Cyclades avec des villages de montagne, des sites antiques et une excellente cuisine, à des prix nettement inférieurs à Mykonos ou Santorin.",
          "Ja, besonders wenn Sie eine griechische Insel suchen, die noch ein echter Ort ist. Naxos verbindet die besten Sandstrände der Kykladen mit Bergdörfern, antiken Stätten und wirklich gutem Essen  -  zu deutlich niedrigeren Preisen als Mykonos oder Santorin.",
        ),
      },
      {
        q: ls(
          "What is Naxos most known for?",
          "Για τι είναι γνωστή η Νάξος;",
          "Per cosa è famosa Naxos?",
          "Pour quoi Naxos est-elle connue ?",
          "Wofür ist Naxos bekannt?",
        ),
        a: ls(
          "The Portara  -  a 2,500-year-old marble doorway standing alone on the islet of Palatia  -  is the island's emblem. Beyond it, Naxos is known for the longest sandy beaches in the Cyclades, its white marble and emery quarries, Mount Zas where mythology says Zeus was raised, and its food: PDO graviera cheese, potatoes and kitron citron liqueur.",
          "Η Πορτάρα  -  μαρμάρινη πύλη 2.500 ετών στο νησάκι Παλάτια  -  είναι το έμβλημα του νησιού. Επίσης οι μεγαλύτερες αμμουδιές των Κυκλάδων, τα λατομεία μαρμάρου και σμύριδας, ο Ζας όπου η μυθολογία τοποθετεί την ανατροφή του Δία, και το φαγητό: γραβιέρα ΠΟΠ, πατάτες και κίτρο.",
          "La Portara  -  un portale in marmo di 2.500 anni sull'isolotto di Palatia  -  è il simbolo dell'isola. Inoltre le spiagge sabbiose più lunghe delle Cicladi, le cave di marmo e smeriglio, il Monte Zas dove secondo il mito crebbe Zeus, e il cibo: graviera DOP, patate e liquore kitron.",
          "La Portara  -  un portail de marbre de 2 500 ans sur l'îlot de Palatia  -  est l'emblème de l'île. Aussi les plus longues plages de sable des Cyclades, les carrières de marbre et d'émeri, le mont Zas où la mythologie situe l'enfance de Zeus, et sa cuisine : graviéra AOP, pommes de terre et liqueur de cédrat.",
          "Die Portara  -  ein 2.500 Jahre altes Marmortor auf der Insel Palatia  -  ist das Wahrzeichen. Dazu die längsten Sandstrände der Kykladen, Marmor- und Schmirgelbrüche, der Mount Zas, wo Zeus der Mythologie nach aufwuchs, und das Essen: Graviera g.U., Kartoffeln und Kitron-Likör.",
        ),
      },
      {
        q: ls(
          "Do you need a car in Naxos?",
          "Χρειάζεστε αυτοκίνητο στη Νάξο;",
          "Serve l'auto a Naxos?",
            "Faut-il une voiture à Naxos ?",
          "Braucht man auf Naxos ein Auto?",
        ),
        a: ls(
          "For anything beyond the three closest beaches, yes. Buses reach Agios Prokopios, Agia Anna and Plaka reliably and the mountain villages three or four times a day, but Mikri Vigla, Alyko, Pyrgaki and the Tragea churches have no service at all. Most visitors who rent for three days or more say it was the best money they spent on the island.",
          "Για οτιδήποτε πέρα από τις τρεις κοντινότερες παραλίες, ναι. Τα λεωφορεία φτάνουν αξιόπιστα στον Άγιο Προκόπιο, την Αγία Άννα και την Πλάκα, αλλά η Μικρή Βίγλα, το Αλυκό και το Πυργάκι δεν εξυπηρετούνται καθόλου.",
          "Per tutto ciò che va oltre le tre spiagge più vicine, sì. Gli autobus raggiungono Agios Prokopios, Agia Anna e Plaka, ma Mikri Vigla, Alyko e Pyrgaki non sono serviti affatto.",
          "Pour tout ce qui dépasse les trois plages les plus proches, oui. Les bus desservent Agios Prokopios, Agia Anna et Plaka, mais Mikri Vigla, Alyko et Pyrgaki ne sont pas desservis du tout.",
          "Für alles jenseits der drei nächstgelegenen Strände: ja. Busse erreichen Agios Prokopios, Agia Anna und Plaka zuverlässig, aber Mikri Vigla, Alyko und Pyrgaki werden gar nicht bedient.",
        ),
      },
      {
        q: ls(
          "Is Naxos better than Santorini?",
          "Είναι η Νάξος καλύτερη από τη Σαντορίνη;",
          "Naxos è meglio di Santorini?",
          "Naxos est-elle mieux que Santorin ?",
          "Ist Naxos besser als Santorin?",
        ),
        a: ls(
          "They are not really comparable. Santorini has the caldera view and nothing else like it on earth; Naxos has swimmable sandy beaches, real villages, better food and half the prices. If you want one spectacular sight, go to Santorini for two nights. If you want a holiday, go to Naxos for a week. Many travellers do both  -  the ferry between them takes about two hours.",
          "Δεν συγκρίνονται πραγματικά. Η Σαντορίνη έχει τη θέα της καλντέρας· η Νάξος έχει αμμώδεις παραλίες για κολύμπι, αληθινά χωριά, καλύτερο φαγητό και τις μισές τιμές. Πολλοί ταξιδιώτες επισκέπτονται και τα δύο  -  το πλοίο μεταξύ τους κάνει περίπου δύο ώρες.",
          "Non sono davvero paragonabili. Santorini ha la vista sulla caldera; Naxos ha spiagge sabbiose balneabili, villaggi veri, cibo migliore e prezzi dimezzati. Molti visitano entrambe  -  il traghetto impiega circa due ore.",
          "Elles ne sont pas vraiment comparables. Santorin a la vue sur la caldeira ; Naxos a des plages de sable où l'on nage, de vrais villages, une meilleure cuisine et des prix deux fois moindres. Beaucoup font les deux  -  le ferry met environ deux heures.",
          "Sie sind kaum vergleichbar. Santorin hat den Caldera-Blick; Naxos hat badetaugliche Sandstrände, echte Dörfer, besseres Essen und halb so hohe Preise. Viele besuchen beide  -  die Fähre braucht etwa zwei Stunden.",
        ),
      },
      {
        q: ls(
          "What is the best month to visit Naxos?",
          "Ποιος είναι ο καλύτερος μήνας για τη Νάξο;",
          "Qual è il mese migliore per visitare Naxos?",
          "Quel est le meilleur mois pour visiter Naxos ?",
          "Welcher Monat eignet sich am besten für Naxos?",
        ),
        a: ls(
          "September, and it is not close. The sea is at its warmest after a summer of heating, the meltemi wind has eased, the crowds have gone home with the school holidays and accommodation drops back to shoulder pricing. June is the runner-up: everything is open, the island is green and the heat is manageable.",
          "Ο Σεπτέμβριος, με διαφορά. Η θάλασσα είναι στο θερμότερο σημείο της, το μελτέμι έχει κοπάσει, ο κόσμος έχει φύγει και οι τιμές επιστρέφουν σε επίπεδα μέσης περιόδου. Δεύτερος ο Ιούνιος: όλα ανοιχτά, το νησί καταπράσινο και η ζέστη διαχειρίσιμη.",
          "Settembre, senza dubbio. Il mare è al massimo del calore, il meltemi si è placato, la folla è tornata a casa e i prezzi scendono. Secondo posto a giugno: tutto aperto, isola verde e caldo gestibile.",
          "Septembre, sans hésiter. La mer est à son plus chaud, le meltemi s'est calmé, la foule est repartie et les prix baissent. Juin arrive second : tout est ouvert, l'île est verte et la chaleur supportable.",
          "September, mit Abstand. Das Meer ist am wärmsten, der Meltemi hat nachgelassen, die Menge ist abgereist und die Preise sinken. Juni folgt: alles geöffnet, die Insel grün und die Hitze angenehm.",
        ),
      },
      {
        q: ls(
          "How do you get to Naxos?",
          "Πώς φτάνετε στη Νάξο;",
          "Come si arriva a Naxos?",
          "Comment se rendre à Naxos ?",
          "Wie kommt man nach Naxos?",
        ),
        a: ls(
          "By ferry from Piraeus (3h15 by high-speed, 5h by conventional) or Rafina, and by inter-island ferry from Paros, Mykonos, Santorini and Ios. Naxos Island National Airport (JNX) takes domestic flights from Athens in 45 minutes, but the runway is short so only small turboprops operate and seats sell out early.",
          "Με πλοίο από Πειραιά (3ω15 με ταχύπλοο, 5ω με συμβατικό) ή Ραφήνα, και με ενδοκυκλαδικά από Πάρο, Μύκονο, Σαντορίνη και Ίο. Το αεροδρόμιο (JNX) δέχεται πτήσεις από Αθήνα σε 45 λεπτά, αλλά ο διάδρομος είναι μικρός και οι θέσεις λίγες.",
          "In traghetto dal Pireo (3h15 con l'alta velocità, 5h con il convenzionale) o da Rafina, e con collegamenti da Paros, Mykonos, Santorini e Ios. L'aeroporto (JNX) riceve voli da Atene in 45 minuti, ma la pista è corta e i posti si esauriscono presto.",
          "En ferry depuis Le Pirée (3h15 en grande vitesse, 5h en conventionnel) ou Rafina, et en liaisons depuis Paros, Mykonos, Santorin et Ios. L'aéroport (JNX) reçoit des vols d'Athènes en 45 minutes, mais la piste est courte et les places partent vite.",
          "Mit der Fähre ab Piräus (3:15 Std. mit dem Schnellboot, 5 Std. konventionell) oder Rafina sowie mit Verbindungen von Paros, Mykonos, Santorin und Ios. Der Flughafen (JNX) empfängt Flüge aus Athen in 45 Minuten, doch die Piste ist kurz und Plätze sind schnell weg.",
        ),
      },
    ],
  },
  {
    slug: "things-to-do-in-naxos",
    cluster: "plan",
    title: ls(
      "21 best things to do in Naxos in 2026 (from people who live here)",
      "21 πράγματα να κάνετε στη Νάξο το 2026",
      "21 cose da fare a Naxos nel 2026",
      "21 choses à faire à Naxos en 2026",
      "21 Dinge, die man 2026 auf Naxos tun sollte",
    ),
    excerpt: ls(
      "Not a list of everything  -  a list of what is actually worth your time, ordered by how often we send guests there and honest about which ones need a car.",
      "Όχι μια λίστα με τα πάντα, αλλά με όσα πραγματικά αξίζουν τον χρόνο σας  -  και ποια χρειάζονται αυτοκίνητο.",
      "Non un elenco di tutto, ma di ciò che vale davvero il tuo tempo  -  e quali richiedono l'auto.",
      "Pas une liste de tout, mais de ce qui vaut vraiment votre temps  -  et ce qui nécessite une voiture.",
      "Keine Liste von allem, sondern von dem, was Ihre Zeit wirklich wert ist  -  und wofür Sie ein Auto brauchen.",
    ),
    answer: ls(
      "The essentials are the Portara at sunset, the Kastro alleys in Chora, a swim at Plaka or Agios Prokopios, lunch in Apeiranthos, the Tragea valley's Byzantine churches, the Kouros of Apollonas, the Temple of Demeter, and a hike up Mount Zas. Ten of the twenty-one below are unreachable without a car.",
      "Τα βασικά: Πορτάρα στο ηλιοβασίλεμα, τα σοκάκια του Κάστρου, μπάνιο στην Πλάκα ή τον Άγιο Προκόπιο, μεσημεριανό στην Απείρανθο, οι βυζαντινές εκκλησίες της Τραγαίας, ο Κούρος του Απόλλωνα, ο Ναός της Δήμητρας και ανάβαση στον Ζα. Δέκα από τα εικοσιένα χρειάζονται αυτοκίνητο.",
      "Gli essenziali: la Portara al tramonto, i vicoli del Kastro, un bagno a Plaka o Agios Prokopios, pranzo ad Apeiranthos, le chiese bizantine di Tragea, il Kouros di Apollonas, il Tempio di Demetra e la salita al Monte Zas. Dieci dei ventuno richiedono l'auto.",
      "L'essentiel : la Portara au coucher du soleil, les ruelles du Kastro, une baignade à Plaka ou Agios Prokopios, un déjeuner à Apeiranthos, les églises byzantines de Tragea, le Kouros d'Apollonas, le temple de Déméter et l'ascension du mont Zas. Dix des vingt-et-un nécessitent une voiture.",
      "Das Wesentliche: die Portara bei Sonnenuntergang, die Gassen des Kastro, ein Bad in Plaka oder Agios Prokopios, Mittagessen in Apeiranthos, die byzantinischen Kirchen des Tragea-Tals, der Kouros von Apollonas, der Demeter-Tempel und der Aufstieg zum Mount Zas. Zehn der einundzwanzig brauchen ein Auto.",
    ),
    hero: "/images/naxos/gallery/naxos-portara.jpg",
    publishedAt: "2026-08-22",
    updatedAt: "2026-08-22",
    readingTime: 14,
    keywords: [
      "things to do in naxos",
      "what to do in naxos",
      "naxos attractions",
      "best things to do naxos",
      "naxos sightseeing",
    ],
    related: ["naxos-travel-guide", "best-beaches-in-naxos", "naxos-villages", "mount-zas-and-hiking"],
    vehiclePicks: ["hyundai-i10", "suzuki-jimny", "citroen-berlingo-7"],
    locationPicks: ["naxos-town", "apeiranthos", "filoti"],
    sections: [
      {
        heading: ls(
          "Watch the sunset from the Portara",
          "Ηλιοβασίλεμα στην Πορτάρα",
          "Il tramonto dalla Portara",
          "Le coucher de soleil depuis la Portara",
          "Sonnenuntergang an der Portara",
        ),
        body: ls(
          "The Portara is a single marble doorway, six metres high, standing alone on the islet of Palatia at the end of a causeway from Chora's harbour. It was to be the entrance of a temple to Apollo begun around 530 BC and abandoned when the tyrant Lygdamis fell; the rest of the marble was carted off over the centuries and only the doorframe  -  too heavy to move  -  remains. Walk out about forty minutes before sunset, because the causeway fills up and the good rock ledges go first. The trick locals use: rather than standing in the crowd on the islet, take a table at one of the harbour-front tavernas facing it and watch the sun set *through* the frame with a drink in hand. Free, open at all hours, and the one thing on Naxos you should not skip.",
          "Η Πορτάρα είναι μια μαρμάρινη πύλη έξι μέτρων στο νησάκι Παλάτια, στην είσοδο του λιμανιού της Χώρας. Ήταν η είσοδος ναού του Απόλλωνα που ξεκίνησε γύρω στο 530 π.Χ. και έμεινε ημιτελής. Πηγαίνετε σαράντα λεπτά πριν τη δύση. Το κόλπο των ντόπιων: αντί να στριμωχτείτε στο νησάκι, καθίστε σε ταβέρνα στην προκυμαία απέναντι και δείτε τον ήλιο να δύει μέσα από το πλαίσιο.",
          "La Portara è un portale in marmo alto sei metri sull'isolotto di Palatia, all'ingresso del porto di Chora. Era l'accesso di un tempio ad Apollo iniziato verso il 530 a.C. e mai completato. Arriva quaranta minuti prima del tramonto. Il trucco dei locali: invece di stare tra la folla, siediti in una taverna sul porto di fronte e guarda il sole calare attraverso la cornice.",
          "La Portara est un portail de marbre de six mètres sur l'îlot de Palatia, à l'entrée du port de Chora. C'était l'accès d'un temple d'Apollon commencé vers 530 av. J.-C. et jamais achevé. Arrivez quarante minutes avant le coucher. L'astuce des locaux : plutôt que la foule, installez-vous à une taverne du port en face et regardez le soleil se coucher à travers le cadre.",
          "Die Portara ist ein sechs Meter hohes Marmortor auf der Insel Palatia am Hafeneingang von Chora. Es war der Zugang zu einem Apollon-Tempel, begonnen um 530 v. Chr. und nie vollendet. Kommen Sie vierzig Minuten vor Sonnenuntergang. Der Trick der Einheimischen: statt im Gedränge zu stehen, an einer Hafentaverne gegenüber Platz nehmen und die Sonne durch den Rahmen sinken sehen.",
        ),
      },
      {
        heading: ls(
          "Get lost in the Kastro",
          "Χαθείτε στο Κάστρο",
          "Perditi nel Kastro",
          "Perdez-vous dans le Kastro",
          "Verlieren Sie sich im Kastro",
        ),
        body: ls(
          "Chora's old town climbs the hill behind the harbour in three tiers, and the top one is the Kastro: the walled Venetian quarter built after Marco Sanudo took the island in 1207 and made it the capital of the Duchy of the Archipelago. Unusually for Greece, Catholic families still live in the tower houses their ancestors built, coats of arms still above the doors. Inside the walls are the Archaeological Museum (in the old Jesuit school where Nikos Kazantzakis briefly studied), the Catholic cathedral, and the Della Rocca-Barozzi Venetian Museum, which is a private home you can actually tour. Go up in the late afternoon when the marble underfoot turns gold. Getting lost is the activity; the hill is small enough that you cannot really go wrong.",
          "Η παλιά πόλη της Χώρας ανεβαίνει τον λόφο σε τρία επίπεδα και στην κορυφή βρίσκεται το Κάστρο: η βενετσιάνικη συνοικία που χτίστηκε μετά το 1207. Καθολικές οικογένειες ζουν ακόμη στους πύργους των προγόνων τους. Μέσα στα τείχη: το Αρχαιολογικό Μουσείο, ο καθολικός καθεδρικός και το Βενετσιάνικο Μουσείο Ντέλα Ρόκα-Μπαρότσι. Ανεβείτε αργά το απόγευμα.",
          "Il centro storico di Chora sale la collina su tre livelli e in cima c'è il Kastro: il quartiere veneziano costruito dopo il 1207. Famiglie cattoliche vivono ancora nelle case-torre dei loro antenati. Dentro le mura: il Museo Archeologico, la cattedrale cattolica e il Museo Veneziano Della Rocca-Barozzi. Sali nel tardo pomeriggio.",
          "La vieille ville de Chora grimpe la colline sur trois niveaux et au sommet se trouve le Kastro : le quartier vénitien bâti après 1207. Des familles catholiques habitent encore les maisons-tours de leurs ancêtres. Dans les murs : le Musée archéologique, la cathédrale catholique et le Musée vénitien Della Rocca-Barozzi. Montez en fin d'après-midi.",
          "Die Altstadt von Chora steigt in drei Ebenen den Hügel hinauf, oben liegt das Kastro: das venezianische Viertel, erbaut nach 1207. Katholische Familien wohnen noch in den Turmhäusern ihrer Vorfahren. Innerhalb der Mauern: Archäologisches Museum, katholische Kathedrale und das Venezianische Museum Della Rocca-Barozzi. Gehen Sie am späten Nachmittag hinauf.",
        ),
      },
      {
        heading: ls(
          "Drive the Tragea valley and its Byzantine churches",
          "Οδηγήστε στην Τραγαία και τις βυζαντινές εκκλησίες",
          "Percorri la valle di Tragea e le sue chiese bizantine",
          "Parcourez la vallée de Tragea et ses églises byzantines",
          "Fahren Sie durch das Tragea-Tal und seine byzantinischen Kirchen",
        ),
        body: ls(
          "The Tragea is a wide inland valley of ancient olive groves between Chalki and Filoti, and it contains one of the densest concentrations of Byzantine churches anywhere in Greece  -  more than thirty within a few kilometres, many with frescoes from the 9th to 13th centuries. Panagia Drosiani near Moni is the one to prioritise: parts of it date to the 6th century, making it among the oldest churches in the Balkans still in use, and the layered frescoes inside include a rare depiction of Christ as a young man. Panagia Protothronos in Chalki and Agios Georgios Diasoritis nearby are both worth the stop. Opening hours are informal  -  often a caretaker with a key who appears when you arrive. This is a full half-day and it requires a car.",
          "Η Τραγαία είναι μια πλατιά κοιλάδα με αιωνόβιους ελαιώνες ανάμεσα στο Χαλκί και το Φιλώτι, με μία από τις πυκνότερες συγκεντρώσεις βυζαντινών εκκλησιών στην Ελλάδα  -  πάνω από τριάντα, πολλές με τοιχογραφίες 9ου–13ου αιώνα. Η Παναγία Δροσιανή είναι η σημαντικότερη: τμήματά της χρονολογούνται στον 6ο αιώνα. Απαιτεί αυτοκίνητο και μισή ημέρα.",
          "La Tragea è un'ampia valle interna di uliveti secolari tra Chalki e Filoti, con una delle concentrazioni più dense di chiese bizantine in Grecia  -  oltre trenta, molte con affreschi dal IX al XIII secolo. Panagia Drosiani è la priorità: parti risalgono al VI secolo. Richiede l'auto e mezza giornata.",
          "La Tragea est une large vallée intérieure d'oliveraies anciennes entre Chalki et Filoti, avec l'une des plus fortes concentrations d'églises byzantines de Grèce  -  plus de trente, beaucoup avec des fresques du IXe au XIIIe siècle. Panagia Drosiani est la priorité : certaines parties datent du VIe siècle. Nécessite une voiture et une demi-journée.",
          "Das Tragea ist ein weites Binnental mit uralten Olivenhainen zwischen Chalki und Filoti und besitzt eine der dichtesten Ansammlungen byzantinischer Kirchen Griechenlands  -  über dreißig, viele mit Fresken vom 9. bis 13. Jahrhundert. Panagia Drosiani hat Priorität: Teile stammen aus dem 6. Jahrhundert. Erfordert Auto und einen halben Tag.",
        ),
      },
      {
        heading: ls(
          "Have lunch in Apeiranthos",
          "Μεσημεριανό στην Απείρανθο",
          "Pranzo ad Apeiranthos",
          "Déjeuner à Apeiranthos",
          "Mittagessen in Apeiranthos",
        ),
        body: ls(
          "Apeiranthos sits at 600 m on the eastern flank of Mount Fanari and is the most striking village on the island: entirely paved in marble, built by settlers from Crete in the 17th century, and still speaking a dialect with recognisably Cretan traces. There are four small museums along one street  -  archaeological, geological, folk art and natural history  -  which tells you something about the place. Park at the entrance; the village itself is not driveable. Eat at one of the tavernas on the main lane and order whatever the goat dish of the day is. The drive up from Filoti is 25 minutes of switchbacks with a view over the Tragea that stops most people at least twice.",
          "Η Απείρανθος βρίσκεται στα 600 μ. και είναι το πιο εντυπωσιακό χωριό του νησιού: εξ ολοκλήρου μαρμαροστρωμένο, χτισμένο από Κρητικούς τον 17ο αιώνα, με διάλεκτο που διατηρεί κρητικά στοιχεία. Τέσσερα μικρά μουσεία σε έναν δρόμο. Παρκάρετε στην είσοδο. Φάτε σε ταβέρνα στον κεντρικό δρόμο και ζητήστε το κατσικάκι της ημέρας.",
          "Apeiranthos si trova a 600 m ed è il villaggio più suggestivo dell'isola: interamente lastricato in marmo, fondato da cretesi nel XVII secolo, con un dialetto che conserva tracce cretesi. Quattro piccoli musei lungo una strada. Parcheggia all'ingresso. Mangia in una taverna della via principale e chiedi il capretto del giorno.",
          "Apeiranthos se situe à 600 m et c'est le plus saisissant village de l'île : entièrement pavé de marbre, fondé par des Crétois au XVIIe siècle, avec un dialecte gardant des traces crétoises. Quatre petits musées sur une seule rue. Garez-vous à l'entrée. Mangez dans une taverne de la rue principale et demandez le chevreau du jour.",
          "Apeiranthos liegt auf 600 m und ist das eindrucksvollste Dorf der Insel: vollständig mit Marmor gepflastert, im 17. Jahrhundert von Kretern gegründet, mit einem Dialekt, der kretische Spuren bewahrt. Vier kleine Museen an einer Straße. Parken Sie am Ortseingang. Essen Sie in einer Taverne an der Hauptgasse und fragen Sie nach dem Ziegengericht des Tages.",
        ),
      },
      {
        heading: ls(
          "Find the three Kouroi",
          "Βρείτε τους τρεις Κούρους",
          "Trova i tre Kouroi",
          "Trouvez les trois Kouroi",
          "Finden Sie die drei Kouroi",
        ),
        body: ls(
          "Naxos has three colossal unfinished marble statues lying exactly where they were abandoned 2,600 years ago, and walking up to one is genuinely startling. The Kouros of Apollonas is the largest at 10.7 m, lying on his back in a quarry above the village in the far north  -  probably a bearded Dionysus, abandoned when a crack appeared. Two more, both around 5.5 m, lie in the olive groves at Flerio near Melanes, a short signed walk from a small car park and much quieter. The Flerio pair are the better visit: there is shade, a stream, a tiny taverna, and usually nobody else. All three need a car; Apollonas is an hour each way from Chora on a beautiful but demanding mountain road.",
          "Η Νάξος έχει τρεις κολοσσιαίους ημιτελείς Κούρους στη θέση όπου εγκαταλείφθηκαν πριν από 2.600 χρόνια. Ο Κούρος του Απόλλωνα είναι ο μεγαλύτερος (10,7 μ.). Δύο ακόμη, περίπου 5,5 μ., βρίσκονται στους ελαιώνες του Φλεριού κοντά στις Μέλανες  -  με σκιά, ρυάκι, μικρή ταβέρνα και συνήθως κανέναν άλλο. Χρειάζεται αυτοκίνητο.",
          "Naxos ha tre colossali kouroi incompiuti nel punto in cui furono abbandonati 2.600 anni fa. Il Kouros di Apollonas è il più grande (10,7 m). Altri due, circa 5,5 m, giacciono negli uliveti di Flerio vicino a Melanes  -  con ombra, un ruscello, una piccola taverna e di solito nessun altro. Serve l'auto.",
          "Naxos possède trois kouroï colossaux inachevés, là où ils furent abandonnés il y a 2 600 ans. Le Kouros d'Apollonas est le plus grand (10,7 m). Deux autres, d'environ 5,5 m, reposent dans les oliveraies de Flerio près de Melanes  -  avec de l'ombre, un ruisseau, une petite taverne et souvent personne. Voiture nécessaire.",
          "Naxos hat drei kolossale unvollendete Kouroi, genau dort, wo sie vor 2.600 Jahren zurückgelassen wurden. Der Kouros von Apollonas ist mit 10,7 m der größte. Zwei weitere, je etwa 5,5 m, liegen in den Olivenhainen von Flerio bei Melanes  -  mit Schatten, einem Bach, einer kleinen Taverne und meist niemandem sonst. Auto erforderlich.",
        ),
      },
      {
        heading: ls(
          "The rest of the twenty-one",
          "Τα υπόλοιπα από τα εικοσιένα",
          "Il resto dei ventuno",
          "Le reste des vingt-et-un",
          "Der Rest der einundzwanzig",
        ),
        body: ls(
          "Swim at Plaka, Agios Prokopios and Alyko. Climb Mount Zas from the Agia Marina trailhead (3 hours return). Visit the Temple of Demeter at Sangri, a small, perfect 6th-century BC marble temple with almost no visitors. Taste kitron at the Vallindras distillery in Chalki, working since 1896. Walk the Alyko cedar forest to the painted abandoned hotel. Watch kitesurfers at Mikri Vigla. Eat at a taverna in Moutsouna on the east coast. Take a day boat to Koufonisia or Iraklia. Visit the Bazeos Tower. See the emery mines and the aerial cableway at Koronos. Buy graviera at a village dairy. Have a coffee in Chalki's square. Swim at Panormos in the far south. Visit Agios Georgios beach at dawn, before anyone else. Drive the west coast road at golden hour. And spend one evening doing nothing at all in Filoti's plateia, which is the most Greek thing on the island.",
          "Κολυμπήστε σε Πλάκα, Άγιο Προκόπιο και Αλυκό. Ανεβείτε τον Ζα από την Αγία Μαρίνα (3 ώρες). Επισκεφθείτε τον Ναό της Δήμητρας στο Σαγκρί. Δοκιμάστε κίτρο στο αποστακτήριο Βαλληνδρά στο Χαλκί (από το 1896). Περπατήστε στο κεδρόδασος του Αλυκού. Δείτε τους kitesurfers στη Μικρή Βίγλα. Φάτε στη Μουτσούνα. Πάρτε καΐκι για Κουφονήσια. Επισκεφθείτε τον Πύργο Μπαζαίου. Και περάστε ένα βράδυ χωρίς πρόγραμμα στην πλατεία του Φιλωτίου.",
          "Nuota a Plaka, Agios Prokopios e Alyko. Sali il Monte Zas da Agia Marina (3 ore). Visita il Tempio di Demetra a Sangri. Assaggia il kitron alla distilleria Vallindras di Chalki (dal 1896). Cammina nella foresta di cedri di Alyko. Guarda i kitesurfer a Mikri Vigla. Mangia a Moutsouna. Prendi una barca per Koufonisia. Visita la Torre Bazeos. E passa una sera senza programmi nella piazza di Filoti.",
          "Nagez à Plaka, Agios Prokopios et Alyko. Grimpez le mont Zas depuis Agia Marina (3 h). Visitez le temple de Déméter à Sangri. Goûtez le kitron à la distillerie Vallindras de Chalki (depuis 1896). Marchez dans la forêt de cèdres d'Alyko. Observez les kitesurfeurs à Mikri Vigla. Mangez à Moutsouna. Prenez un bateau pour Koufonissia. Visitez la tour Bazeos. Et passez une soirée sans programme sur la place de Filoti.",
          "Baden Sie in Plaka, Agios Prokopios und Alyko. Besteigen Sie den Mount Zas ab Agia Marina (3 Std.). Besuchen Sie den Demeter-Tempel in Sangri. Probieren Sie Kitron in der Vallindras-Destillerie in Chalki (seit 1896). Wandern Sie durch den Zedernwald von Alyko. Sehen Sie den Kitesurfern in Mikri Vigla zu. Essen Sie in Moutsouna. Nehmen Sie ein Boot nach Koufonisia. Besuchen Sie den Bazeos-Turm. Und verbringen Sie einen Abend ohne Plan auf dem Dorfplatz von Filoti.",
        ),
      },
    ],
    faq: [
      {
        q: ls(
          "What should you not miss in Naxos?",
          "Τι δεν πρέπει να χάσετε στη Νάξο;",
          "Cosa non perdere a Naxos?",
          "Que ne faut-il pas manquer à Naxos ?",
          "Was sollte man auf Naxos nicht verpassen?",
        ),
        a: ls(
          "The Portara at sunset, the Kastro quarter in Chora, one full day in the mountain villages of Chalki, Filoti and Apeiranthos, and a swim at Plaka. If you only do four things on the island, those are the four.",
          "Την Πορτάρα στο ηλιοβασίλεμα, το Κάστρο στη Χώρα, μία ολόκληρη ημέρα στα ορεινά χωριά Χαλκί, Φιλώτι και Απείρανθο, και ένα μπάνιο στην Πλάκα.",
          "La Portara al tramonto, il quartiere Kastro a Chora, una giornata intera nei villaggi di Chalki, Filoti e Apeiranthos, e un bagno a Plaka.",
          "La Portara au coucher du soleil, le quartier du Kastro à Chora, une journée entière dans les villages de Chalki, Filoti et Apeiranthos, et une baignade à Plaka.",
          "Die Portara bei Sonnenuntergang, das Kastro-Viertel in Chora, einen ganzen Tag in den Bergdörfern Chalki, Filoti und Apeiranthos und ein Bad in Plaka.",
        ),
      },
      {
        q: ls(
          "How many days do you need in Naxos?",
          "Πόσες ημέρες χρειάζεστε στη Νάξο;",
          "Quanti giorni servono a Naxos?",
          "Combien de jours faut-il à Naxos ?",
          "Wie viele Tage braucht man auf Naxos?",
        ),
        a: ls(
          "Five to seven. Three is the minimum that lets you see the mountain villages as well as the beaches; below that you are choosing between them. Seven allows Mount Zas, a boat trip to the Small Cyclades and unhurried days.",
          "Πέντε έως επτά. Τρεις είναι το ελάχιστο για να δείτε και τα ορεινά χωριά και τις παραλίες. Επτά επιτρέπουν τον Ζα και μια εκδρομή στις Μικρές Κυκλάδες.",
          "Cinque-sette. Tre è il minimo per vedere sia i villaggi di montagna sia le spiagge. Sette permettono il Monte Zas e una gita alle Piccole Cicladi.",
          "Cinq à sept. Trois est le minimum pour voir à la fois les villages de montagne et les plages. Sept permettent le mont Zas et une excursion aux Petites Cyclades.",
          "Fünf bis sieben. Drei ist das Minimum, um Bergdörfer und Strände zu sehen. Sieben erlauben den Mount Zas und einen Ausflug zu den Kleinen Kykladen.",
        ),
      },
      {
        q: ls(
          "Can you see Naxos without a car?",
          "Μπορείτε να δείτε τη Νάξο χωρίς αυτοκίνητο;",
          "Si può vedere Naxos senza auto?",
          "Peut-on visiter Naxos sans voiture ?",
          "Kann man Naxos ohne Auto sehen?",
        ),
        a: ls(
          "Partly. Buses reach Chora, the three main west-coast beaches and the larger mountain villages. They do not reach Mikri Vigla, Alyko, Pyrgaki, the Flerio kouroi, the Temple of Demeter or most of the Tragea churches  -  which is roughly half of what makes Naxos worth the trip.",
          "Εν μέρει. Τα λεωφορεία φτάνουν στη Χώρα, στις τρεις κύριες δυτικές παραλίες και στα μεγαλύτερα ορεινά χωριά. Δεν φτάνουν στη Μικρή Βίγλα, το Αλυκό, το Πυργάκι, τους Κούρους του Φλεριού ή τον Ναό της Δήμητρας.",
          "In parte. Gli autobus raggiungono Chora, le tre spiagge principali e i villaggi più grandi. Non raggiungono Mikri Vigla, Alyko, Pyrgaki, i kouroi di Flerio o il Tempio di Demetra.",
          "En partie. Les bus desservent Chora, les trois plages principales et les plus grands villages. Ils ne desservent pas Mikri Vigla, Alyko, Pyrgaki, les kouroï de Flerio ni le temple de Déméter.",
          "Teilweise. Busse erreichen Chora, die drei Hauptstrände und die größeren Dörfer. Nicht erreichbar sind Mikri Vigla, Alyko, Pyrgaki, die Kouroi von Flerio und der Demeter-Tempel.",
        ),
      },
      {
        q: ls(
          "Is Naxos good for families with children?",
          "Είναι η Νάξος κατάλληλη για οικογένειες;",
          "Naxos è adatta alle famiglie?",
          "Naxos convient-elle aux familles ?",
          "Ist Naxos für Familien geeignet?",
        ),
        a: ls(
          "Exceptionally. Agios Prokopios and Agia Anna have shallow, gently shelving sand that stays waist-deep a long way out, Chora's old town is car-free, and the island's food is unfussy and cheap. It is the Cyclades island we would pick with young children.",
          "Εξαιρετικά. Ο Άγιος Προκόπιος και η Αγία Άννα έχουν ρηχά νερά με ήπια κλίση, η παλιά πόλη της Χώρας είναι πεζόδρομος και το φαγητό απλό και οικονομικό.",
          "Moltissimo. Agios Prokopios e Agia Anna hanno acque basse e digradanti, il centro storico di Chora è pedonale e il cibo è semplice ed economico.",
          "Parfaitement. Agios Prokopios et Agia Anna ont des eaux peu profondes en pente douce, la vieille ville de Chora est piétonne et la cuisine est simple et abordable.",
          "Hervorragend. Agios Prokopios und Agia Anna haben flach abfallendes Wasser, die Altstadt von Chora ist autofrei und das Essen einfach und günstig.",
        ),
      },
      {
        q: ls(
          "What is there to do in Naxos when it rains?",
          "Τι να κάνετε στη Νάξο όταν βρέχει;",
          "Cosa fare a Naxos quando piove?",
          "Que faire à Naxos quand il pleut ?",
          "Was kann man auf Naxos bei Regen tun?",
        ),
        a: ls(
          "Rain is rare between May and September, but when it comes: the Archaeological Museum in the Kastro, the Della Rocca-Barozzi Venetian Museum, the four museums of Apeiranthos, the Vallindras kitron distillery in Chalki, and the Bazeos Tower. All are indoors and all are within a 40-minute drive of Chora.",
          "Η βροχή είναι σπάνια από Μάιο έως Σεπτέμβριο. Όταν συμβεί: Αρχαιολογικό Μουσείο στο Κάστρο, Βενετσιάνικο Μουσείο, τα τέσσερα μουσεία της Απειράνθου, το αποστακτήριο Βαλληνδρά στο Χαλκί και ο Πύργος Μπαζαίου.",
          "La pioggia è rara da maggio a settembre. Quando arriva: Museo Archeologico nel Kastro, Museo Veneziano, i quattro musei di Apeiranthos, la distilleria Vallindras a Chalki e la Torre Bazeos.",
          "La pluie est rare de mai à septembre. Le cas échéant : Musée archéologique du Kastro, Musée vénitien, les quatre musées d'Apeiranthos, la distillerie Vallindras à Chalki et la tour Bazeos.",
          "Regen ist von Mai bis September selten. Falls doch: Archäologisches Museum im Kastro, Venezianisches Museum, die vier Museen von Apeiranthos, die Vallindras-Destillerie in Chalki und der Bazeos-Turm.",
        ),
      },
      {
        q: ls(
          "Is Naxos a tourist trap?",
          "Είναι η Νάξος τουριστική παγίδα;",
          "Naxos è una trappola per turisti?",
          "Naxos est-elle un piège à touristes ?",
          "Ist Naxos eine Touristenfalle?",
        ),
        a: ls(
          "No, and the reason is structural: Naxos has real agriculture and a year-round population of over 20,000, so tavernas and shops serve locals as well as visitors. The harbour front in August is touristy, as any harbour front is  -  walk two streets inland or five kilometres out and that disappears entirely.",
          "Όχι, και ο λόγος είναι δομικός: η Νάξος έχει πραγματική γεωργία και μόνιμο πληθυσμό άνω των 20.000, οπότε ταβέρνες και καταστήματα εξυπηρετούν και ντόπιους. Η προκυμαία τον Αύγουστο είναι τουριστική  -  δύο δρόμους πιο μέσα αυτό εξαφανίζεται.",
          "No, e il motivo è strutturale: Naxos ha un'agricoltura reale e oltre 20.000 residenti stabili, quindi taverne e negozi servono anche i locali. Il lungomare ad agosto è turistico  -  due strade più all'interno sparisce.",
          "Non, et la raison est structurelle : Naxos a une vraie agriculture et plus de 20 000 habitants à l'année, donc les tavernes servent aussi les locaux. Le front de port en août est touristique  -  deux rues plus loin, cela disparaît.",
          "Nein, und der Grund ist strukturell: Naxos hat echte Landwirtschaft und über 20.000 feste Einwohner, Tavernen und Läden bedienen also auch Einheimische. Die Hafenpromenade ist im August touristisch  -  zwei Straßen landeinwärts verschwindet das.",
        ),
      },
    ],
  },
  {
    slug: "naxos-itinerary",
    cluster: "plan",
    title: ls(
      "Naxos itinerary: 3, 5 and 7-day plans that actually work",
      "Πρόγραμμα για τη Νάξο: διαδρομές 3, 5 και 7 ημερών",
      "Itinerario a Naxos: piani da 3, 5 e 7 giorni che funzionano",
      "Itinéraire à Naxos : plans de 3, 5 et 7 jours qui fonctionnent",
      "Naxos Reiseroute: 3-, 5- und 7-Tage-Pläne, die funktionieren",
    ),
    excerpt: ls(
      "Day-by-day plans built around real driving times, not a map. Where to go each morning, where to eat, and which day to keep free for the weather.",
      "Ημερήσια προγράμματα βασισμένα σε πραγματικούς χρόνους οδήγησης: πού να πάτε κάθε πρωί, πού να φάτε και ποια ημέρα να κρατήσετε ελεύθερη.",
      "Piani giorno per giorno costruiti su tempi di guida reali: dove andare ogni mattina, dove mangiare e quale giorno tenere libero.",
      "Des plans jour par jour basés sur de vrais temps de trajet : où aller chaque matin, où manger et quel jour garder libre.",
      "Tagespläne auf Basis echter Fahrzeiten: wohin an jedem Morgen, wo essen und welchen Tag Sie freihalten sollten.",
    ),
    answer: ls(
      "Three days covers Chora and the Kastro, the west-coast beaches, and one mountain loop through Chalki, Filoti and Apeiranthos. Five adds Apollonas in the north and the Alyko cedar forest in the south. Seven adds Mount Zas, a boat to the Small Cyclades and a genuinely free day. Every plan below assumes a rental car.",
      "Τρεις ημέρες καλύπτουν τη Χώρα και το Κάστρο, τις δυτικές παραλίες και μία ορεινή διαδρομή Χαλκί–Φιλώτι–Απείρανθος. Πέντε προσθέτουν τον Απόλλωνα και το κεδρόδασος του Αλυκού. Επτά προσθέτουν τον Ζα, καΐκι στις Μικρές Κυκλάδες και μια πραγματικά ελεύθερη ημέρα.",
      "Tre giorni coprono Chora e il Kastro, le spiagge occidentali e un giro in montagna tra Chalki, Filoti e Apeiranthos. Cinque aggiungono Apollonas e la foresta di cedri di Alyko. Sette aggiungono il Monte Zas, una barca per le Piccole Cicladi e un giorno davvero libero.",
      "Trois jours couvrent Chora et le Kastro, les plages de l'ouest et une boucle en montagne par Chalki, Filoti et Apeiranthos. Cinq ajoutent Apollonas et la forêt de cèdres d'Alyko. Sept ajoutent le mont Zas, un bateau vers les Petites Cyclades et une journée vraiment libre.",
      "Drei Tage decken Chora und das Kastro, die Weststrände und eine Bergrunde über Chalki, Filoti und Apeiranthos ab. Fünf ergänzen Apollonas und den Zedernwald von Alyko. Sieben ergänzen den Mount Zas, ein Boot zu den Kleinen Kykladen und einen wirklich freien Tag.",
    ),
    hero: "/images/naxos/landscape.jpg",
    publishedAt: "2026-08-22",
    updatedAt: "2026-08-22",
    readingTime: 11,
    keywords: [
      "naxos itinerary",
      "how many days in naxos",
      "naxos 3 day itinerary",
      "naxos 5 day itinerary",
      "naxos road trip",
    ],
    related: ["naxos-travel-guide", "things-to-do-in-naxos", "naxos-villages", "best-beaches-in-naxos"],
    vehiclePicks: ["hyundai-i10", "peugeot-208", "suzuki-jimny"],
    locationPicks: ["naxos-town", "apeiranthos", "mikri-vigla"],
    table: {
      caption: ls(
        "Driving times from Chora (Naxos Town)",
        "Χρόνοι οδήγησης από τη Χώρα",
        "Tempi di guida da Chora",
        "Temps de trajet depuis Chora",
        "Fahrzeiten ab Chora",
      ),
      columns: [
        ls("Destination", "Προορισμός", "Destinazione", "Destination", "Ziel"),
        ls("Distance", "Απόσταση", "Distanza", "Distance", "Entfernung"),
        ls("Drive time", "Χρόνος", "Tempo", "Durée", "Fahrzeit"),
        ls("Road", "Δρόμος", "Strada", "Route", "Straße"),
      ],
      rows: [
        [ls("Agios Prokopios"), ls("6 km"), ls("10 min"), ls("Paved, easy", "Άσφαλτος, εύκολος", "Asfaltata, facile", "Goudronnée, facile", "Asphaltiert, leicht")],
        [ls("Plaka"), ls("8 km"), ls("13 min"), ls("Paved, easy", "Άσφαλτος, εύκολος", "Asfaltata, facile", "Goudronnée, facile", "Asphaltiert, leicht")],
        [ls("Mikri Vigla"), ls("17 km"), ls("25 min"), ls("Paved, easy", "Άσφαλτος, εύκολος", "Asfaltata, facile", "Goudronnée, facile", "Asphaltiert, leicht")],
        [ls("Alyko / Pyrgaki"), ls("22 km"), ls("35 min"), ls("Paved to car park", "Άσφαλτος έως το πάρκινγκ", "Asfaltata fino al parcheggio", "Goudronnée jusqu'au parking", "Asphaltiert bis Parkplatz")],
        [ls("Chalki"), ls("16 km"), ls("22 min"), ls("Paved, narrow", "Άσφαλτος, στενός", "Asfaltata, stretta", "Goudronnée, étroite", "Asphaltiert, eng")],
        [ls("Filoti"), ls("20 km"), ls("28 min"), ls("Paved, narrow", "Άσφαλτος, στενός", "Asfaltata, stretta", "Goudronnée, étroite", "Asphaltiert, eng")],
        [ls("Apeiranthos"), ls("27 km"), ls("45 min"), ls("Switchbacks", "Στροφές", "Tornanti", "Lacets", "Serpentinen")],
        [ls("Apollonas"), ls("48 km"), ls("1 h 05", "1ω 05", "1 h 05", "1 h 05", "1 Std. 05")],
        [ls("Moutsouna"), ls("38 km"), ls("55 min"), ls("Switchbacks", "Στροφές", "Tornanti", "Lacets", "Serpentinen")],
      ],
    },
    sections: [
      {
        heading: ls(
          "Three days: the essentials",
          "Τρεις ημέρες: τα βασικά",
          "Tre giorni: l'essenziale",
          "Trois jours : l'essentiel",
          "Drei Tage: das Wesentliche",
        ),
        body: ls(
          "Day 1  -  Chora. Collect the car at the port or airport, drop your bags, and spend the day on foot: the Kastro in the late morning while it is cool, lunch in the old town, an afternoon swim at Agios Georgios five minutes from the harbour, then the Portara at sunset and dinner on the waterfront. Do not drive on your arrival day; you will be tired and Chora's one-way system is unkind to newcomers. Day 2  -  the mountain loop. Leave by 09:30. Chalki for coffee in the square and the Vallindras kitron distillery, Panagia Drosiani near Moni, then Filoti, then the climb to Apeiranthos for a late lunch. Come back down through Moutsouna if you want the east coast, or retrace for the faster route. Day 3  -  beaches. Agios Prokopios, Agia Anna and Plaka run into each other along one road; pick two, swim, eat at a beach taverna, and finish at Mikri Vigla to watch the kitesurfers before you drive back for the ferry.",
          "Ημέρα 1  -  Χώρα: παραλαβή αυτοκινήτου, Κάστρο το πρωί, μεσημεριανό στην παλιά πόλη, μπάνιο στον Άγιο Γεώργιο, Πορτάρα στο ηλιοβασίλεμα. Μην οδηγήσετε την ημέρα άφιξης. Ημέρα 2  -  ορεινή διαδρομή: αναχώρηση 09:30, Χαλκί, Παναγία Δροσιανή, Φιλώτι, Απείρανθος για αργό μεσημεριανό. Ημέρα 3  -  παραλίες: Άγιος Προκόπιος, Αγία Άννα, Πλάκα και τέλος Μικρή Βίγλα.",
          "Giorno 1  -  Chora: ritiro auto, Kastro in mattinata, pranzo nel centro storico, bagno ad Agios Georgios, Portara al tramonto. Non guidare il giorno dell'arrivo. Giorno 2  -  giro in montagna: partenza 09:30, Chalki, Panagia Drosiani, Filoti, Apeiranthos per pranzo tardi. Giorno 3  -  spiagge: Agios Prokopios, Agia Anna, Plaka e infine Mikri Vigla.",
          "Jour 1  -  Chora : récupération de la voiture, Kastro le matin, déjeuner dans la vieille ville, baignade à Agios Georgios, Portara au coucher du soleil. Ne conduisez pas le jour de l'arrivée. Jour 2  -  boucle montagne : départ 9h30, Chalki, Panagia Drosiani, Filoti, Apeiranthos pour un déjeuner tardif. Jour 3  -  plages : Agios Prokopios, Agia Anna, Plaka puis Mikri Vigla.",
          "Tag 1  -  Chora: Auto übernehmen, Kastro am Vormittag, Mittagessen in der Altstadt, Bad in Agios Georgios, Portara bei Sonnenuntergang. Fahren Sie am Anreisetag nicht. Tag 2  -  Bergrunde: Aufbruch 9:30 Uhr, Chalki, Panagia Drosiani, Filoti, Apeiranthos für ein spätes Mittagessen. Tag 3  -  Strände: Agios Prokopios, Agia Anna, Plaka und zum Schluss Mikri Vigla.",
        ),
      },
      {
        heading: ls(
          "Five days: add the north and the south",
          "Πέντε ημέρες: προσθέστε βορρά και νότο",
          "Cinque giorni: aggiungi nord e sud",
          "Cinq jours : ajoutez le nord et le sud",
          "Fünf Tage: Norden und Süden dazu",
        ),
        body: ls(
          "Keep days 1–3 and add these. Day 4  -  the north. This is the long one: 48 km up through Koronos to Apollonas, an hour each way on a road that is beautiful, paved, and single-lane in places. See the 10.7 m Kouros lying in his quarry, swim at Apollonas beach, eat fish at the harbour, and come back via the coastal road for a completely different view. Leave early and do not attempt it in the dark. Day 5  -  the south. Drive to Alyko, park at the signed area, and walk through the cedar forest to the painted abandoned hotel and the three small beaches below it. Continue to Pyrgaki for the quietest sunset on the island. Stop at the Temple of Demeter at Sangri on the way back  -  it is a ten-minute detour and one of the most perfect small buildings in Greece.",
          "Κρατήστε τις ημέρες 1–3 και προσθέστε: Ημέρα 4  -  βορράς: 48 χλμ. μέσω Κορώνου στον Απόλλωνα, μία ώρα ανά κατεύθυνση. Κούρος 10,7 μ., μπάνιο, ψάρι στο λιμάνι. Ξεκινήστε νωρίς. Ημέρα 5  -  νότος: Αλυκό, περπάτημα στο κεδρόδασος, Πυργάκι για το πιο ήσυχο ηλιοβασίλεμα, και στάση στον Ναό της Δήμητρας στο Σαγκρί.",
          "Mantieni i giorni 1–3 e aggiungi: Giorno 4  -  nord: 48 km via Koronos fino ad Apollonas, un'ora per senso. Kouros di 10,7 m, bagno, pesce al porto. Parti presto. Giorno 5  -  sud: Alyko, passeggiata nella foresta di cedri, Pyrgaki per il tramonto più tranquillo, e sosta al Tempio di Demetra a Sangri.",
          "Gardez les jours 1–3 et ajoutez : Jour 4  -  nord : 48 km via Koronos jusqu'à Apollonas, une heure par trajet. Kouros de 10,7 m, baignade, poisson au port. Partez tôt. Jour 5  -  sud : Alyko, marche dans la forêt de cèdres, Pyrgaki pour le coucher de soleil le plus calme, et arrêt au temple de Déméter à Sangri.",
          "Behalten Sie Tag 1–3 und ergänzen Sie: Tag 4  -  Norden: 48 km über Koronos nach Apollonas, eine Stunde pro Richtung. Kouros mit 10,7 m, Baden, Fisch am Hafen. Früh starten. Tag 5  -  Süden: Alyko, Wanderung durch den Zedernwald, Pyrgaki für den ruhigsten Sonnenuntergang und Halt am Demeter-Tempel in Sangri.",
        ),
      },
      {
        heading: ls(
          "Seven days: the version we would book",
          "Επτά ημέρες: η εκδοχή που θα διαλέγαμε",
          "Sette giorni: la versione che sceglieremmo",
          "Sept jours : la version que nous choisirions",
          "Sieben Tage: die Version, die wir buchen würden",
        ),
        body: ls(
          "Days 1–5 as above, then: Day 6  -  Mount Zas. Start from the Agia Marina trailhead above Filoti before 09:00, allow three hours return, take two litres of water per person and proper shoes. The summit at 1,004 m gives you the whole Cyclades on a clear morning  -  Paros, Ios, Santorini, sometimes Crete. Reward yourself in Filoti's plateia afterwards. Day 7  -  keep it free. Book nothing. This is the day the meltemi blows too hard for the beach you planned, or the day you go back to the taverna in Apeiranthos, or the day you take the boat to Koufonisia. Every itinerary that fills all seven days is a worse itinerary than one that fills six.",
          "Ημέρες 1–5 όπως παραπάνω, και: Ημέρα 6  -  Ζας: εκκίνηση από την Αγία Μαρίνα πριν τις 09:00, τρεις ώρες συνολικά, δύο λίτρα νερό και κατάλληλα παπούτσια. Από την κορυφή στα 1.004 μ. φαίνονται Πάρος, Ίος, Σαντορίνη. Ημέρα 7  -  αφήστε την ελεύθερη. Κάθε πρόγραμμα που γεμίζει και τις επτά ημέρες είναι χειρότερο από ένα που γεμίζει έξι.",
          "Giorni 1–5 come sopra, poi: Giorno 6  -  Monte Zas: partenza da Agia Marina prima delle 09:00, tre ore andata e ritorno, due litri d'acqua e scarpe adatte. Dalla vetta a 1.004 m si vedono Paros, Ios, Santorini. Giorno 7  -  lascialo libero. Ogni itinerario che riempie tutti e sette i giorni è peggiore di uno che ne riempie sei.",
          "Jours 1–5 comme ci-dessus, puis : Jour 6  -  mont Zas : départ d'Agia Marina avant 9h, trois heures aller-retour, deux litres d'eau et de bonnes chaussures. Du sommet à 1 004 m, on voit Paros, Ios, Santorin. Jour 7  -  gardez-le libre. Tout itinéraire qui remplit les sept jours est moins bon qu'un qui en remplit six.",
          "Tag 1–5 wie oben, dann: Tag 6  -  Mount Zas: Start ab Agia Marina vor 9:00 Uhr, drei Stunden hin und zurück, zwei Liter Wasser und feste Schuhe. Vom Gipfel auf 1.004 m sieht man Paros, Ios, Santorin. Tag 7  -  halten Sie ihn frei. Jede Route, die alle sieben Tage füllt, ist schlechter als eine, die sechs füllt.",
        ),
      },
      {
        heading: ls(
          "Three scheduling rules that save the trip",
          "Τρεις κανόνες προγραμματισμού που σώζουν το ταξίδι",
          "Tre regole di programmazione che salvano il viaggio",
          "Trois règles de planification qui sauvent le voyage",
          "Drei Planungsregeln, die die Reise retten",
        ),
        body: ls(
          "First, do the mountains in the morning and the beaches in the afternoon, never the reverse: the inland roads are cooler and emptier before noon, and the west-coast beaches get their best light after 16:00. Second, watch the wind, not the temperature. A 28°C day with 7 Beaufort of meltemi makes Plaka and Mikri Vigla unpleasant and Moutsouna on the sheltered east coast perfect  -  check a wind forecast each morning and flip your plan accordingly. Third, never schedule a long drive on your departure day. Ferries from Naxos are punctual and the port area gets genuinely congested in August; be back in Chora two hours before sailing, which usually means no drive further than Plaka that morning.",
          "Πρώτον, βουνό το πρωί και παραλία το απόγευμα, ποτέ το αντίστροφο. Δεύτερον, παρακολουθείτε τον άνεμο, όχι τη θερμοκρασία: με 7 μποφόρ μελτέμι η Πλάκα και η Μικρή Βίγλα είναι δυσάρεστες ενώ η Μουτσούνα στα ανατολικά είναι τέλεια. Τρίτον, ποτέ μεγάλη διαδρομή την ημέρα αναχώρησης  -  επιστρέψτε στη Χώρα δύο ώρες πριν τον απόπλου.",
          "Primo, montagna al mattino e spiaggia al pomeriggio, mai il contrario. Secondo, guarda il vento, non la temperatura: con 7 Beaufort di meltemi Plaka e Mikri Vigla sono sgradevoli mentre Moutsouna a est è perfetta. Terzo, mai un lungo viaggio il giorno della partenza  -  torna a Chora due ore prima dell'imbarco.",
          "Premièrement, la montagne le matin et la plage l'après-midi, jamais l'inverse. Deuxièmement, surveillez le vent, pas la température : avec 7 Beaufort de meltemi, Plaka et Mikri Vigla sont désagréables alors que Moutsouna à l'est est parfaite. Troisièmement, jamais de long trajet le jour du départ  -  soyez à Chora deux heures avant l'embarquement.",
          "Erstens: Berge am Morgen, Strand am Nachmittag, nie umgekehrt. Zweitens: Achten Sie auf den Wind, nicht die Temperatur  -  bei 7 Beaufort Meltemi sind Plaka und Mikri Vigla unangenehm, während Moutsouna im Osten perfekt ist. Drittens: nie eine lange Fahrt am Abreisetag  -  seien Sie zwei Stunden vor Abfahrt zurück in Chora.",
        ),
      },
    ],
    faq: [
      {
        q: ls(
          "Is 3 days enough for Naxos?",
          "Είναι αρκετές οι 3 ημέρες για τη Νάξο;",
          "Bastano 3 giorni a Naxos?",
          "Trois jours suffisent-ils à Naxos ?",
          "Reichen 3 Tage für Naxos?",
        ),
        a: ls(
          "Three days is enough to see Chora, the main beaches and one mountain loop  -  a good trip, but you will leave knowing you missed the north and the south. If three days is all you have, rent a car for all of them; without one, three days becomes two beaches and a town.",
          "Τρεις ημέρες αρκούν για τη Χώρα, τις κύριες παραλίες και μία ορεινή διαδρομή  -  αλλά θα φύγετε ξέροντας ότι χάσατε τον βορρά και τον νότο. Αν έχετε μόνο τρεις ημέρες, νοικιάστε αυτοκίνητο και για τις τρεις.",
          "Tre giorni bastano per Chora, le spiagge principali e un giro in montagna  -  ma partirai sapendo di aver perso nord e sud. Se hai solo tre giorni, noleggia l'auto per tutti e tre.",
          "Trois jours suffisent pour Chora, les plages principales et une boucle en montagne  -  mais vous partirez en sachant avoir manqué le nord et le sud. Si vous n'avez que trois jours, louez une voiture pour les trois.",
          "Drei Tage reichen für Chora, die Hauptstrände und eine Bergrunde  -  Sie werden aber wissen, dass Sie Norden und Süden verpasst haben. Bei nur drei Tagen: für alle drei ein Auto mieten.",
        ),
      },
      {
        q: ls(
          "Can you do Naxos in a day trip?",
          "Μπορείτε να δείτε τη Νάξο σε μία ημέρα;",
          "Si può visitare Naxos in giornata?",
          "Peut-on visiter Naxos en une journée ?",
          "Kann man Naxos an einem Tag sehen?",
        ),
        a: ls(
          "You can visit, but you cannot see it. A day trip from Paros or Mykonos gives you Chora, the Kastro, the Portara and one beach  -  a pleasant six hours. The mountain villages and the Kouroi need a full day of their own. Naxos rewards staying much more than most Cyclades islands.",
          "Μπορείτε να επισκεφθείτε, αλλά όχι να τη δείτε. Μια ημερήσια εκδρομή από Πάρο ή Μύκονο δίνει Χώρα, Κάστρο, Πορτάρα και μία παραλία. Τα ορεινά χωριά και οι Κούροι θέλουν ολόκληρη ημέρα.",
          "Puoi visitarla, ma non vederla. Una gita da Paros o Mykonos dà Chora, il Kastro, la Portara e una spiaggia. I villaggi di montagna e i kouroi richiedono un giorno intero.",
          "Vous pouvez la visiter, mais pas la voir. Une excursion depuis Paros ou Mykonos donne Chora, le Kastro, la Portara et une plage. Les villages de montagne et les kouroï nécessitent une journée entière.",
          "Besuchen ja, sehen nein. Ein Tagesausflug von Paros oder Mykonos bringt Chora, das Kastro, die Portara und einen Strand. Bergdörfer und Kouroi brauchen einen ganzen Tag.",
        ),
      },
      {
        q: ls(
          "How long does it take to drive around Naxos?",
          "Πόση ώρα χρειάζεται ο γύρος της Νάξου;",
          "Quanto ci vuole a girare Naxos in auto?",
          "Combien de temps pour faire le tour de Naxos ?",
          "Wie lange dauert eine Rundfahrt um Naxos?",
        ),
        a: ls(
          "A full circuit  -  Chora, the west coast, the south, up through Filoti and Apeiranthos to Apollonas and back along the north  -  is about 140 km and takes six to seven hours of driving without stops. Nobody should do it in one day. Split it across two: the mountain loop one day, the coast the next.",
          "Ο πλήρης γύρος  -  Χώρα, δυτική ακτή, νότος, Φιλώτι, Απείρανθος, Απόλλωνας και επιστροφή  -  είναι περίπου 140 χλμ. και έξι με επτά ώρες οδήγησης χωρίς στάσεις. Χωρίστε τον σε δύο ημέρες.",
          "Il giro completo  -  Chora, costa ovest, sud, Filoti, Apeiranthos, Apollonas e ritorno  -  è di circa 140 km e sei-sette ore di guida senza soste. Dividilo in due giorni.",
          "Le tour complet  -  Chora, côte ouest, sud, Filoti, Apeiranthos, Apollonas et retour  -  fait environ 140 km et six à sept heures de conduite sans arrêt. Répartissez-le sur deux jours.",
          "Die komplette Runde  -  Chora, Westküste, Süden, Filoti, Apeiranthos, Apollonas und zurück  -  sind etwa 140 km und sechs bis sieben Stunden reine Fahrzeit. Verteilen Sie sie auf zwei Tage.",
        ),
      },
      {
        q: ls(
          "What is the best day trip from Naxos?",
          "Ποια είναι η καλύτερη ημερήσια εκδρομή από τη Νάξο;",
          "Qual è la migliore gita in giornata da Naxos?",
          "Quelle est la meilleure excursion depuis Naxos ?",
          "Was ist der beste Tagesausflug ab Naxos?",
        ),
        a: ls(
          "Koufonisia, in the Small Cyclades. Day boats leave Chora in the morning and return late afternoon, and the island's turquoise water and sea caves are the closest thing to a tropical beach in Greece. Iraklia and Schinoussa are quieter alternatives on the same route. Paros is 45 minutes by ferry if you want a second big island.",
          "Τα Κουφονήσια. Καΐκια φεύγουν από τη Χώρα το πρωί και επιστρέφουν αργά το απόγευμα. Η Ηρακλειά και η Σχοινούσα είναι πιο ήσυχες εναλλακτικές. Η Πάρος απέχει 45 λεπτά με πλοίο.",
          "Koufonisia, nelle Piccole Cicladi. Le barche partono da Chora al mattino e rientrano nel tardo pomeriggio. Iraklia e Schinoussa sono alternative più tranquille. Paros dista 45 minuti di traghetto.",
          "Koufonissia, dans les Petites Cyclades. Les bateaux partent de Chora le matin et rentrent en fin d'après-midi. Iraklia et Schinoussa sont des alternatives plus calmes. Paros est à 45 minutes en ferry.",
          "Koufonisia in den Kleinen Kykladen. Boote fahren morgens ab Chora und kehren am späten Nachmittag zurück. Iraklia und Schinoussa sind ruhigere Alternativen. Paros liegt 45 Fährminuten entfernt.",
        ),
      },
      {
        q: ls(
          "Should I rent a car for the whole stay or just a few days?",
          "Να νοικιάσω αυτοκίνητο για όλη τη διαμονή ή για λίγες ημέρες;",
          "Meglio noleggiare l'auto per tutto il soggiorno o solo per pochi giorni?",
          "Faut-il louer une voiture pour tout le séjour ou quelques jours ?",
          "Auto für den ganzen Aufenthalt oder nur ein paar Tage mieten?",
        ),
        a: ls(
          "For four nights or more, take it for the whole stay  -  the daily rate falls with duration and you lose more in taxi fares and lost mornings than you save. For two or three nights, rent for the middle days and use the free delivery to the port on arrival and departure. We are happy to arrange either.",
          "Για τέσσερις νύχτες και άνω, πάρτε το για όλη τη διαμονή  -  η ημερήσια τιμή πέφτει με τη διάρκεια. Για δύο-τρεις νύχτες, νοικιάστε για τις ενδιάμεσες ημέρες και χρησιμοποιήστε τη δωρεάν παράδοση στο λιμάνι.",
          "Da quattro notti in su, prendila per tutto il soggiorno  -  la tariffa giornaliera scende con la durata. Per due o tre notti, noleggia per i giorni centrali e usa la consegna gratuita al porto.",
          "À partir de quatre nuits, prenez-la pour tout le séjour  -  le tarif journalier baisse avec la durée. Pour deux ou trois nuits, louez pour les jours du milieu et profitez de la livraison gratuite au port.",
          "Ab vier Nächten für den ganzen Aufenthalt  -  der Tagessatz sinkt mit der Dauer. Bei zwei oder drei Nächten für die mittleren Tage mieten und die kostenlose Lieferung am Hafen nutzen.",
        ),
      },
    ],
  },
  {
    slug: "naxos-vs-paros",
    cluster: "plan",
    title: ls(
      "Naxos vs Paros 2026: which island should you actually choose?",
      "Νάξος ή Πάρος 2026: ποιο νησί να επιλέξετε;",
      "Naxos o Paros 2026: quale isola scegliere davvero?",
      "Naxos ou Paros 2026 : quelle île choisir vraiment ?",
      "Naxos oder Paros 2026: Welche Insel sollten Sie wählen?",
    ),
    excerpt: ls(
      "They are 45 minutes apart and constantly confused. A head-to-head on beaches, food, nightlife, cost, families and getting around  -  written from the Naxos side, and honest about where Paros wins.",
      "Απέχουν 45 λεπτά και συγχέονται διαρκώς. Σύγκριση σε παραλίες, φαγητό, νυχτερινή ζωή, κόστος και οικογένειες  -  με ειλικρίνεια για το πού κερδίζει η Πάρος.",
      "Distano 45 minuti e vengono continuamente confuse. Un confronto su spiagge, cibo, vita notturna, costi e famiglie  -  onesto su dove vince Paros.",
      "Elles sont à 45 minutes l'une de l'autre et souvent confondues. Un face-à-face sur les plages, la cuisine, la vie nocturne, le budget et les familles  -  honnête sur les points où Paros gagne.",
      "45 Minuten voneinander entfernt und ständig verwechselt. Ein Direktvergleich zu Stränden, Essen, Nachtleben, Kosten und Familien  -  ehrlich dort, wo Paros gewinnt.",
    ),
    answer: ls(
      "Choose Naxos for beaches, mountains, food and value  -  it is bigger, greener, cheaper and has the better sand. Choose Paros for nightlife, boutique hotels, easier ferry connections and prettier villages. Naxos suits families and week-long stays; Paros suits couples, groups and island-hopping. They are 45 minutes apart, so doing both is the real answer.",
      "Επιλέξτε τη Νάξο για παραλίες, βουνά, φαγητό και σχέση αξίας  -  είναι μεγαλύτερη, πιο πράσινη και πιο οικονομική. Επιλέξτε την Πάρο για νυχτερινή ζωή, boutique ξενοδοχεία, καλύτερες ακτοπλοϊκές συνδέσεις και ομορφότερα χωριά. Απέχουν 45 λεπτά, οπότε η πραγματική απάντηση είναι και τα δύο.",
      "Scegli Naxos per spiagge, montagne, cibo e rapporto qualità-prezzo  -  è più grande, più verde e più economica. Scegli Paros per vita notturna, hotel boutique, collegamenti migliori e villaggi più belli. Distano 45 minuti: la risposta vera è entrambe.",
      "Choisissez Naxos pour les plages, les montagnes, la cuisine et le rapport qualité-prix  -  plus grande, plus verte, moins chère. Choisissez Paros pour la vie nocturne, les hôtels de charme, les liaisons et les plus jolis villages. À 45 minutes l'une de l'autre : la vraie réponse est les deux.",
      "Wählen Sie Naxos für Strände, Berge, Essen und Preis-Leistung  -  größer, grüner, günstiger. Wählen Sie Paros für Nachtleben, Boutiquehotels, bessere Verbindungen und hübschere Dörfer. 45 Minuten auseinander: Die ehrliche Antwort ist beides.",
    ),
    hero: "/images/naxos/gallery/naxos-aerial.jpg",
    publishedAt: "2026-08-22",
    updatedAt: "2026-08-22",
    readingTime: 10,
    keywords: [
      "naxos vs paros",
      "naxos or paros",
      "paros vs naxos",
      "which is better naxos or paros",
      "naxos paros comparison",
    ],
    related: ["naxos-travel-guide", "best-beaches-in-naxos", "how-to-get-to-naxos", "naxos-itinerary"],
    vehiclePicks: ["hyundai-i10", "peugeot-208", "citroen-berlingo-7"],
    locationPicks: ["port-pickup", "naxos-town", "plaka"],
    table: {
      caption: ls(
        "Naxos vs Paros at a glance",
        "Νάξος και Πάρος με μια ματιά",
        "Naxos e Paros a colpo d'occhio",
        "Naxos et Paros en un coup d'œil",
        "Naxos und Paros im Überblick",
      ),
      columns: [
        ls("", "", "", "", ""),
        ls("Naxos"),
        ls("Paros"),
      ],
      rows: [
        [
          ls("Size", "Έκταση", "Superficie", "Superficie", "Fläche"),
          ls("430 km²"),
          ls("196 km²"),
        ],
        [
          ls("Best for", "Ιδανικό για", "Ideale per", "Idéal pour", "Ideal für"),
          ls("Families, beaches, hiking, food", "Οικογένειες, παραλίες, πεζοπορία, φαγητό", "Famiglie, spiagge, trekking, cibo", "Familles, plages, randonnée, cuisine", "Familien, Strände, Wandern, Essen"),
          ls("Couples, nightlife, island-hopping", "Ζευγάρια, νυχτερινή ζωή, island hopping", "Coppie, vita notturna, island hopping", "Couples, vie nocturne, cabotage", "Paare, Nachtleben, Inselhüpfen"),
        ],
        [
          ls("Beaches", "Παραλίες", "Spiagge", "Plages", "Strände"),
          ls("Longer, sandier, shallower", "Μεγαλύτερες, πιο αμμώδεις, πιο ρηχές", "Più lunghe, sabbiose, basse", "Plus longues, sableuses, peu profondes", "Länger, sandiger, flacher"),
          ls("Prettier coves, more organised", "Ομορφότεροι όρμοι, πιο οργανωμένες", "Baie più belle, più attrezzate", "Criques plus jolies, plus aménagées", "Hübschere Buchten, besser ausgestattet"),
        ],
        [
          ls("Nightlife", "Νυχτερινή ζωή", "Vita notturna", "Vie nocturne", "Nachtleben"),
          ls("Quiet, taverna-led", "Ήσυχη, με ταβέρνες", "Tranquilla, da taverna", "Calme, autour des tavernes", "Ruhig, tavernenbasiert"),
          ls("Naoussa is a genuine scene", "Η Νάουσα έχει πραγματική σκηνή", "Naoussa è una vera scena", "Naoussa est une vraie scène", "Naoussa ist eine echte Szene"),
        ],
        [
          ls("Cost", "Κόστος", "Costi", "Coût", "Kosten"),
          ls("Lower", "Χαμηλότερο", "Più basso", "Plus bas", "Niedriger"),
          ls("15–25% higher", "15–25% υψηλότερο", "15–25% più alto", "15–25 % plus élevé", "15–25 % höher"),
        ],
        [
          ls("Ferry links", "Ακτοπλοϊκές συνδέσεις", "Collegamenti", "Liaisons", "Fährverbindungen"),
          ls("Very good", "Πολύ καλές", "Molto buoni", "Très bonnes", "Sehr gut"),
          ls("The Cyclades hub", "Ο κόμβος των Κυκλάδων", "Il nodo delle Cicladi", "Le hub des Cyclades", "Das Drehkreuz der Kykladen"),
        ],
        [
          ls("Need a car?", "Χρειάζεται αυτοκίνητο;", "Serve l'auto?", "Voiture nécessaire ?", "Auto nötig?"),
          ls("Yes  -  the island is big", "Ναι  -  το νησί είναι μεγάλο", "Sì  -  l'isola è grande", "Oui  -  l'île est grande", "Ja  -  die Insel ist groß"),
          ls("Helpful, not essential", "Χρήσιμο, όχι απαραίτητο", "Utile, non essenziale", "Utile, pas indispensable", "Hilfreich, nicht zwingend"),
        ],
      ],
    },
    sections: [
      {
        heading: ls(
          "Beaches: Naxos, and it is not particularly close",
          "Παραλίες: η Νάξος, με σαφή διαφορά",
          "Spiagge: Naxos, e non di poco",
          "Plages : Naxos, et de loin",
          "Strände: Naxos, und zwar deutlich",
        ),
        body: ls(
          "Naxos has the longest continuous stretch of sand in the Cyclades. Agios Prokopios, Agia Anna, Plaka, Kastraki and Alyko run for roughly 12 km down the west coast, mostly fine pale sand with a gentle shelf you can walk out fifty metres into and still stand up. Paros has beautiful beaches  -  Kolymbithres with its wind-sculpted granite, Santa Maria, Golden Beach for windsurfers  -  but they are coves rather than expanses, they organise up more heavily with sunbeds, and the crowds concentrate because there is less coastline to spread across. If the beach is the reason you are going to Greece, this comparison ends here.",
          "Η Νάξος έχει τη μεγαλύτερη συνεχή αμμουδιά των Κυκλάδων: Άγιος Προκόπιος, Αγία Άννα, Πλάκα, Καστράκι και Αλυκό εκτείνονται περίπου 12 χλμ. με ψιλή άμμο και ήπια κλίση. Η Πάρος έχει όμορφες παραλίες  -  Κολυμπήθρες, Σάντα Μαρία, Χρυσή Ακτή  -  αλλά είναι όρμοι, πιο οργανωμένοι και με μεγαλύτερη συγκέντρωση κόσμου.",
          "Naxos ha la spiaggia continua più lunga delle Cicladi: Agios Prokopios, Agia Anna, Plaka, Kastraki e Alyko si estendono per circa 12 km con sabbia fine e fondale dolce. Paros ha belle spiagge  -  Kolymbithres, Santa Maria, Golden Beach  -  ma sono baie, più attrezzate e più affollate.",
          "Naxos possède la plus longue plage continue des Cyclades : Agios Prokopios, Agia Anna, Plaka, Kastraki et Alyko s'étendent sur environ 12 km de sable fin en pente douce. Paros a de belles plages  -  Kolymbithres, Santa Maria, Golden Beach  -  mais ce sont des criques, plus aménagées et plus fréquentées.",
          "Naxos hat den längsten zusammenhängenden Sandstrand der Kykladen: Agios Prokopios, Agia Anna, Plaka, Kastraki und Alyko erstrecken sich über rund 12 km mit feinem Sand und flachem Einstieg. Paros hat schöne Strände  -  Kolymbithres, Santa Maria, Golden Beach  -  aber es sind Buchten, stärker organisiert und voller.",
        ),
      },
      {
        heading: ls(
          "Villages and atmosphere: Paros wins on charm, Naxos on depth",
          "Χωριά και ατμόσφαιρα: η Πάρος στη γοητεία, η Νάξος στο βάθος",
          "Villaggi e atmosfera: Paros vince in fascino, Naxos in profondità",
          "Villages et ambiance : Paros gagne en charme, Naxos en profondeur",
          "Dörfer und Atmosphäre: Paros gewinnt beim Charme, Naxos bei der Tiefe",
        ),
        body: ls(
          "Naoussa is the prettiest village in either island  -  a small Venetian fishing harbour of blue boats and whitewash that becomes a serious bar scene after dark, and Lefkes inland is lovely. Parikia is a working port town that most visitors underrate. But Naxos has more of it: Chora's three-tier Kastro is a genuine medieval quarter with people still living in the towers, and Chalki, Filoti, Apeiranthos, Koronos and Apollonas are five entirely distinct mountain villages rather than variations on one. Paros feels curated; Naxos feels inhabited. Which you prefer is genuinely a matter of taste rather than quality.",
          "Η Νάουσα είναι το ομορφότερο χωριό και των δύο νησιών  -  βενετσιάνικο ψαρολίμανο που μετά το σκοτάδι γίνεται σοβαρή σκηνή μπαρ  -  ενώ οι Λεύκες είναι υπέροχες. Η Νάξος όμως έχει περισσότερα: το τριώροφο Κάστρο της Χώρας και πέντε εντελώς διαφορετικά ορεινά χωριά. Η Πάρος μοιάζει επιμελημένη· η Νάξος μοιάζει κατοικημένη.",
          "Naoussa è il villaggio più bello delle due isole  -  un porticciolo veneziano che di sera diventa una vera scena di bar  -  e Lefkes è deliziosa. Ma Naxos ne ha di più: il Kastro di Chora su tre livelli e cinque villaggi di montagna del tutto distinti. Paros sembra curata; Naxos sembra abitata.",
          "Naoussa est le plus joli village des deux îles  -  un petit port vénitien qui devient une vraie scène de bars le soir  -  et Lefkes est charmante. Mais Naxos en a davantage : le Kastro de Chora sur trois niveaux et cinq villages de montagne totalement distincts. Paros paraît soignée ; Naxos paraît habitée.",
          "Naoussa ist das hübscheste Dorf beider Inseln  -  ein venezianischer Fischerhafen, der abends zur echten Barszene wird  -  und Lefkes ist reizend. Aber Naxos hat mehr davon: das dreistufige Kastro von Chora und fünf völlig unterschiedliche Bergdörfer. Paros wirkt kuratiert, Naxos bewohnt.",
        ),
      },
      {
        heading: ls(
          "Nightlife, hotels and getting there: Paros",
          "Νυχτερινή ζωή, ξενοδοχεία και πρόσβαση: η Πάρος",
          "Vita notturna, hotel e come arrivare: Paros",
          "Vie nocturne, hôtels et accès : Paros",
          "Nachtleben, Hotels und Anreise: Paros",
        ),
        body: ls(
          "If you want to go out properly, Paros is the answer: Naoussa's harbour bars run until 04:00 and the standard is high. Naxos nightlife is a long dinner and a drink on the waterfront, which many people prefer but is a different proposition entirely. Paros also has the stronger boutique and design-hotel market, and it is the ferry hub of the Cyclades  -  almost every route passes through Parikia, which makes island-hopping simpler and gives you more flight options via nearby Mykonos. Naxos has good connections too, but Paros has more of them, and if your trip is four islands in ten days that matters.",
          "Αν θέλετε πραγματική νυχτερινή έξοδο, η απάντηση είναι η Πάρος: τα μπαρ της Νάουσας λειτουργούν έως τις 04:00. Η νυχτερινή ζωή στη Νάξο είναι ένα μακρύ δείπνο και ένα ποτό στην προκυμαία. Η Πάρος έχει επίσης ισχυρότερη αγορά boutique ξενοδοχείων και είναι ο ακτοπλοϊκός κόμβος των Κυκλάδων.",
          "Se vuoi uscire davvero, la risposta è Paros: i bar del porto di Naoussa vanno fino alle 04:00. La vita notturna di Naxos è una lunga cena e un drink sul porto. Paros ha anche più hotel boutique ed è il nodo dei traghetti delle Cicladi.",
          "Si vous voulez vraiment sortir, la réponse est Paros : les bars du port de Naoussa vont jusqu'à 4h. La vie nocturne de Naxos, c'est un long dîner et un verre sur le port. Paros a aussi plus d'hôtels de charme et c'est le hub des ferries des Cyclades.",
          "Wenn Sie richtig ausgehen wollen, ist Paros die Antwort: Die Hafenbars von Naoussa laufen bis 4:00 Uhr. Das Nachtleben auf Naxos ist ein langes Abendessen und ein Drink am Hafen. Paros hat außerdem mehr Boutiquehotels und ist das Fährdrehkreuz der Kykladen.",
        ),
      },
      {
        heading: ls(
          "Cost and value: Naxos, by a clear margin",
          "Κόστος και αξία: η Νάξος, με σαφή διαφορά",
          "Costi e valore: Naxos, con margine chiaro",
          "Coût et rapport qualité-prix : Naxos, nettement",
          "Kosten und Wert: Naxos, mit klarem Vorsprung",
        ),
        body: ls(
          "Expect to pay roughly 15–25% more on Paros for a comparable room, and noticeably more for dinner in Naoussa than for the same meal in Chora. The reason is agriculture again: Naxos grows and raises much of what its tavernas serve, so the supply chain is shorter and the prices reflect it. Car hire is similar on both islands, though Naxos needs one and Paros does not, so budget accordingly  -  on Paros you could realistically manage with buses and one rental day, while on Naxos a car is part of the trip.",
          "Υπολογίστε περίπου 15–25% υψηλότερες τιμές στην Πάρο για αντίστοιχο δωμάτιο και αισθητά ακριβότερο δείπνο στη Νάουσα. Ο λόγος είναι πάλι η γεωργία: η Νάξος παράγει μεγάλο μέρος όσων σερβίρουν οι ταβέρνες της. Η ενοικίαση αυτοκινήτου κοστίζει παρόμοια, αλλά η Νάξος το χρειάζεται και η Πάρος όχι.",
          "Aspettati circa il 15–25% in più a Paros per una camera equivalente e cene più care a Naoussa. Il motivo è di nuovo l'agricoltura: Naxos produce gran parte di ciò che serve nelle taverne. Il noleggio auto costa simile, ma a Naxos serve e a Paros no.",
          "Comptez environ 15 à 25 % de plus à Paros pour une chambre équivalente et des dîners plus chers à Naoussa. La raison est encore l'agriculture : Naxos produit une grande part de ce que servent ses tavernes. La location coûte pareil, mais Naxos en a besoin et Paros non.",
          "Rechnen Sie auf Paros mit etwa 15–25 % höheren Zimmerpreisen und teureren Abendessen in Naoussa. Der Grund ist wieder die Landwirtschaft: Naxos erzeugt vieles selbst, was seine Tavernen servieren. Automieten kosten ähnlich, aber Naxos braucht eines, Paros nicht.",
        ),
      },
      {
        heading: ls(
          "The answer most people should take",
          "Η απάντηση που ταιριάζει στους περισσότερους",
          "La risposta giusta per la maggior parte",
          "La réponse qui convient au plus grand nombre",
          "Die Antwort für die meisten",
        ),
        body: ls(
          "Do both. The ferry is 45 minutes and runs several times a day in season, so a ten-day trip splits perfectly: four nights on Paros for the villages and the nightlife, five on Naxos for the beaches and the mountains, one night wherever your flight home is easier. If you must pick one and you are travelling with children, or you want a week that feels like a holiday rather than a tour, take Naxos. If you are two people in your twenties or thirties looking for a lively base with good bars and easy hops to Mykonos and Ios, take Paros.",
          "Κάντε και τα δύο. Το πλοίο κάνει 45 λεπτά και εκτελεί πολλά δρομολόγια ημερησίως: τέσσερις νύχτες στην Πάρο για τα χωριά και τη νυχτερινή ζωή, πέντε στη Νάξο για παραλίες και βουνά. Αν πρέπει να επιλέξετε ένα και ταξιδεύετε με παιδιά, επιλέξτε τη Νάξο.",
          "Fai entrambe. Il traghetto impiega 45 minuti e parte più volte al giorno: quattro notti a Paros per i villaggi e la vita notturna, cinque a Naxos per spiagge e montagne. Se devi sceglierne una e viaggi con bambini, scegli Naxos.",
          "Faites les deux. Le ferry met 45 minutes et circule plusieurs fois par jour : quatre nuits à Paros pour les villages et les sorties, cinq à Naxos pour les plages et les montagnes. Si vous devez choisir et voyagez avec des enfants, prenez Naxos.",
          "Machen Sie beides. Die Fähre braucht 45 Minuten und fährt mehrmals täglich: vier Nächte Paros für Dörfer und Nachtleben, fünf Nächte Naxos für Strände und Berge. Wenn Sie sich entscheiden müssen und mit Kindern reisen: Naxos.",
        ),
      },
    ],
    faq: [
      {
        q: ls(
          "Is Naxos or Paros better for families?",
          "Νάξος ή Πάρος για οικογένειες;",
          "Naxos o Paros per le famiglie?",
          "Naxos ou Paros pour les familles ?",
          "Naxos oder Paros für Familien?",
        ),
        a: ls(
          "Naxos, clearly. The west-coast beaches shelve so gently that small children can walk out a long way safely, Chora's old town is car-free, food is cheaper and simpler, and the island is big enough that you always have somewhere new to go on day five.",
          "Η Νάξος, ξεκάθαρα. Οι δυτικές παραλίες έχουν πολύ ήπια κλίση, η παλιά πόλη είναι πεζόδρομος, το φαγητό είναι φθηνότερο και το νησί αρκετά μεγάλο ώστε να υπάρχει πάντα κάτι νέο.",
          "Naxos, chiaramente. Le spiagge occidentali digradano dolcemente, il centro storico è pedonale, il cibo costa meno e l'isola è abbastanza grande da avere sempre una novità.",
          "Naxos, clairement. Les plages de l'ouest descendent en pente douce, la vieille ville est piétonne, la nourriture coûte moins cher et l'île est assez grande pour toujours offrir du nouveau.",
          "Klar Naxos. Die Weststrände fallen sehr flach ab, die Altstadt ist autofrei, das Essen ist günstiger und die Insel groß genug für immer neue Ziele.",
        ),
      },
      {
        q: ls(
          "How far is Naxos from Paros?",
          "Πόσο απέχει η Νάξος από την Πάρο;",
          "Quanto dista Naxos da Paros?",
          "À quelle distance est Naxos de Paros ?",
          "Wie weit ist Naxos von Paros entfernt?",
        ),
        a: ls(
          "About 12 nautical miles. Ferries run several times a day in season and take 30–45 minutes depending on the vessel, with fares typically €10–20. It is the easiest island hop in the Cyclades and makes combining the two straightforward.",
          "Περίπου 12 ναυτικά μίλια. Τα πλοία εκτελούν πολλά δρομολόγια ημερησίως και κάνουν 30–45 λεπτά, με εισιτήρια συνήθως €10–20.",
          "Circa 12 miglia nautiche. I traghetti partono più volte al giorno e impiegano 30–45 minuti, con biglietti tipicamente €10–20.",
          "Environ 12 milles nautiques. Les ferries circulent plusieurs fois par jour et mettent 30 à 45 minutes, pour €10–20 environ.",
          "Etwa 12 Seemeilen. Fähren fahren mehrmals täglich und brauchen 30–45 Minuten, Tickets meist €10–20.",
        ),
      },
      {
        q: ls(
          "Which island is cheaper, Naxos or Paros?",
          "Ποιο νησί είναι φθηνότερο, η Νάξος ή η Πάρος;",
          "Quale isola costa meno, Naxos o Paros?",
          "Quelle île est la moins chère, Naxos ou Paros ?",
          "Welche Insel ist günstiger, Naxos oder Paros?",
        ),
        a: ls(
          "Naxos, by roughly 15–25% on accommodation and noticeably on food. Naxos produces much of its own food, has a larger year-round population and less concentrated demand, all of which keeps prices closer to mainland levels.",
          "Η Νάξος, κατά περίπου 15–25% στη διαμονή και αισθητά στο φαγητό. Η Νάξος παράγει μεγάλο μέρος της τροφής της και έχει μεγαλύτερο μόνιμο πληθυσμό.",
          "Naxos, circa il 15–25% in meno sull'alloggio e sensibilmente sul cibo. Naxos produce gran parte del proprio cibo e ha più residenti stabili.",
          "Naxos, environ 15 à 25 % de moins sur l'hébergement et nettement moins sur la nourriture. Naxos produit une grande part de son alimentation et compte plus d'habitants à l'année.",
          "Naxos, rund 15–25 % günstiger bei Unterkünften und deutlich beim Essen. Naxos erzeugt vieles selbst und hat mehr Ganzjahresbewohner.",
        ),
      },
      {
        q: ls(
          "Can you visit Naxos and Paros in one trip?",
          "Μπορείτε να επισκεφθείτε Νάξο και Πάρο στο ίδιο ταξίδι;",
          "Si possono visitare Naxos e Paros in un solo viaggio?",
          "Peut-on visiter Naxos et Paros en un seul voyage ?",
          "Kann man Naxos und Paros in einer Reise verbinden?",
        ),
        a: ls(
          "Easily, and most people should. A week splits well as three nights on one and four on the other; ten days as four and five with a night near your departure airport. Book the ferry a few days ahead in August  -  the fast boats fill up.",
          "Εύκολα, και οι περισσότεροι θα έπρεπε. Μια εβδομάδα χωρίζεται σε τρεις και τέσσερις νύχτες. Κλείστε το πλοίο λίγες ημέρες νωρίτερα τον Αύγουστο.",
          "Facilmente, ed è consigliabile. Una settimana si divide in tre e quattro notti. Prenota il traghetto con qualche giorno di anticipo ad agosto.",
          "Facilement, et c'est même conseillé. Une semaine se répartit en trois et quatre nuits. Réservez le ferry quelques jours à l'avance en août.",
          "Problemlos, und die meisten sollten es tun. Eine Woche teilt sich gut in drei und vier Nächte. Buchen Sie die Fähre im August einige Tage im Voraus.",
        ),
      },
      {
        q: ls(
          "Do you need a car on Paros as well as Naxos?",
          "Χρειάζεστε αυτοκίνητο και στην Πάρο;",
          "Serve l'auto anche a Paros?",
          "Faut-il une voiture à Paros aussi ?",
          "Braucht man auch auf Paros ein Auto?",
        ),
        a: ls(
          "On Naxos, yes  -  the island is more than twice the size and half of what is worth seeing has no bus. On Paros a car is useful but optional: the bus network between Parikia, Naoussa and the main beaches is genuinely good and the distances are short.",
          "Στη Νάξο ναι  -  το νησί είναι περισσότερο από διπλάσιο και τα μισά αξιοθέατα δεν εξυπηρετούνται. Στην Πάρο το αυτοκίνητο είναι χρήσιμο αλλά προαιρετικό: το δίκτυο λεωφορείων είναι πολύ καλό.",
          "A Naxos sì  -  l'isola è più del doppio e metà di ciò che vale la pena vedere non ha autobus. A Paros l'auto è utile ma opzionale: la rete di autobus è davvero buona.",
          "À Naxos oui  -  l'île fait plus du double et la moitié des sites n'a pas de bus. À Paros, la voiture est utile mais facultative : le réseau de bus est vraiment bon.",
          "Auf Naxos ja  -  die Insel ist mehr als doppelt so groß und die Hälfte der Sehenswürdigkeiten hat keinen Bus. Auf Paros ist ein Auto nützlich, aber optional: Das Busnetz ist wirklich gut.",
        ),
      },
    ],
  },
];
