import type { Locale } from "@/lib/site";

const copy = {
  en: {
    intro: "Your island. Your own way.",
    headline: "A little further.",
    accent: "A lot more Naxos.",
    description:
      "Salt in the air. Villages in the hills. A beach you almost missed. Find your rental car in Naxos and make room for the unexpected.",
    explore: "Find your car",
    arrival: "Where does your trip begin?",
    arrivalNote: "Choose your arrival point. We’ll help with the rest.",
    airport: "Naxos airport",
    port: "Naxos port",
    stay: "Your accommodation",
    pickup: "Pickup details",
    fleet: "Good cars. Great days.",
    fleetIntro:
      "Small enough for the island. Comfortable enough for the long way home. Compare our cars and check availability for your dates.",
    all: "All cars",
    automatic: "Automatic cars",
    family: "Family & 7-seater",
    suv: "SUV & 4×4",
    automaticDesc: "An easier drive, from coast to village.",
    familyDesc: "More room for your people and their bags.",
    suvDesc: "Space and comfort for island journeys.",
    island: "The island is the itinerary.",
    islandText:
      "Follow the coast. Stop for a swim. Take the turn towards the villages. Our Naxos guides help you choose the next stop.",
    coast: "A day by the sea",
    villages: "Take the scenic way",
    sunset: "Stay for the sunset",
    journal: "Before you take the wheel.",
    people: "An island business. A personal welcome.",
    peopleText:
      "Meet Marios and Ria, the people behind Fast Motor Rental Naxos. A direct conversation, practical island advice and a car for the trip you have in mind.",
    final: "See where the road takes you.",
    finalText: "Your dates. Your car. Your next Naxos story.",
    available: "Check availability",
    cars: "Cars in our fleet",
    since: "Family-run since",
    details: "Explore the car",
    terms: "Rental terms",
    reviews: "Guest reviews",
    legal: "Legal & information",
    seasonal:
      "Seasonal guide price. Final quote depends on dates and availability.",
  },
  el: {
    intro: "Το νησί σου. Με τον δικό σου ρυθμό.",
    headline: "Λίγο πιο μακριά.",
    accent: "Πολύ περισσότερη Νάξος.",
    description:
      "Αλμύρα στον αέρα. Χωριά στα βουνά. Μια παραλία που παραλίγο να προσπεράσεις. Βρες το αυτοκίνητό σου στη Νάξο και άφησε χώρο για το απρόσμενο.",
    explore: "Βρες το αυτοκίνητό σου",
    arrival: "Από πού ξεκινά το ταξίδι σου;",
    arrivalNote: "Επίλεξε σημείο άφιξης. Θα σε βοηθήσουμε με τα υπόλοιπα.",
    airport: "Αεροδρόμιο Νάξου",
    port: "Λιμάνι Νάξου",
    stay: "Το κατάλυμά σου",
    pickup: "Πληροφορίες παραλαβής",
    fleet: "Ωραίο αυτοκίνητο. Αξέχαστες μέρες.",
    fleetIntro:
      "Ευέλικτα για το νησί. Άνετα για τη μεγάλη διαδρομή. Σύγκρινε τα αυτοκίνητά μας και δες διαθεσιμότητα για τις ημερομηνίες σου.",
    all: "Όλα τα αυτοκίνητα",
    automatic: "Αυτόματα αυτοκίνητα",
    family: "Οικογενειακά & 7θέσια",
    suv: "SUV & 4×4",
    automaticDesc: "Άνετη οδήγηση, από την ακτή στα χωριά.",
    familyDesc: "Περισσότερος χώρος για παρέα και αποσκευές.",
    suvDesc: "Χώρος και άνεση στις διαδρομές του νησιού.",
    island: "Το νησί γράφει τη διαδρομή.",
    islandText:
      "Ακολούθησε την ακτή. Σταμάτα για μια βουτιά. Στρίψε προς τα χωριά. Οι οδηγοί μας για τη Νάξο σε βοηθούν να επιλέξεις την επόμενη στάση.",
    coast: "Μια μέρα στη θάλασσα",
    villages: "Ο δρόμος για τα χωριά",
    sunset: "Μείνε για το ηλιοβασίλεμα",
    journal: "Πριν πιάσεις το τιμόνι.",
    people: "Ντόπιοι άνθρωποι. Προσωπική εξυπηρέτηση.",
    peopleText:
      "Γνώρισε τον Μάριο και τη Ρία, τους ανθρώπους πίσω από τη Fast Motor Rental Naxos. Άμεση επικοινωνία, πρακτικές συμβουλές και ένα αυτοκίνητο για το ταξίδι που έχεις στο μυαλό σου.",
    final: "Δες πού θα σε βγάλει ο δρόμος.",
    finalText: "Οι μέρες σου. Το αυτοκίνητό σου. Η δική σου Νάξος.",
    available: "Δες διαθεσιμότητα",
    cars: "Αυτοκίνητα στον στόλο",
    since: "Οικογενειακή επιχείρηση από το",
    details: "Δες το αυτοκίνητο",
    terms: "Όροι ενοικίασης",
    reviews: "Κριτικές πελατών",
    legal: "Νομικές πληροφορίες",
    seasonal:
      "Ενδεικτική εποχική τιμή. Η τελική προσφορά εξαρτάται από τις ημερομηνίες και τη διαθεσιμότητα.",
  },
  it: {
    intro: "La tua isola. Il tuo ritmo.",
    headline: "Un po’ più lontano.",
    accent: "Molto più Naxos.",
    description:
      "Sale nell’aria. Borghi sulle colline. Una spiaggia da scoprire. Trova la tua auto a noleggio a Naxos e lascia spazio all’imprevisto.",
    explore: "Trova la tua auto",
    arrival: "Da dove inizia il tuo viaggio?",
    arrivalNote: "Scegli il punto di arrivo. Ti aiutiamo con il resto.",
    airport: "Aeroporto di Naxos",
    port: "Porto di Naxos",
    stay: "Il tuo alloggio",
    pickup: "Dettagli del ritiro",
    fleet: "L’auto giusta. Giornate speciali.",
    fleetIntro:
      "Agili per l’isola, comode per la strada più lunga. Confronta le nostre auto e verifica la disponibilità per le tue date.",
    all: "Tutte le auto",
    automatic: "Auto automatiche",
    family: "Famiglie e 7 posti",
    suv: "SUV e 4×4",
    automaticDesc: "Una guida semplice, dalla costa ai borghi.",
    familyDesc: "Più spazio per le persone e i bagagli.",
    suvDesc: "Spazio e comfort per esplorare l’isola.",
    island: "L’isola è il tuo itinerario.",
    islandText:
      "Segui la costa. Fermati per un bagno. Svolta verso i borghi. Le nostre guide di Naxos ti aiutano a scegliere la prossima tappa.",
    coast: "Una giornata al mare",
    villages: "La strada panoramica",
    sunset: "Aspetta il tramonto",
    journal: "Prima di metterti al volante.",
    people: "Un’impresa dell’isola. Un benvenuto personale.",
    peopleText:
      "Conosci Marios e Ria, le persone dietro Fast Motor Rental Naxos. Un contatto diretto, consigli pratici e un’auto per il viaggio che immagini.",
    final: "Scopri dove ti porta la strada.",
    finalText: "Le tue date. La tua auto. La tua storia a Naxos.",
    available: "Verifica disponibilità",
    cars: "Auto nella flotta",
    since: "A conduzione familiare dal",
    details: "Scopri l’auto",
    terms: "Condizioni di noleggio",
    reviews: "Recensioni degli ospiti",
    legal: "Informazioni legali",
    seasonal:
      "Prezzo stagionale indicativo. Il preventivo finale dipende dalle date e dalla disponibilità.",
  },
  fr: {
    intro: "Votre île. À votre rythme.",
    headline: "Un peu plus loin.",
    accent: "Tellement plus de Naxos.",
    description:
      "L’air marin. Les villages perchés. Une plage à découvrir. Trouvez votre voiture de location à Naxos et laissez une place à l’imprévu.",
    explore: "Trouvez votre voiture",
    arrival: "Où commence votre voyage ?",
    arrivalNote:
      "Choisissez votre point d’arrivée. Nous vous aidons pour la suite.",
    airport: "Aéroport de Naxos",
    port: "Port de Naxos",
    stay: "Votre hébergement",
    pickup: "Détails du retrait",
    fleet: "La bonne voiture. De belles journées.",
    fleetIntro:
      "Agiles sur l’île, confortables sur les longs trajets. Comparez nos voitures et consultez les disponibilités pour vos dates.",
    all: "Toutes les voitures",
    automatic: "Voitures automatiques",
    family: "Familles et 7 places",
    suv: "SUV et 4×4",
    automaticDesc: "Une conduite facile, de la côte aux villages.",
    familyDesc: "Plus de place pour vos proches et leurs bagages.",
    suvDesc: "Espace et confort pour parcourir l’île.",
    island: "L’île dessine votre itinéraire.",
    islandText:
      "Longez la côte. Arrêtez-vous pour une baignade. Prenez la route des villages. Nos guides de Naxos vous aident à choisir la prochaine étape.",
    coast: "Une journée à la mer",
    villages: "La route des villages",
    sunset: "Restez pour le coucher du soleil",
    journal: "Avant de prendre le volant.",
    people: "Une entreprise locale. Un accueil personnel.",
    peopleText:
      "Rencontrez Marios et Ria, les visages de Fast Motor Rental Naxos. Un échange direct, des conseils pratiques et une voiture pour votre voyage.",
    final: "Voyez où la route vous mène.",
    finalText: "Vos dates. Votre voiture. Votre histoire à Naxos.",
    available: "Voir les disponibilités",
    cars: "Voitures dans notre flotte",
    since: "Entreprise familiale depuis",
    details: "Découvrir la voiture",
    terms: "Conditions de location",
    reviews: "Avis des voyageurs",
    legal: "Informations légales",
    seasonal:
      "Tarif saisonnier indicatif. Le devis final dépend des dates et de la disponibilité.",
  },
  de: {
    intro: "Deine Insel. Dein eigener Weg.",
    headline: "Ein Stück weiter.",
    accent: "Viel mehr Naxos.",
    description:
      "Salz in der Luft. Dörfer in den Bergen. Ein Strand, den du fast verpasst hättest. Finde deinen Mietwagen auf Naxos und lass Raum für Entdeckungen.",
    explore: "Finde dein Auto",
    arrival: "Wo beginnt deine Reise?",
    arrivalNote: "Wähle deinen Ankunftsort. Wir helfen dir mit dem Rest.",
    airport: "Flughafen Naxos",
    port: "Hafen Naxos",
    stay: "Deine Unterkunft",
    pickup: "Details zur Abholung",
    fleet: "Das passende Auto. Besondere Tage.",
    fleetIntro:
      "Wendig für die Insel. Bequem für den längeren Heimweg. Vergleiche unsere Autos und prüfe die Verfügbarkeit für deine Reisedaten.",
    all: "Alle Autos",
    automatic: "Automatikautos",
    family: "Familien & 7-Sitzer",
    suv: "SUV & 4×4",
    automaticDesc: "Entspannt fahren, von der Küste in die Dörfer.",
    familyDesc: "Mehr Platz für deine Mitreisenden und Gepäck.",
    suvDesc: "Platz und Komfort für Inseltouren.",
    island: "Die Insel ist dein Reiseplan.",
    islandText:
      "Folge der Küste. Halte zum Schwimmen an. Biege zu den Dörfern ab. Unsere Naxos-Reiseführer helfen dir beim nächsten Ziel.",
    coast: "Ein Tag am Meer",
    villages: "Der Weg in die Dörfer",
    sunset: "Bleib zum Sonnenuntergang",
    journal: "Bevor du losfährst.",
    people: "Ein Inselbetrieb. Ein persönlicher Empfang.",
    peopleText:
      "Lerne Marios und Ria kennen, die Menschen hinter Fast Motor Rental Naxos. Direkter Kontakt, praktische Inseltipps und ein Auto für deine Reise.",
    final: "Entdecke, wohin der Weg dich führt.",
    finalText: "Deine Reisedaten. Dein Auto. Deine Naxos-Geschichte.",
    available: "Verfügbarkeit prüfen",
    cars: "Autos in unserer Flotte",
    since: "Familiengeführt seit",
    details: "Auto entdecken",
    terms: "Mietbedingungen",
    reviews: "Gästebewertungen",
    legal: "Rechtliche Informationen",
    seasonal:
      "Unverbindlicher Saisonpreis. Das endgültige Angebot hängt von Reisedaten und Verfügbarkeit ab.",
  },
} satisfies Record<Locale, Record<string, string>>;

export const designCopy = (locale: Locale) => copy[locale];
