import type { Faq } from "@/types/content";

const ls = (en: string, el?: string, it?: string, fr?: string, de?: string) => ({
  en, el: el ?? en, it: it ?? en, fr: fr ?? en, de: de ?? en,
});

export const FAQS: Faq[] = [
  {
    slug: "do-i-need-car-naxos",
    category: "vehicles",
    question: ls(
      "Do I need to rent a car on Naxos?",
      "Χρειάζομαι αυτοκίνητο στη Νάξο;",
      "Serve l'auto a Naxos?",
      "Faut-il louer une voiture à Naxos ?",
      "Brauche ich auf Naxos ein Auto?",
    ),
    answer: ls(
      "If you're staying in Chora and only visiting the closest beaches, no  -  buses and taxis cover that. For the inland villages (Chalki, Filoti, Apeiranthos), Apollonas, Mikri Vigla and Alyko, a rental gives you 5–10× the freedom of the bus schedule. Most visitors who rent for at least 3 days say it's the best money they spent on the island.",
      "Αν μένετε μόνο στη Χώρα και θέλετε να δείτε τις πολύ κοντινές παραλίες, μπορείτε να κινηθείτε και χωρίς αυτοκίνητο. Για τα χωριά της ενδοχώρας (Χαλκί, Φιλότι, Απείρανθος), τον Απόλλωνα, τη Μικρή Βίγλα και το Αλυκό, η ενοικίαση σας δίνει πολλαπλάσια ελευθερία από τα δρομολόγια λεωφορείων. Οι περισσότεροι επισκέπτες που νοικιάζουν για 3+ ημέρες το θεωρούν από τις καλύτερες επιλογές του ταξιδιού.",
      "Se resti a Chora e visiti solo le spiagge vicine, no. Per i villaggi interni, Apollonas, Mikri Vigla e Alyko, il noleggio è essenziale.",
      "Si tu restes à Chora et ne visites que les plages proches, non. Pour l'arrière-pays, Apollonas, Mikri Vigla et Alyko, la location est essentielle.",
      "Wenn Sie in Chora bleiben und nur die nahen Strände besuchen, nein. Für die Bergdörfer, Apollonas, Mikri Vigla und Alyko ist eine Anmietung essenziell.",
    ),
  },
  {
    slug: "idp-greece",
    category: "documents",
    question: ls(
      "Do I need an International Driving Permit (IDP) in Greece?",
      "Χρειάζομαι International Driving Permit (IDP) στην Ελλάδα;",
      "Serve la patente internazionale (IDP) in Grecia?",
      "Faut-il un permis international (IDP) en Grèce ?",
      "Brauche ich einen internationalen Führerschein (IDP) in Griechenland?",
    ),
    answer: ls(
      "Greek Law 4850/2021 (in force since 5 November 2021) removed the IDP requirement for licence holders from EU/EEA, the UK, USA, Canada, Australia and Gibraltar for tourist stays under 6 months. If your licence is in Latin script and shows your photo, your country's home licence is enough. Visitors from countries outside that list (e.g. China, India, most Latin American states) still need an IDP.",
      "Ο Νόμος 4850/2021 κατάργησε την υποχρέωση IDP για κατόχους αδειών ΕΕ/ΗΠΑ/Καναδά/ΗΒ/Αυστραλίας/Γιβραλτάρ για τουριστική διαμονή κάτω των 6 μηνών. Άλλες χώρες χρειάζονται IDP.",
      "La legge greca 4850/2021 ha eliminato l'obbligo dell'IDP per UE/USA/Canada/UK/Australia/Gibilterra per soggiorni turistici sotto 6 mesi.",
      "La loi grecque 4850/2021 a supprimé l'obligation du permis international pour UE/USA/Canada/Royaume-Uni/Australie/Gibraltar pour séjours touristiques < 6 mois.",
      "Das griechische Gesetz 4850/2021 hat die IDP-Pflicht für EU/USA/Kanada/UK/Australien/Gibraltar bei Touristenaufenthalten unter 6 Monaten abgeschafft.",
    ),
  },
  {
    slug: "automatic-availability",
    category: "vehicles",
    question: ls(
      "Are automatic cars available on Naxos?",
      "Υπάρχουν αυτόματα αυτοκίνητα στη Νάξο;",
      "Ci sono auto automatiche a Naxos?",
      "Y a-t-il des voitures automatiques à Naxos ?",
      "Gibt es Automatikautos auf Naxos?",
    ),
    answer: ls(
      "Yes, but supply is tight. We always keep automatic Hyundai i10, Kia Picanto, Citroen C3, Peugeot 208, Toyota RAV4, Kia Sportage and Polaris buggies. In July and August book at least 3 weeks in advance for guaranteed automatic. Outside high season we usually have same-week availability.",
      "Ναι, διαθέτουμε αυτόματα μικρά αυτοκίνητα, οικογενειακά μοντέλα, SUV και buggies, όμως η διαθεσιμότητα στη Νάξο είναι περιορισμένη. Για Ιούλιο και Αύγουστο προτείνουμε κράτηση τουλάχιστον 3 εβδομάδες πριν, ειδικά αν θέλετε συγκεκριμένο μοντέλο. Εκτός υψηλής σεζόν συνήθως υπάρχει διαθεσιμότητα και μέσα στην ίδια εβδομάδα.",
      "Sì, ma la disponibilità è limitata. In alta stagione prenota 3 settimane prima.",
      "Oui, mais la disponibilité est limitée. En haute saison, réserve 3 semaines avant.",
      "Ja, aber die Verfügbarkeit ist begrenzt. In der Hauptsaison 3 Wochen im Voraus buchen.",
    ),
  },
  {
    slug: "4x4-needed",
    category: "vehicles",
    question: ls(
      "Do I need a 4×4 / SUV / Jeep on Naxos?",
      "Χρειάζομαι 4×4 ή SUV στη Νάξο;",
      "Serve un 4×4 / SUV a Naxos?",
      "Faut-il un 4×4 / SUV à Naxos ?",
      "Brauche ich ein 4×4 / SUV auf Naxos?",
    ),
    answer: ls(
      "No for 95% of itineraries. The road network  -  including the climb to Apeiranthos and Apollonas  -  is paved and a small car handles it fine. You only need a 4×4 if you plan to drive the dirt tracks to remote chapels, the Alyko cedar dunes, or the goat tracks above Mikri Vigla. Most rental contracts (ours included) forbid taking a non-4×4 vehicle off-road, so respect it.",
      "Όχι για το 95% των διαδρομών. Οι βασικοί δρόμοι προς Χώρα, παραλίες, Απείρανθο, Φιλότι και Απόλλωνα είναι ασφαλτοστρωμένοι και ένα μικρό αυτοκίνητο αρκεί. 4×4 χρειάζεστε μόνο αν σκοπεύετε να κινηθείτε σε χωματόδρομους ή πιο απομονωμένα σημεία. Θυμηθείτε ότι τα περισσότερα συμβόλαια ενοικίασης δεν επιτρέπουν off-road οδήγηση με απλό αυτοκίνητο.",
      "No nel 95% dei casi. 4×4 solo per strade sterrate.",
      "Non dans 95% des cas. 4×4 seulement pour les pistes.",
      "In 95% der Fälle nein. 4×4 nur für Schotterwege.",
    ),
  },
  {
    slug: "airport-vs-port-pickup",
    category: "delivery",
    question: ls(
      "Should I rent at the port or at the airport?",
      "Να νοικιάσω στο λιμάνι ή στο αεροδρόμιο;",
      "Meglio noleggiare al porto o aeroporto?",
      "Plutôt port ou aéroport pour la location ?",
      "Lieber im Hafen oder Flughafen mieten?",
    ),
    answer: ls(
      "Whichever is closer to your arrival point  -  both are free. We meet you at JNX (under 4 km from Chora) or at the port (2-min walk to our office). The price is identical. Tell us your flight or ferry on WhatsApp the day before.",
      "Ό,τι σας βολεύει περισσότερο  -  και τα δύο σημεία είναι δωρεάν. Στο αεροδρόμιο JNX σας συναντάμε στην άφιξη, ενώ στο λιμάνι το γραφείο είναι πολύ κοντά. Η τιμή δεν αλλάζει ανάλογα με το σημείο παραλαβής. Στείλτε μας πτήση ή πλοίο στο WhatsApp για να οργανώσουμε την παράδοση χωρίς αναμονή.",
      "Quello più vicino al tuo arrivo  -  entrambi gratis.",
      "Le plus proche de ton arrivée  -  les deux gratuits.",
      "Was näher liegt  -  beides kostenlos.",
    ),
  },
  {
    slug: "advance-vs-walkin",
    category: "booking",
    question: ls(
      "Is it cheaper to book in advance or walk in on arrival?",
      "Είναι φθηνότερα η προ-κράτηση ή η on-spot;",
      "Conviene prenotare prima o all'arrivo?",
      "Réserver à l'avance ou sur place ?",
      "Vorab oder vor Ort buchen?",
    ),
    answer: ls(
      "Advance is cheaper and safer in July, August and the first half of September  -  local supply runs out and walk-in prices spike. May, June, late September and October are usually fine to book a day or two before. We hold the same online price either way; we don't penalise advance bookings.",
      "Τον Ιούλιο, τον Αύγουστο και στις αρχές Σεπτεμβρίου η προ-κράτηση είναι πιο ασφαλής και συχνά πιο οικονομική, γιατί η διαθεσιμότητα μειώνεται γρήγορα. Τον Μάιο, τον Ιούνιο, στα τέλη Σεπτεμβρίου και τον Οκτώβριο μπορείτε συνήθως να κλείσετε και 1–2 ημέρες πριν. Κρατάμε διαφανείς online τιμές και δεν τιμωρούμε την έγκαιρη κράτηση.",
      "In alta stagione meglio prima. Negli altri mesi anche all'arrivo.",
      "En haute saison, à l'avance. Hors saison, l'arrivée convient.",
      "In der Hauptsaison vorab. Sonst geht auch vor Ort.",
    ),
  },
  {
    slug: "rental-cost",
    category: "booking",
    question: ls(
      "How much does a Naxos rental cost?",
      "Πόσο κοστίζει η ενοικίαση στη Νάξο;",
      "Quanto costa il noleggio a Naxos?",
      "Combien coûte une location à Naxos ?",
      "Was kostet die Anmietung auf Naxos?",
    ),
    answer: ls(
      "Indicative ranges in 2026: small cars €30–55/day, mid-size €45–75, SUVs €65–110, scooters €18–48, ATVs €35–120, buggies €110–190. The cheapest month historically is March–April; July–August can be 60–80% more expensive than May. All our prices include unlimited km, basic CDW, taxes, second driver and a baby seat.",
      "Ενδεικτικά για το 2026: μικρά αυτοκίνητα €30–55/ημέρα, μεσαία €45–75, SUV €65–110, μηχανάκια €18–48, ATV €35–120 και buggy €110–190. Οι τιμές ανεβαίνουν τον Ιούλιο και τον Αύγουστο, ενώ Μάιο, αρχές Ιουνίου, τέλος Σεπτεμβρίου και Οκτώβριο είναι συνήθως χαμηλότερες. Στις τιμές μας περιλαμβάνονται απεριόριστα χιλιόμετρα, βασική ασφάλεια, φόροι, δεύτερος οδηγός και παιδικό κάθισμα.",
      "Indicativo: piccole €30–55, medie €45–75, SUV €65–110, scooter €18–48, ATV €35–120, buggy €110–190.",
      "Indicatif : petites €30–55, moyennes €45–75, SUV €65–110, scooters €18–48, ATV €35–120, buggys €110–190.",
      "Richtwerte: Kleinwagen €30–55, Mittelklasse €45–75, SUV €65–110, Roller €18–48, ATV €35–120, Buggy €110–190.",
    ),
  },
  {
    slug: "minimum-age",
    category: "documents",
    question: ls(
      "What's the minimum age to rent a car on Naxos?",
      "Ποια είναι η ελάχιστη ηλικία ενοικίασης;",
      "Qual è l'età minima per noleggiare?",
      "Âge minimum pour louer ?",
      "Mindestalter für die Anmietung?",
    ),
    answer: ls(
      "21 years old, with the licence held for at least 1 year, for our cars. 23 years for SUVs and the buggy. No upper age limit. Drivers under 25 may have a small young-driver surcharge  -  we'll always tell you in advance.",
      "Για αυτοκίνητα χρειάζεται ηλικία 21+ και δίπλωμα τουλάχιστον 1 έτους. Για SUV και buggy η ελάχιστη ηλικία είναι 23 ετών. Δεν υπάρχει ανώτατο όριο ηλικίας. Για οδηγούς 21–24 ετών μπορεί να υπάρχει μικρή χρέωση νέου οδηγού, την οποία αναφέρουμε πάντα πριν την κράτηση.",
      "21 anni con patente da almeno 1 anno. 23 per SUV e buggy.",
      "21 ans, permis depuis 1 an. 23 pour SUV et buggy.",
      "21 Jahre, Führerschein seit 1 Jahr. 23 für SUV und Buggy.",
    ),
  },
  {
    slug: "insurance-included",
    category: "insurance",
    question: ls(
      "Is insurance included? What's the deposit?",
      "Συμπεριλαμβάνεται η ασφάλεια; Ποια είναι η εγγύηση;",
      "L'assicurazione è inclusa? Quanto è il deposito?",
      "L'assurance est-elle incluse ? Quelle caution ?",
      "Ist die Versicherung inklusive? Wie hoch die Kaution?",
    ),
    answer: ls(
      "Basic CDW is included with every rental. Deposit varies €100–€800 depending on insurance level. Full CDW (€150 excess) and Zero Excess (€0) are optional upgrades. Tyres, undercarriage and windscreen are NOT covered by basic  -  choose Full or Zero if you'll be on rougher village roads.",
      "Η βασική ασφάλεια CDW περιλαμβάνεται σε κάθε ενοικίαση. Η εγγύηση κυμαίνεται συνήθως από €100 έως €800 ανάλογα με το όχημα και το επίπεδο κάλυψης. Μπορείτε να επιλέξετε Full CDW ή Zero Excess για μικρότερη ή μηδενική απαλλαγή. Ελαστικά, κάτω μέρος και παρμπρίζ δεν καλύπτονται από τη βασική ασφάλεια.",
      "CDW base inclusa. Deposito €100–€800 secondo il livello.",
      "CDW de base inclus. Caution €100–€800 selon niveau.",
      "Basis-CDW inklusive. Kaution €100–€800 je nach Stufe.",
    ),
  },
  {
    slug: "documents-needed",
    category: "documents",
    question: ls(
      "What documents do I need at pickup?",
      "Τι έγγραφα χρειάζομαι στην παραλαβή;",
      "Quali documenti servono al ritiro?",
      "Quels documents au retrait ?",
      "Welche Dokumente bei Abholung?",
    ),
    answer: ls(
      "Your driving licence, passport or national ID, and a credit card (for the deposit hold). Debit cards are usually accepted but the deposit may be charged rather than held. IDP only if your country's licence is not in Latin script.",
      "Χρειάζεστε έγκυρο δίπλωμα οδήγησης, διαβατήριο ή ταυτότητα και κάρτα για την εγγύηση. Η πιστωτική κάρτα είναι προτιμότερη για δέσμευση ποσού, αλλά σε πολλές περιπτώσεις δεχόμαστε και χρεωστική ή μετρητά κατόπιν συνεννόησης. IDP χρειάζεται μόνο αν η άδειά σας δεν αναγνωρίζεται ή δεν είναι σε λατινικούς χαρακτήρες.",
      "Patente, passaporto/carta d'identità, carta di credito.",
      "Permis, passeport/carte d'identité, carte de crédit.",
      "Führerschein, Reisepass/ID, Kreditkarte.",
    ),
  },
  {
    slug: "fuel-policy",
    category: "vehicles",
    question: ls(
      "What's the fuel policy?",
      "Ποια είναι η πολιτική καυσίμου;",
      "Qual è la politica del carburante?",
      "Quelle politique carburant ?",
      "Wie ist die Tankregelung?",
    ),
    answer: ls(
      "Same-to-same. We hand over the car with whatever fuel level is in it (usually full or near-full) and you return it at the same level. No 'pre-purchase' tricks, no top-up fees, no penalty if you return slightly under as long as it's reasonable.",
      "Η πολιτική είναι same-to-same: παραλαμβάνετε το όχημα με συγκεκριμένο επίπεδο καυσίμου και το επιστρέφετε στο ίδιο. Δεν υπάρχουν υποχρεωτικές προπληρωμές καυσίμων ή κρυφές χρεώσεις. Αν η διαφορά είναι μικρή και λογική, το χειριζόμαστε ανθρώπινα.",
      "Stesso a stesso  -  restituisci come l'hai presa.",
      "Identique  -  rendre comme reçue.",
      "Same-to-same  -  bei gleichem Tankstand zurück.",
    ),
  },
  {
    slug: "ferry-with-rental",
    category: "vehicles",
    question: ls(
      "Can I take the rental car on the ferry to another island?",
      "Μπορώ να πάρω το αυτοκίνητο στο πλοίο;",
      "Posso portare l'auto sul traghetto?",
      "Puis-je embarquer la voiture sur le ferry ?",
      "Darf ich den Wagen auf die Fähre nehmen?",
    ),
    answer: ls(
      "No, not without written permission. Like every other Naxos rental company, our standard contract forbids leaving the island. If you have a special case (e.g. transfer to Paros for the day), tell us before booking  -  sometimes we can authorise it with extra insurance.",
      "Όχι χωρίς γραπτή άδεια. Σε ειδικές περιπτώσεις μπορούμε να εγκρίνουμε με επιπλέον ασφάλεια.",
      "No, senza permesso scritto.",
      "Non, sans autorisation écrite.",
      "Nein, ohne schriftliche Genehmigung.",
    ),
  },
  {
    slug: "driving-difficulty",
    category: "driving",
    question: ls(
      "Is driving on Naxos difficult? Are the roads good?",
      "Είναι δύσκολη η οδήγηση στη Νάξο; Είναι καλοί οι δρόμοι;",
      "È difficile guidare a Naxos? Le strade sono buone?",
      "Conduire à Naxos est-il difficile ?",
      "Ist das Fahren auf Naxos schwierig?",
    ),
    answer: ls(
      "Main roads are paved and in good shape. Mountain switchbacks (especially Filoti–Apeiranthos and Chalki–Moni) demand attention but are not technically difficult. The biggest hazards are: narrow village streets, scooters overtaking, goats on the road, and unlit roads at night  -  avoid driving the back roads after sunset on your first day.",
      "Οι κύριοι δρόμοι είναι καλοί. Στροφές βουνού απαιτούν προσοχή. Αποφύγετε νυχτερινή οδήγηση στους εσωτερικούς δρόμους.",
      "Strade principali buone. Curve di montagna richiedono attenzione.",
      "Routes principales bonnes. Virages de montagne exigent de l'attention.",
      "Hauptstraßen gut. Bergkurven erfordern Aufmerksamkeit.",
    ),
  },
  {
    slug: "chora-parking",
    category: "driving",
    question: ls(
      "Where can I park in Chora?",
      "Πού μπορώ να παρκάρω στη Χώρα;",
      "Dove parcheggio a Chora?",
      "Où se garer à Chora ?",
      "Wo parke ich in Chora?",
    ),
    answer: ls(
      "Free parking at the port (often full by 11:00 in summer) and along the harbour road. Pay-and-display in the centre. The smartest move is to park at the port and walk in  -  the old town is car-free anyway.",
      "Δωρεάν παρκινγκ στο λιμάνι (γεμίζει στις 11:00). Παρκάρετε στο λιμάνι και περπατήστε.",
      "Parcheggio gratis al porto (pieno dalle 11:00).",
      "Parking gratuit au port (plein dès 11h).",
      "Kostenlos am Hafen (ab 11:00 voll).",
    ),
  },
  {
    slug: "speed-limits-2026",
    category: "driving",
    question: ls(
      "What are the speed limits in Greece in 2026?",
      "Ποια είναι τα όρια ταχύτητας στην Ελλάδα το 2026;",
      "Quali sono i limiti di velocità in Grecia nel 2026?",
      "Limites de vitesse en Grèce en 2026 ?",
      "Tempolimits in Griechenland 2026?",
    ),
    answer: ls(
      "Effective 1 January 2026: 30 km/h within cities (down from 50), 90 km/h on rural roads, 110 km/h on expressways, 130 km/h on motorways. Greece is the second EU country (after Spain) to adopt the 30 km/h urban limit. Naxos is mostly rural and village roads  -  expect a lot of 30 and 50 zones.",
      "Από 1/1/2026: 30 εντός πόλης, 90 αγροτικά, 110 ταχείας, 130 αυτοκινητόδρομου.",
      "Dall'1/1/2026: 30 città, 90 extraurbane, 110 superstrade, 130 autostrade.",
      "Au 1/1/2026 : 30 ville, 90 hors agglo, 110 voie rapide, 130 autoroute.",
      "Ab 1.1.2026: 30 in Städten, 90 Landstraße, 110 Schnellstraße, 130 Autobahn.",
    ),
  },
  {
    slug: "alcohol-limit",
    category: "driving",
    question: ls(
      "What's the alcohol limit for driving in Greece?",
      "Ποιο είναι το όριο αλκοόλ για οδήγηση;",
      "Qual è il limite di alcol per guidare?",
      "Quel taux d'alcool autorisé ?",
      "Wie hoch die Promillegrenze?",
    ),
    answer: ls(
      "0.05% blood alcohol for full-licence drivers, 0.02% for drivers with under 2 years experience and for motorcyclists. Above that you face fines and an automatic licence suspension. The Greek police run frequent checks on Naxos in summer.",
      "0.05% για κανονικούς οδηγούς, 0.02% για νέους και μοτοσικλετιστές.",
      "0,05% standard, 0,02% neopatentati e motociclisti.",
      "0,05% standard, 0,02% jeunes conducteurs et motards.",
      "0,05% Standard, 0,02% Fahranfänger und Motorradfahrer.",
    ),
  },
  {
    slug: "child-seats",
    category: "vehicles",
    question: ls(
      "Are child seats included?",
      "Τα παιδικά καθίσματα είναι δωρεάν;",
      "I seggiolini sono inclusi?",
      "Les sièges enfant sont-ils inclus ?",
      "Sind Kindersitze inklusive?",
    ),
    answer: ls(
      "Yes  -  one baby seat or booster is free with every car. Greek law requires a proper seat for under-3s, a booster for 3–11s, and forbids children under 12 (or shorter than 1.35 m) from sitting in the front. Multiple seats free on request  -  just message us.",
      "Ναι, ένα δωρεάν με κάθε αυτοκίνητο. Πολλαπλά κατόπιν ζήτησης.",
      "Sì, uno gratis. Multipli su richiesta.",
      "Oui, un gratuit. Plusieurs sur demande.",
      "Ja, einer kostenlos. Mehrere auf Anfrage.",
    ),
  },
  {
    slug: "second-driver",
    category: "documents",
    question: ls(
      "Is the second driver free?",
      "Είναι δωρεάν ο 2ος οδηγός;",
      "Il secondo guidatore è gratis?",
      "Le second conducteur est-il gratuit ?",
      "Ist der zweite Fahrer kostenlos?",
    ),
    answer: ls(
      "Yes, always. Bring their licence at pickup so we can write them on the contract.",
      "Ναι, πάντα. Φέρτε το δίπλωμά του στην παραλαβή.",
      "Sì, sempre. Porta la patente al ritiro.",
      "Oui, toujours. Apporte son permis au retrait.",
      "Ja, immer. Führerschein bei Abholung mitbringen.",
    ),
  },
  {
    slug: "what-if-damage",
    category: "insurance",
    question: ls(
      "What happens if I scratch or damage the car?",
      "Τι γίνεται αν χτυπήσω/γραντζουνίσω το αυτοκίνητο;",
      "Cosa succede se danneggio l'auto?",
      "Et si je raye / abîme la voiture ?",
      "Was passiert bei einem Schaden?",
    ),
    answer: ls(
      "We follow a transparent damage protocol. We photograph the car together at pickup and at return, and any new damage is logged with photos. With Basic CDW you pay up to your excess (€600). With Full CDW it's €150. With Zero Excess you pay nothing. We do not charge invented damage  -  every Google review can attest.",
      "Ακολουθούμε διαφανές πρωτόκολλο ζημιών. Φωτογραφίες παράδοσης και επιστροφής.",
      "Protocollo danni trasparente con foto al ritiro e alla restituzione.",
      "Protocole transparent : photos au retrait et au retour.",
      "Transparentes Schadenprotokoll mit Fotos bei Abholung und Rückgabe.",
    ),
  },
  {
    slug: "cancellation",
    category: "booking",
    question: ls(
      "What is your cancellation policy?",
      "Ποια είναι η πολιτική ακύρωσης;",
      "Qual è la politica di cancellazione?",
      "Quelle politique d'annulation ?",
      "Wie ist die Stornierungsregelung?",
    ),
    answer: ls(
      "Free cancellation up to 24 hours before pickup. After that, we keep the first day as a no-show fee. No questions on the rest. Booking changes (dates, vehicle) are always free.",
      "Δωρεάν ακύρωση έως 24 ώρες πριν. Αλλαγές πάντα δωρεάν.",
      "Cancellazione gratuita fino a 24 ore prima. Modifiche sempre gratis.",
      "Annulation gratuite jusqu'à 24 h avant. Modifications toujours gratuites.",
      "Kostenlose Stornierung bis 24 h vorher. Änderungen immer kostenfrei.",
    ),
  },
  {
    slug: "scooter-licence-50",
    category: "documents",
    question: ls(
      "Can I rent a 50cc scooter with a car licence?",
      "Μπορώ να νοικιάσω 50cc με δίπλωμα Β;",
      "Posso noleggiare 50cc con la patente B?",
      "Puis-je louer un 50cc avec un permis B ?",
      "Kann ich 50cc mit Pkw-Schein mieten?",
    ),
    answer: ls(
      "Yes. Greek law allows 50cc scooters and 150cc ATVs/quads on a category B (car) licence held for at least 1 year. 125cc and above scooters require an A1, A2 or A motorcycle licence.",
      "Ναι, 50cc και ATV 150cc με δίπλωμα Β. 125cc και άνω χρειάζονται δίπλωμα μοτο.",
      "Sì, 50cc e ATV 150cc con patente B. 125cc+ patente moto.",
      "Oui, 50cc et ATV 150cc avec permis B. 125cc+ permis moto.",
      "Ja, 50cc und ATV 150cc mit Pkw-Schein. Ab 125cc Motorradschein.",
    ),
  },
  {
    slug: "credit-card-required",
    category: "booking",
    question: ls(
      "Do I need a credit card?",
      "Χρειάζομαι πιστωτική κάρτα;",
      "Serve una carta di credito?",
      "Faut-il une carte de crédit ?",
      "Brauche ich eine Kreditkarte?",
    ),
    answer: ls(
      "Strongly preferred for the deposit hold (we don't actually charge it). Debit cards are accepted but the deposit will be a real charge that we refund at return. Cash deposits also possible, please ask in advance.",
      "Συνήθως ναι για την εγγύηση. Χρεωστική γίνεται δεκτή με χρέωση που επιστρέφεται.",
      "Preferibile per il deposito.",
      "Préférable pour la caution.",
      "Bevorzugt für die Kaution.",
    ),
  },
  {
    slug: "extra-driver-fee",
    category: "insurance",
    question: ls(
      "Is there a young-driver fee under 25?",
      "Υπάρχει χρέωση για οδηγό κάτω των 25;",
      "C'è un supplemento giovane conducente sotto i 25?",
      "Y a-t-il un supplément jeune conducteur < 25 ans ?",
      "Gibt es einen Jungfahrer-Aufschlag unter 25?",
    ),
    answer: ls(
      "€5/day young-driver fee for drivers aged 21–24 on cars and SUVs. No surcharge on scooters, ATVs or buggies once the age requirement is met.",
      "€5/ημέρα για οδηγούς 21–24 σε αυτοκίνητα και SUV.",
      "€5/giorno per conducenti 21–24 su auto e SUV.",
      "€5/jour conducteurs 21–24 sur voitures et SUV.",
      "€5/Tag für 21–24 bei Pkw und SUV.",
    ),
  },
  {
    slug: "delivery-zones",
    category: "delivery",
    question: ls(
      "Where do you deliver vehicles for free?",
      "Πού παραδίδετε δωρεάν;",
      "Dove consegnate gratis?",
      "Où livrez-vous gratuitement ?",
      "Wohin liefern Sie kostenlos?",
    ),
    answer: ls(
      "Anywhere on Naxos. Airport, port, every village, every beach hotel. Free is free  -  no minimum rental days, no hidden fees.",
      "Παντού στη Νάξο. Δωρεάν, χωρίς όρια.",
      "Ovunque a Naxos. Gratis senza minimi.",
      "Partout à Naxos. Gratuit sans minimum.",
      "Überall auf Naxos. Kostenlos, ohne Mindestzeit.",
    ),
  },
  {
    slug: "automatic-vs-manual",
    category: "vehicles",
    question: ls(
      "Should I rent automatic or manual on Naxos?",
      "Αυτόματο ή χειροκίνητο στη Νάξο;",
      "Meglio automatico o manuale a Naxos?",
      "Auto ou manuel à Naxos ?",
      "Automatik oder Schalter auf Naxos?",
    ),
    answer: ls(
      "Manual is fine for confident drivers  -  Naxos isn't San Francisco. Automatic is calmer if you'll be doing stop-and-go in Chora and around tight Stelida roads, especially for two-driver families splitting the wheel.",
      "Χειροκίνητο για έμπειρους οδηγούς. Αυτόματο πιο άνετο σε Χώρα και Στελίδα.",
      "Manuale per guidatori esperti. Automatico più rilassato in Chora.",
      "Manuel pour conducteurs confirmés. Auto plus reposant à Chora.",
      "Schalter für erfahrene Fahrer. Automatik entspannter in Chora.",
    ),
  },
  {
    slug: "best-time-to-rent",
    category: "booking",
    question: ls(
      "When is the best time to visit Naxos by car?",
      "Πότε είναι η καλύτερη εποχή για road trip στη Νάξο;",
      "Quando è il momento migliore per visitare Naxos in auto?",
      "Quelle est la meilleure période pour Naxos en voiture ?",
      "Wann ist die beste Zeit für eine Autotour auf Naxos?",
    ),
    answer: ls(
      "Mid-May to mid-June and mid-September to mid-October. Warm weather, swimmable sea, low queues, full availability of the fleet at shoulder prices. Avoid early August if you can  -  it's the busiest week of the year.",
      "Μέσα Μαΐου–μέσα Ιουνίου και μέσα Σεπτεμβρίου–μέσα Οκτωβρίου.",
      "Metà maggio–metà giugno e metà settembre–metà ottobre.",
      "Mi-mai à mi-juin et mi-septembre à mi-octobre.",
      "Mitte Mai–Mitte Juni und Mitte September–Mitte Oktober.",
    ),
  },
  {
    slug: "ev-charging",
    category: "vehicles",
    question: ls(
      "Are there electric cars and charging points on Naxos?",
      "Υπάρχουν ηλεκτρικά αυτοκίνητα και σημεία φόρτισης;",
      "Ci sono auto elettriche e colonnine a Naxos?",
      "Y a-t-il des voitures électriques et bornes à Naxos ?",
      "Gibt es E-Autos und Ladesäulen auf Naxos?",
    ),
    answer: ls(
      "Charging points exist in Chora and a handful of major hotels. We don't currently offer fully-electric rentals because the island infrastructure is still thin  -  when it improves, we'll add a Tesla Model Y. We do offer Toyota RAV4 Hybrid for low-fuel touring.",
      "Υπάρχουν λίγα σημεία φόρτισης. Δεν προσφέρουμε αμιγώς ηλεκτρικά ακόμη.",
      "Pochi punti di ricarica. Per ora niente elettriche.",
      "Quelques bornes. Pas encore d'électrique.",
      "Wenige Ladesäulen. Noch keine reinen E-Autos.",
    ),
  },
  {
    slug: "drop-off-different",
    category: "delivery",
    question: ls(
      "Can I pick up at the airport and drop off at the port (or vice-versa)?",
      "Παραλαβή σε ένα μέρος και επιστροφή σε άλλο;",
      "Posso ritirare e riconsegnare in posti diversi?",
      "Retrait et restitution à des endroits différents ?",
      "Abholung und Rückgabe an verschiedenen Orten?",
    ),
    answer: ls(
      "Yes, free. Tell us at booking. Both points are free; we'll be there.",
      "Ναι, δωρεάν.",
      "Sì, gratis.",
      "Oui, gratuit.",
      "Ja, kostenlos.",
    ),
  },
  {
    slug: "insurance-ferry-day",
    category: "insurance",
    question: ls(
      "What if I cancel because my ferry is cancelled?",
      "Τι γίνεται αν ακυρωθεί το πλοίο μου;",
      "Cosa succede se il traghetto viene cancellato?",
      "Et si mon ferry est annulé ?",
      "Was, wenn meine Fähre ausfällt?",
    ),
    answer: ls(
      "Send us the cancellation notice on WhatsApp  -  we waive the no-show fee. Aegean weather happens.",
      "Στείλτε μας απόδειξη ακύρωσης στο WhatsApp. Δεν χρεώνουμε no-show.",
      "Inviaci la cancellazione su WhatsApp  -  niente penale.",
      "Envoie-nous l'annulation  -  pas de frais.",
      "Sende uns die Stornobestätigung  -  keine Gebühr.",
    ),
  },
  {
    slug: "booster-or-baby",
    category: "vehicles",
    question: ls(
      "What types of child seats do you provide?",
      "Τι τύπους παιδικών καθισμάτων διαθέτετε;",
      "Quali seggiolini fornite?",
      "Quels types de sièges enfant proposez-vous ?",
      "Welche Kindersitze gibt es?",
    ),
    answer: ls(
      "Rear-facing baby seat (0–13 kg), forward-facing toddler seat (9–18 kg), and high-back booster (15–36 kg). All ECE R44/04 or R129 (i-Size) certified.",
      "Bébé, παιδικό και booster  -  όλα πιστοποιημένα.",
      "Da neonato, bambino e booster  -  tutti certificati.",
      "Bébé, enfant et booster  -  tous certifiés.",
      "Babyschale, Kindersitz und Booster  -  alle zertifiziert.",
    ),
  },
];
