import type { Vehicle } from "@/types/content";

const ls = (en: string, el?: string, it?: string, fr?: string, de?: string) => ({
  en, el: el ?? en, it: it ?? en, fr: fr ?? en, de: de ?? en,
});

export const VEHICLES: Vehicle[] = [
  {
    slug: "hyundai-i10",
    category: "cars",
    brand: "Hyundai",
    model: "i10",
    year: 2024,
    name: ls("Hyundai i10"),
    tagline: ls(
      "The Naxos parking champion — small enough for Chora alleys",
      "Πρωταθλητής στο παρκάρισμα στα στενά της Χώρας",
      "Campione del parcheggio a Chora",
      "Championne du stationnement dans les ruelles de Chora",
      "Parkmeister in den engen Gassen von Chora",
    ),
    description: ls(
      "Our most-rented compact. Five doors, easy automatic shift, fits two suitcases plus carry-ons, and slips into Chora parking spots that turn larger cars away. A favourite for couples and small families spending most days at the beach.",
      "Το πιο ζητούμενο μικρό μας αυτοκίνητο. Πέντε πόρτες, εύκολη αυτόματη αλλαγή ταχυτήτων, χωράει δύο βαλίτσες συν χειραποσκευές και παρκάρει εκεί που τα μεγάλα αυτοκίνητα δεν χωρούν.",
      "La nostra compatta più noleggiata. Cinque porte, cambio automatico facile, due valigie più bagaglio a mano, entra dove le auto più grandi non riescono.",
      "Notre compacte la plus louée. Cinq portes, boîte auto facile, deux valises plus bagages à main, se faufile où les autres ne passent pas.",
      "Unser meistvermieteter Kleinwagen. Fünf Türen, einfache Automatik, zwei Koffer plus Handgepäck, passt wo größere Autos scheitern.",
    ),
    image: "https://images.unsplash.com/photo-1623869675781-80aa31012a5a?w=1200&auto=format&fit=crop",
    seats: 5, doors: 5, transmission: "automatic", fuelType: "gasoline", engineCC: 998,
    features: [
      ls("Bluetooth & Apple CarPlay"),
      ls("Reverse camera", "Κάμερα οπισθοπορείας", "Telecamera posteriore", "Caméra de recul", "Rückfahrkamera"),
      ls("Air conditioning", "Κλιματισμός", "Aria condizionata", "Climatisation", "Klimaanlage"),
      ls("USB-C charging", "Φόρτιση USB-C", "Ricarica USB-C", "Charge USB-C", "USB-C-Laden"),
    ],
    bestFor: [
      ls("Couples", "Ζευγάρια", "Coppie", "Couples", "Paare"),
      ls("Chora parking", "Παρκάρισμα στη Χώρα", "Parcheggio a Chora", "Stationnement à Chora", "Parken in Chora"),
      ls("Beach hopping", "Διαδρομές παραλίας", "Tour delle spiagge", "Tour des plages", "Strandtour"),
    ],
    priceShoulder: 35, priceHigh: 55, priceWeekly: 240,
  },
  {
    slug: "toyota-aygo",
    category: "cars",
    brand: "Toyota",
    model: "Aygo X",
    year: 2024,
    name: ls("Toyota Aygo X"),
    tagline: ls(
      "Tiny, thrifty, and surprisingly fun on the Filoti–Apeiranthos road",
      "Μικρό, οικονομικό και απρόσμενα διασκεδαστικό στη διαδρομή Φιλώτι–Απείρανθος",
      "Piccola, economica e sorprendentemente divertente",
      "Petite, économique et étonnamment fun",
      "Klein, sparsam und überraschend spaßig",
    ),
    description: ls(
      "Toyota's bulletproof city car with the lowest fuel bill on our fleet. Light steering, tiny turning circle, 5-star real-world reliability — the choice when the priority is cheap, easy, and stress-free.",
      "Το αξιόπιστο μικρό αστικό της Toyota με τη χαμηλότερη κατανάλωση. Ελαφρύ τιμόνι, μικρή ακτίνα στροφής, αξιόπιστο.",
      "La citadina Toyota più affidabile, consumi minimi, sterzo leggero.",
      "La citadine Toyota la plus fiable, consommation minimale, direction légère.",
      "Toyotas zuverlässiger Stadtwagen mit dem niedrigsten Verbrauch.",
    ),
    image: "https://images.unsplash.com/photo-1612825173281-9a193378527e?w=1200&auto=format&fit=crop",
    seats: 5, doors: 5, transmission: "manual", fuelType: "gasoline", engineCC: 998,
    features: [
      ls("Bluetooth"),
      ls("Air conditioning", "Κλιματισμός", "Aria condizionata", "Climatisation", "Klimaanlage"),
      ls("USB charging", "Φόρτιση USB", "Ricarica USB", "Charge USB", "USB-Laden"),
      ls("Best fuel economy", "Καλύτερη κατανάλωση", "Miglior consumo", "Meilleure conso", "Bester Verbrauch"),
    ],
    bestFor: [
      ls("Budget travellers", "Οικονομικά ταξίδια", "Viaggi economici", "Voyageurs économiques", "Sparsame Reisende"),
      ls("Solo travel", "Μονό ταξίδι", "Viaggio singolo", "Voyage solo", "Alleinreisende"),
    ],
    priceShoulder: 30, priceHigh: 50, priceWeekly: 220,
  },
  {
    slug: "fiat-panda",
    category: "cars",
    brand: "Fiat",
    model: "Panda",
    year: 2024,
    name: ls("Fiat Panda"),
    tagline: ls(
      "The Italian classic that drives Naxos like a local",
      "Ο ιταλικός κλασικός που οδηγεί στη Νάξο σαν ντόπιος",
      "Il classico italiano che guida Naxos come un locale",
      "La classique italienne qui roule comme une locale",
      "Der italienische Klassiker — fährt wie ein Einheimischer",
    ),
    description: ls(
      "Tall, square, and easy to park, the Panda gives you slightly more boot space than the i10 with the same nimble feel. Especially good if you're staying in a mountain village.",
      "Ψηλό, τετράγωνο, εύκολο στο παρκάρισμα, με λίγο μεγαλύτερο πορτμπαγκάζ από το i10.",
      "Alto, squadrato, facile da parcheggiare, bagagliaio leggermente più grande della i10.",
      "Haute, carrée, facile à garer, coffre légèrement plus grand que la i10.",
      "Hoch, kantig, leicht zu parken, etwas mehr Kofferraum als der i10.",
    ),
    image: "https://images.unsplash.com/photo-1607853202273-797f1c22a38e?w=1200&auto=format&fit=crop",
    seats: 5, doors: 5, transmission: "manual", fuelType: "gasoline", engineCC: 1242,
    features: [ls("Bluetooth"), ls("Air conditioning"), ls("Tall driving position"), ls("Roomy boot")],
    bestFor: [ls("Mountain villages"), ls("Couples"), ls("Light luggage")],
    priceShoulder: 32, priceHigh: 52, priceWeekly: 230,
  },
  {
    slug: "fiat-500-cabrio",
    category: "cars",
    brand: "Fiat",
    model: "500 Cabrio",
    year: 2024,
    name: ls("Fiat 500 Cabrio"),
    tagline: ls(
      "Drop the top — Naxos was made for this",
      "Άνοιξε την οροφή — η Νάξος είναι φτιαγμένη για αυτό",
      "Apri il tetto — Naxos è fatta per questo",
      "Ouvre le toit — Naxos est faite pour ça",
      "Dach auf — Naxos ist dafür gemacht",
    ),
    description: ls(
      "Convertible cabriolet roof, instant Instagram, and surprisingly sensible to park. The high-converter on the island in summer — book early in July and August.",
      "Πτυσσόμενη οροφή, στιγμιαία φωτογραφία, εύκολο στο παρκάρισμα. Πολύ ζητούμενο τον Ιούλιο και Αύγουστο.",
      "Tetto pieghevole, foto istantanea, facile da parcheggiare. Si esaurisce a luglio e agosto.",
      "Toit pliant, photo instantanée, facile à garer. Très demandé en juillet-août.",
      "Faltdach, sofortiges Foto, leicht zu parken. Im Juli/August schnell weg.",
    ),
    image: "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=1200&auto=format&fit=crop",
    seats: 4, doors: 3, transmission: "manual", fuelType: "gasoline", engineCC: 1242,
    features: [ls("Folding cabrio roof"), ls("Bluetooth"), ls("Air conditioning"), ls("Sport mode")],
    bestFor: [ls("Couples"), ls("Beach photos"), ls("Sunset drives")],
    priceShoulder: 55, priceHigh: 95, priceWeekly: 480,
  },
  {
    slug: "citroen-c3",
    category: "cars",
    brand: "Citroen",
    model: "C3",
    year: 2024,
    name: ls("Citroen C3"),
    tagline: ls(
      "Comfortable French compact for longer drives",
      "Άνετο γαλλικό μικρό για μεγαλύτερες διαδρομές",
      "Compatta francese comoda per lunghi viaggi",
      "Compacte française confortable pour les longs trajets",
      "Komfortable französische Kompaktklasse für längere Fahrten",
    ),
    description: ls(
      "Higher driving position, cushy ride, big boot. The pick if you're touring the whole island — Apollonas, Moutsouna, the Tragea valley — rather than staying close to base.",
      "Ψηλότερη θέση οδήγησης, άνετη ανάρτηση, μεγάλο πορτμπαγκάζ.",
      "Posizione di guida alta, sospensioni morbide, grande bagagliaio.",
      "Position de conduite haute, suspension douce, grand coffre.",
      "Höhere Sitzposition, weiche Federung, großer Kofferraum.",
    ),
    image: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=1200&auto=format&fit=crop",
    seats: 5, doors: 5, transmission: "automatic", fuelType: "gasoline", engineCC: 1199,
    features: [ls("Apple CarPlay & Android Auto"), ls("Reverse camera"), ls("Cruise control"), ls("Comfort suspension")],
    bestFor: [ls("Long drives"), ls("Families"), ls("Comfort")],
    priceShoulder: 45, priceHigh: 70, priceWeekly: 320,
  },
  {
    slug: "kia-picanto",
    category: "cars",
    brand: "Kia",
    model: "Picanto",
    year: 2024,
    name: ls("Kia Picanto"),
    tagline: ls(
      "Modern, automatic, easy on petrol",
      "Μοντέρνο, αυτόματο, οικονομικό",
      "Moderna, automatica, parca",
      "Moderne, automatique, économe",
      "Modern, Automatik, sparsam",
    ),
    description: ls(
      "A direct alternative to the i10 with similar specs. Pick whichever is available on your dates — both are excellent.",
      "Άμεση εναλλακτική του i10 με παρόμοια χαρακτηριστικά.",
      "Alternativa diretta alla i10 con specifiche simili.",
      "Alternative directe à la i10 avec des specs similaires.",
      "Direkte Alternative zum i10 mit ähnlichen Spezifikationen.",
    ),
    image: "https://images.unsplash.com/photo-1553260168-69b041873e65?w=1200&auto=format&fit=crop",
    seats: 5, doors: 5, transmission: "automatic", fuelType: "gasoline", engineCC: 998,
    features: [ls("Bluetooth"), ls("Reverse camera"), ls("Air conditioning"), ls("Cruise control")],
    bestFor: [ls("Couples"), ls("City driving")],
    priceShoulder: 35, priceHigh: 55, priceWeekly: 240,
  },
  {
    slug: "peugeot-208",
    category: "cars",
    brand: "Peugeot",
    model: "208",
    year: 2024,
    name: ls("Peugeot 208"),
    tagline: ls(
      "Sharp French hatch with the comfiest ride in its class",
      "Κοφτό γαλλικό hatchback με την πιο άνετη ανάρτηση στην κατηγορία",
      "Hatchback francese con la guida più confortevole",
      "Berline française au confort de référence",
      "Französischer Hatchback mit dem komfortabelsten Fahrwerk der Klasse",
    ),
    description: ls(
      "A step up in trim and tech: digital cluster, lane assist, automatic gearbox. Worth the upgrade if you'll be on the road most days.",
      "Αναβάθμιση σε εξοπλισμό και τεχνολογία.",
      "Un passo avanti in dotazione e tecnologia.",
      "Un cran au-dessus en équipement et technologie.",
      "Ein Plus an Ausstattung und Technik.",
    ),
    image: "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=1200&auto=format&fit=crop",
    seats: 5, doors: 5, transmission: "automatic", fuelType: "gasoline", engineCC: 1199,
    features: [ls("Digital cluster"), ls("Lane assist"), ls("Apple CarPlay"), ls("Cruise control")],
    bestFor: [ls("Couples"), ls("Tech lovers"), ls("Long days driving")],
    priceShoulder: 50, priceHigh: 75, priceWeekly: 340,
  },
  {
    slug: "suzuki-jimny",
    category: "cars",
    brand: "Suzuki",
    model: "Jimny 4x4",
    year: 2024,
    name: ls("Suzuki Jimny 4×4"),
    tagline: ls(
      "Real 4×4 for Mount Zas, Alyko dunes and the goat tracks",
      "Πραγματικό 4×4 για τον Ζα, αμμοθίνες Αλυκού και τα μονοπάτια",
      "Vero 4×4 per il Monte Zas, dune di Alyko e sentieri",
      "Vrai 4×4 pour le mont Zas, dunes d'Alyko et pistes",
      "Echtes 4×4 für Berg Zas, Alyko-Dünen und Schotterwege",
    ),
    description: ls(
      "Compact body, low-range gearbox, rear differential lock — the only car on our fleet permitted on unpaved roads. Mandatory if you want to reach the inland chapels and quiet beaches off the asphalt.",
      "Συμπαγές αμάξωμα, low-range, μπλόκο διαφορικού — το μόνο όχημα που επιτρέπεται σε χωμάτινους δρόμους.",
      "Carrozzeria compatta, ridotte, blocco differenziale — l'unico ammesso su sterrato.",
      "Carrosserie compacte, gamme courte, blocage de diff — seul autorisé hors asphalte.",
      "Kompakte Karosserie, Geländeuntersetzung, Differenzialsperre — als einziges für Schotter zugelassen.",
    ),
    image: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=1200&auto=format&fit=crop",
    seats: 4, doors: 3, transmission: "manual", fuelType: "gasoline", engineCC: 1462, fourByFour: true,
    features: [ls("True 4×4"), ls("Low-range gearbox"), ls("Allowed on dirt roads"), ls("Bluetooth")],
    bestFor: [ls("Mount Zas"), ls("Alyko dunes"), ls("Off-road chapels")],
    priceShoulder: 65, priceHigh: 95, priceWeekly: 480,
  },
  {
    slug: "dacia-duster",
    category: "cars",
    brand: "Dacia",
    model: "Duster",
    year: 2024,
    name: ls("Dacia Duster"),
    tagline: ls(
      "SUV space, surprisingly affordable",
      "Χώρος SUV σε προσιτή τιμή",
      "Spazio da SUV a prezzo accessibile",
      "Espace SUV à prix abordable",
      "SUV-Platz zum fairen Preis",
    ),
    description: ls(
      "The smart choice for a family of four with full luggage. Roomy boot, comfortable highway ride, and plenty of ground clearance for rougher village roads.",
      "Έξυπνη επιλογή για οικογένεια τεσσάρων με αποσκευές.",
      "Scelta intelligente per una famiglia di quattro con bagagli.",
      "Choix malin pour une famille de quatre avec bagages.",
      "Schlaue Wahl für eine vierköpfige Familie mit Gepäck.",
    ),
    image: "https://images.unsplash.com/photo-1568844293986-8c1a5f8e7d63?w=1200&auto=format&fit=crop",
    seats: 5, doors: 5, transmission: "manual", fuelType: "diesel", engineCC: 1461,
    features: [ls("Big boot"), ls("Roof rails"), ls("High ground clearance"), ls("Cruise control")],
    bestFor: [ls("Families"), ls("Big luggage"), ls("Highway comfort")],
    priceShoulder: 55, priceHigh: 85, priceWeekly: 380,
  },
  {
    slug: "toyota-rav4",
    category: "cars",
    brand: "Toyota",
    model: "RAV4 Hybrid",
    year: 2024,
    name: ls("Toyota RAV4 Hybrid"),
    tagline: ls(
      "Hybrid, comfortable, family-grade",
      "Υβριδικό, άνετο, οικογενειακό",
      "Ibrida, comoda, formato famiglia",
      "Hybride, confortable, format famille",
      "Hybrid, komfortabel, familientauglich",
    ),
    description: ls(
      "Our flagship family SUV. Hybrid powertrain sips fuel, plenty of room for five plus large suitcases, and surefooted on every Naxos road.",
      "Το κορυφαίο SUV οικογενείας. Υβριδικό, χώρος για πέντε και μεγάλες βαλίτσες.",
      "Il nostro SUV ammiraglia. Ibrida, spazio per cinque più valigie grandi.",
      "Notre SUV phare. Hybride, place pour cinq et valises XL.",
      "Unser SUV-Flaggschiff. Hybrid, Platz für fünf plus große Koffer.",
    ),
    image: "https://images.unsplash.com/photo-1568844293986-8c1a5f8e7d63?w=1200&auto=format&fit=crop",
    seats: 5, doors: 5, transmission: "automatic", fuelType: "hybrid", engineCC: 2487,
    features: [ls("Hybrid powertrain"), ls("Large boot"), ls("Adaptive cruise"), ls("Apple CarPlay")],
    bestFor: [ls("Families"), ls("Comfort"), ls("Hybrid efficiency")],
    priceShoulder: 75, priceHigh: 110, priceWeekly: 520,
  },
  {
    slug: "kia-sportage",
    category: "cars",
    brand: "Kia",
    model: "Sportage",
    year: 2024,
    name: ls("Kia Sportage"),
    tagline: ls(
      "Modern crossover with all the toys",
      "Μοντέρνο crossover με όλα τα έξτρα",
      "Crossover moderno con tutti gli optional",
      "Crossover moderne avec toutes les options",
      "Modernes Crossover mit voller Ausstattung",
    ),
    description: ls(
      "Big screen, premium feel, smooth automatic. A favourite for couples that want a relaxed, comfortable cruiser without going full luxury.",
      "Μεγάλη οθόνη, premium αίσθηση, ομαλό αυτόματο.",
      "Schermo grande, sensazione premium, automatico fluido.",
      "Grand écran, sensation premium, automatique fluide.",
      "Großes Display, Premium-Gefühl, weiche Automatik.",
    ),
    image: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=1200&auto=format&fit=crop",
    seats: 5, doors: 5, transmission: "automatic", fuelType: "gasoline", engineCC: 1598,
    features: [ls("12-inch screen"), ls("360 camera"), ls("Lane assist"), ls("Apple CarPlay")],
    bestFor: [ls("Comfort"), ls("Couples"), ls("Tech")],
    priceShoulder: 70, priceHigh: 105, priceWeekly: 500,
  },
  {
    slug: "citroen-berlingo-7",
    category: "cars",
    brand: "Citroen",
    model: "Berlingo 7-seater",
    year: 2024,
    name: ls("Citroen Berlingo 7-seater"),
    tagline: ls(
      "Seven seats, mountain of luggage, one easy-to-drive van",
      "Επτά θέσεις, βουνό αποσκευών, εύκολο στην οδήγηση",
      "Sette posti, montagna di bagagli, facile da guidare",
      "Sept places, montagne de bagages, facile à conduire",
      "Sieben Sitze, Berge an Gepäck, leicht zu fahren",
    ),
    description: ls(
      "Two extra rows for that family reunion. Sliding rear doors make Chora parking lots much easier with kids.",
      "Δύο επιπλέον σειρές, συρόμενες πόρτες — εύκολη πρόσβαση με παιδιά.",
      "Due file extra, porte scorrevoli — accesso facile con bambini.",
      "Deux rangs supplémentaires, portes coulissantes — accès facile avec enfants.",
      "Zwei zusätzliche Reihen, Schiebetüren — leichter Einstieg mit Kindern.",
    ),
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&auto=format&fit=crop",
    seats: 7, doors: 5, transmission: "manual", fuelType: "diesel", engineCC: 1499,
    features: [ls("7 seats"), ls("Sliding rear doors"), ls("Massive boot"), ls("Cruise control")],
    bestFor: [ls("Big families"), ls("Group travel"), ls("Heavy luggage")],
    priceShoulder: 75, priceHigh: 115, priceWeekly: 540,
  },
  // Scooters
  {
    slug: "scooter-50",
    category: "scooters",
    brand: "SYM",
    model: "Symphony 50",
    year: 2024,
    name: ls("50cc Scooter"),
    tagline: ls(
      "Car licence is enough — Naxos beach legend",
      "Αρκεί δίπλωμα Β — θρύλος της παραλίας",
      "Basta la patente B — leggenda da spiaggia",
      "Permis B suffit — légende de plage",
      "Pkw-Führerschein reicht — Strand-Klassiker",
    ),
    description: ls(
      "The 50cc class is rentable on a regular car licence (Greek/EU Category B). Top speed ~45 km/h, perfect for Chora ↔ Agios Prokopios ↔ Plaka beach runs.",
      "Η κατηγορία 50cc νοικιάζεται με δίπλωμα Β. Ιδανικό για διαδρομές παραλίας.",
      "La classe 50cc si noleggia con la patente B. Perfetto per le spiagge.",
      "Le 50cc se loue avec un permis B. Parfait pour les plages.",
      "50cc mit Pkw-Führerschein. Perfekt für Strand-Trips.",
    ),
    image: "https://images.unsplash.com/photo-1534353473418-4cfa6c56fd38?w=1200&auto=format&fit=crop",
    seats: 2, transmission: "automatic", fuelType: "gasoline", engineCC: 50,
    features: [ls("Car licence sufficient"), ls("Helmets included"), ls("Topcase included"), ls("Easy automatic")],
    bestFor: [ls("Couples"), ls("Beach hopping"), ls("First-time scooter")],
    priceShoulder: 18, priceHigh: 28, priceWeekly: 130,
  },
  {
    slug: "scooter-125",
    category: "scooters",
    brand: "Honda",
    model: "PCX 125",
    year: 2024,
    name: ls("125cc Scooter"),
    tagline: ls(
      "Full-island reach with motorbike licence",
      "Φτάνει παντού — με δίπλωμα μοτο",
      "Raggio completo dell'isola — con patente moto",
      "Toute l'île — permis moto requis",
      "Inselweite Reichweite — Motorradführerschein nötig",
    ),
    description: ls(
      "Motorbike licence (A1/A2/A) required. Comfortable on the Filoti and Apollonas roads, easy two-up cruiser.",
      "Απαιτείται δίπλωμα μοτο (A1/A2/A). Άνετο για Φιλώτι και Απόλλωνα.",
      "Patente moto richiesta. Comodo per Filoti e Apollonas.",
      "Permis moto requis. Confortable pour Filoti et Apollonas.",
      "Motorradschein erforderlich. Bequem für Filoti und Apollonas.",
    ),
    image: "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=1200&auto=format&fit=crop",
    seats: 2, transmission: "automatic", fuelType: "gasoline", engineCC: 125,
    features: [ls("Motorbike licence required"), ls("2 helmets included"), ls("Topcase included")],
    bestFor: [ls("Two-up touring"), ls("Mountain villages"), ls("Daily commuting")],
    priceShoulder: 25, priceHigh: 38, priceWeekly: 180,
  },
  {
    slug: "scooter-200",
    category: "scooters",
    brand: "Yamaha",
    model: "X-Max 200",
    year: 2024,
    name: ls("200cc Scooter"),
    tagline: ls(
      "Highway-ready, the touring favourite",
      "Έτοιμο για ταχύτητα, αγαπημένο touring",
      "Pronto per le superstrade, preferito turismo",
      "Prêt voie rapide, favori touring",
      "Schnellstraßentauglich, Touring-Favorit",
    ),
    description: ls(
      "Bigger engine, bigger comfort, room for serious panniers. The choice for Chora→Apollonas in one go.",
      "Μεγαλύτερος κινητήρας, περισσότερη άνεση.",
      "Motore più grande, più comfort.",
      "Plus gros moteur, plus de confort.",
      "Größerer Motor, mehr Komfort.",
    ),
    image: "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=1200&auto=format&fit=crop",
    seats: 2, transmission: "automatic", fuelType: "gasoline", engineCC: 200,
    features: [ls("Highway capable"), ls("Comfortable two-up"), ls("Topcase included"), ls("ABS brakes")],
    bestFor: [ls("Touring"), ls("Long distances"), ls("Two-up comfort")],
    priceShoulder: 32, priceHigh: 48, priceWeekly: 220,
  },
  {
    slug: "vespa-primavera",
    category: "scooters",
    brand: "Piaggio",
    model: "Vespa Primavera 125",
    year: 2024,
    name: ls("Vespa Primavera 125"),
    tagline: ls(
      "Italian style, Greek island sunshine",
      "Ιταλικό στυλ, ελληνικός ήλιος",
      "Stile italiano, sole greco",
      "Style italien, soleil grec",
      "Italienischer Stil, griechische Sonne",
    ),
    description: ls(
      "Iconic. Photogenic. Drives like a dream. Motorbike licence (A1+) required.",
      "Εμβληματικό. Φωτογενές. Χρειάζεται δίπλωμα μοτο.",
      "Iconica. Fotogenica. Patente moto richiesta.",
      "Iconique. Photogénique. Permis moto requis.",
      "Ikonisch. Fotogen. Motorradschein nötig.",
    ),
    image: "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=1200&auto=format&fit=crop",
    seats: 2, transmission: "automatic", fuelType: "gasoline", engineCC: 125,
    features: [ls("Motorbike licence required"), ls("Iconic Vespa frame"), ls("ABS"), ls("Topcase")],
    bestFor: [ls("Couples"), ls("Photo trips"), ls("Style")],
    priceShoulder: 35, priceHigh: 55, priceWeekly: 250,
  },
  // ATV / Quads
  {
    slug: "atv-150",
    category: "atv-quad",
    brand: "TGB",
    model: "Blade 150",
    year: 2024,
    name: ls("ATV 150cc"),
    tagline: ls(
      "Entry-level quad, car licence accepted",
      "Αρχάριο γουρουνάκι, με δίπλωμα Β",
      "Quad entry-level, patente B",
      "Quad débutant, permis B",
      "Einsteiger-Quad, Pkw-Führerschein",
    ),
    description: ls(
      "Light, automatic, room for two. The first-quad choice on Naxos.",
      "Ελαφρύ, αυτόματο, για δύο.",
      "Leggero, automatico, per due.",
      "Léger, auto, pour deux.",
      "Leicht, Automatik, für zwei.",
    ),
    image: "https://images.unsplash.com/photo-1612385032055-1a1d8c2f3e4d?w=1200&auto=format&fit=crop",
    seats: 2, transmission: "automatic", fuelType: "gasoline", engineCC: 150,
    features: [ls("Car licence sufficient"), ls("2 helmets"), ls("Storage box"), ls("Easy automatic")],
    bestFor: [ls("First-time quad"), ls("Couples"), ls("Beach trips")],
    priceShoulder: 35, priceHigh: 55, priceWeekly: 240,
  },
  {
    slug: "atv-300",
    category: "atv-quad",
    brand: "Kymco",
    model: "MXU 300",
    year: 2024,
    name: ls("ATV 300cc"),
    tagline: ls(
      "More power, more comfort",
      "Περισσότερη ισχύς, περισσότερη άνεση",
      "Più potenza, più comfort",
      "Plus de puissance, plus de confort",
      "Mehr Leistung, mehr Komfort",
    ),
    description: ls(
      "Step up from the 150 — better seat, larger fuel tank, more two-up power.",
      "Αναβάθμιση από το 150 — καλύτερη θέση, μεγαλύτερη δεξαμενή.",
      "Un passo oltre il 150 — sedile migliore, serbatoio più grande.",
      "Un cran au-dessus du 150 — meilleure selle, plus grand réservoir.",
      "Eine Stufe über dem 150 — besserer Sitz, größerer Tank.",
    ),
    image: "https://images.unsplash.com/photo-1612385032055-1a1d8c2f3e4d?w=1200&auto=format&fit=crop",
    seats: 2, transmission: "automatic", fuelType: "gasoline", engineCC: 300,
    features: [ls("Car licence sufficient"), ls("2 helmets"), ls("Storage box"), ls("Bigger seat")],
    bestFor: [ls("Two-up touring"), ls("Longer days")],
    priceShoulder: 45, priceHigh: 65, priceWeekly: 290,
  },
  {
    slug: "atv-500",
    category: "atv-quad",
    brand: "CFMoto",
    model: "CForce 500",
    year: 2024,
    name: ls("ATV 500cc"),
    tagline: ls(
      "Real off-road grunt — for the back tracks",
      "Πραγματικό off-road — για τα μονοπάτια",
      "Vera potenza off-road — per i sentieri",
      "Vraie puissance off-road — pour les pistes",
      "Echte Off-Road-Power — für Schotterwege",
    ),
    description: ls(
      "4×4 quad with full off-road capability. Recommended only for experienced quad riders.",
      "Quad 4×4 με πλήρη off-road ικανότητα.",
      "Quad 4×4 con piene capacità off-road.",
      "Quad 4×4 avec pleines capacités off-road.",
      "4×4-Quad mit voller Geländefähigkeit.",
    ),
    image: "https://images.unsplash.com/photo-1612385032055-1a1d8c2f3e4d?w=1200&auto=format&fit=crop",
    seats: 2, transmission: "automatic", fuelType: "gasoline", engineCC: 500, fourByFour: true,
    features: [ls("4×4"), ls("Off-road capable"), ls("Winch"), ls("Storage box")],
    bestFor: [ls("Experienced riders"), ls("Off-road")],
    priceShoulder: 60, priceHigh: 90, priceWeekly: 420,
  },
  {
    slug: "atv-800",
    category: "atv-quad",
    brand: "CFMoto",
    model: "CForce 800",
    year: 2024,
    name: ls("ATV 800cc"),
    tagline: ls(
      "Big-bore quad — top of the line",
      "Μεγάλο γουρούνι — κορυφή",
      "Quad maxi — top di gamma",
      "Quad maxi — haut de gamme",
      "Großvolumen-Quad — Spitzenmodell",
    ),
    description: ls(
      "Our most powerful quad. Two-up, 4×4, fully equipped. For experienced riders only.",
      "Το πιο ισχυρό μας γουρούνι.",
      "Il nostro quad più potente.",
      "Notre quad le plus puissant.",
      "Unser stärkstes Quad.",
    ),
    image: "https://images.unsplash.com/photo-1612385032055-1a1d8c2f3e4d?w=1200&auto=format&fit=crop",
    seats: 2, transmission: "automatic", fuelType: "gasoline", engineCC: 800, fourByFour: true,
    features: [ls("4×4"), ls("Power steering"), ls("Winch"), ls("Big storage")],
    bestFor: [ls("Experienced riders"), ls("Hard off-road")],
    priceShoulder: 80, priceHigh: 120, priceWeekly: 560,
  },
  // Buggies
  {
    slug: "buggy-2",
    category: "buggy",
    brand: "Polaris",
    model: "RZR 2-seat",
    year: 2024,
    name: ls("Polaris RZR 2-seat"),
    tagline: ls(
      "Open-air rocket, Naxos's best photo op",
      "Ανοιχτό αμάξι — η καλύτερη φωτογραφία",
      "Razzo a cielo aperto — la foto migliore",
      "Fusée à ciel ouvert — la meilleure photo",
      "Open-Air-Rakete — das beste Foto",
    ),
    description: ls(
      "Two seats, full roll cage, harness belts. Allowed on tarmac plus the unpaved roads to Alyko, Pyrgaki and Mikri Vigla. Car licence accepted.",
      "Δύο θέσεις, πλήρες roll cage, ζώνες πρόσδεσης. Επιτρέπεται σε άσφαλτο και χωμάτινους δρόμους.",
      "Due posti, roll cage completo. Ammesso su asfalto e sterrato.",
      "Deux places, arceau complet. Autorisé sur asphalte et pistes.",
      "Zwei Sitze, voller Überrollkäfig. Auf Asphalt und Schotter erlaubt.",
    ),
    image: "https://images.unsplash.com/photo-1604147495798-57beb5d6af73?w=1200&auto=format&fit=crop",
    seats: 2, transmission: "automatic", fuelType: "gasoline", engineCC: 999, fourByFour: true,
    features: [ls("Roll cage"), ls("Harness belts"), ls("4×4"), ls("Off-road tyres")],
    bestFor: [ls("Adventure couples"), ls("Alyko dunes"), ls("Photo days")],
    priceShoulder: 110, priceHigh: 150, priceWeekly: 850,
  },
  {
    slug: "buggy-4",
    category: "buggy",
    brand: "Polaris",
    model: "RZR 4-seat",
    year: 2024,
    name: ls("Polaris RZR 4-seat"),
    tagline: ls(
      "Four-seat buggy — the family adventure machine",
      "Τετραθέσιο buggy — οικογενειακή περιπέτεια",
      "Buggy a 4 posti — avventura in famiglia",
      "Buggy 4 places — aventure en famille",
      "4-Sitzer-Buggy — Familienabenteuer",
    ),
    description: ls(
      "Bigger sibling — same off-road chops, two extra seats. The headline rental for adventure-minded families.",
      "Μεγαλύτερος αδελφός με δύο επιπλέον θέσεις.",
      "Fratello maggiore con due posti in più.",
      "Frère ainé avec deux sièges en plus.",
      "Großer Bruder mit zwei zusätzlichen Sitzen.",
    ),
    image: "https://images.unsplash.com/photo-1604147495798-57beb5d6af73?w=1200&auto=format&fit=crop",
    seats: 4, transmission: "automatic", fuelType: "gasoline", engineCC: 999, fourByFour: true,
    features: [ls("4 seats"), ls("Roll cage"), ls("Harness belts"), ls("4×4")],
    bestFor: [ls("Adventure families"), ls("Off-road")],
    priceShoulder: 140, priceHigh: 190, priceWeekly: 1080,
  },
];

export const VEHICLES_BY_SLUG = Object.fromEntries(VEHICLES.map((v) => [v.slug, v]));

export function vehiclesByCategory(category: Vehicle["category"]) {
  return VEHICLES.filter((v) => v.category === category);
}
