import type { Vehicle } from "@/types/content";

/**
 * The fleet, reconciled against the live booking engine on 2026-08-23
 * (fastmotorentalnaxos.cosmicbooker.com).
 *
 * Specs, booking group and luggage counts for every `bookable: true` vehicle
 * come from that engine, which is the operator's own source of truth. Prices
 * are deliberately absent on the vehicles the engine does not publish a rate
 * card for in this repo — see the `priceShoulder` note in @/types/content.
 *
 * Eight vehicles are marked `bookable: false`. They are on the site but the
 * engine does not offer them, so they must not present themselves as
 * reservable. Their pages stay live because several hold search demand
 * (/fleet/cars/suzuki-jimny earned 9 clicks and 58 impressions last quarter);
 * retiring them is an owner decision, not a code one.
 */

const ls = (en: string, el?: string, it?: string, fr?: string, de?: string) => ({
  en, el: el ?? en, it: it ?? en, fr: fr ?? en, de: de ?? en,
});

export const VEHICLES: Vehicle[] = [
  {
    slug: "hyundai-i10",
    category: "cars",
    brand: "Hyundai",
    model: "i10",
    year: 2024,
    name: ls("Hyundai i10"),
    tagline: ls(
      "The Naxos parking champion  -  small enough for Chora alleys",
      "Ο πρωταθλητής του παρκαρίσματος στα στενά της Χώρας",
      "Campione del parcheggio a Chora",
      "Championne du stationnement dans les ruelles de Chora",
      "Parkmeister in den engen Gassen von Chora",
    ),
    description: ls(
      "Our most-rented compact. Five doors, easy automatic shift, fits two suitcases plus carry-ons, and slips into Chora parking spots that turn larger cars away. A favourite for couples and small families spending most days at the beach.",
      "Το πιο δημοφιλές μικρό αυτοκίνητο του στόλου μας. Πέντε πόρτες, αυτόματο κιβώτιο, χωρητικότητα για δύο βαλίτσες και χειραποσκευές, παρκάρει εκεί που τα μεγαλύτερα αυτοκίνητα αδυνατούν. Ιδανικό για ζευγάρια και μικρές οικογένειες που περνούν τις περισσότερες ημέρες στις παραλίες.",
      "La nostra compatta più noleggiata. Cinque porte, cambio automatico facile, due valigie più bagaglio a mano, entra dove le auto più grandi non riescono.",
      "Notre compacte la plus louée. Cinq portes, boîte auto facile, deux valises plus bagages à main, se faufile où les autres ne passent pas.",
      "Unser meistvermieteter Kleinwagen. Fünf Türen, einfache Automatik, zwei Koffer plus Handgepäck, passt wo größere Autos scheitern.",
    ),
    image: "/images/fleet/hyundai-i10.jpg",
    seats: 5, doors: 5, transmission: "manual", fuelType: "gasoline", engineCC: 1000,
    bookingGroup: "B", luggageLarge: 2, luggageSmall: 2, bookable: true,
    features: [
      ls("Bluetooth & Apple CarPlay"),
      ls("Reverse camera", "Κάμερα οπισθοπορείας", "Telecamera posteriore", "Caméra de recul", "Rückfahrkamera"),
      ls("Air conditioning", "Κλιματισμός", "Aria condizionata", "Climatisation", "Klimaanlage"),
      ls("USB-C charging", "Φόρτιση USB-C", "Ricarica USB-C", "Charge USB-C", "USB-C-Laden"),
    ],
    bestFor: [
      ls("Couples", "Ζευγάρια", "Coppie", "Couples", "Paare"),
      ls("Chora parking", "Παρκάρισμα στη Χώρα", "Parcheggio a Chora", "Stationnement à Chora", "Parken in Chora"),
      ls("Beach hopping", "Διαδρομές παραλίας", "Tour delle spiagge", "Tour des plages", "Strandtour"),
    ],
    priceShoulder: 35, priceHigh: 55, priceWeekly: 240,
  },
  {
    slug: "toyota-aygo",
    category: "cars",
    brand: "Toyota",
    model: "Aygo X",
    year: 2024,
    name: ls("Toyota Aygo X"),
    tagline: ls(
      "Tiny, thrifty, and surprisingly fun on the Filoti–Apeiranthos road",
      "Μικρό, οικονομικό και απροσδόκητα ευχάριστο στη διαδρομή Φιλώτι–Απείρανθος",
      "Piccola, economica e sorprendentemente divertente",
      "Petite, économique et étonnamment fun",
      "Klein, sparsam und überraschend spaßig",
    ),
    description: ls(
      "Toyota's bulletproof city car with the lowest fuel bill on our fleet. Light steering, tiny turning circle, 5-star real-world reliability  -  the choice when the priority is cheap, easy, and stress-free.",
      "Το αξιόπιστο αστικό της Toyota με τη χαμηλότερη κατανάλωση στον στόλο μας. Ελαφρύ τιμόνι, μικρή διάμετρος στροφής και πραγματική αξιοπιστία πέντε αστέρων  -  η ιδανική επιλογή όταν θέλετε κάτι οικονομικό, εύκολο και χωρίς άγχος.",
      "La citadina Toyota più affidabile, consumi minimi, sterzo leggero.",
      "La citadine Toyota la plus fiable, consommation minimale, direction légère.",
      "Toyotas zuverlässiger Stadtwagen mit dem niedrigsten Verbrauch.",
    ),
    image: "/images/fleet/toyota-aygo.jpg",
    seats: 4, doors: 3, transmission: "manual", fuelType: "gasoline", engineCC: 1000,
    bookingGroup: "A", luggageLarge: 1, luggageSmall: 2, bookable: true,
    features: [
      ls("Bluetooth"),
      ls("Air conditioning", "Κλιματισμός", "Aria condizionata", "Climatisation", "Klimaanlage"),
      ls("USB charging", "Φόρτιση USB", "Ricarica USB", "Charge USB", "USB-Laden"),
      ls("Best fuel economy", "Καλύτερη κατανάλωση", "Miglior consumo", "Meilleure conso", "Bester Verbrauch"),
    ],
    bestFor: [
      ls("Budget travellers", "Οικονομικά ταξίδια", "Viaggi economici", "Voyageurs économiques", "Sparsame Reisende"),
      ls("Solo travel", "Μονό ταξίδι", "Viaggio singolo", "Voyage solo", "Alleinreisende"),
    ],
    priceShoulder: 30, priceHigh: 50, priceWeekly: 220,
  },
  {
    slug: "fiat-panda",
    category: "cars",
    brand: "Fiat",
    model: "Panda",
    year: 2024,
    name: ls("Fiat Panda"),
    tagline: ls(
      "The Italian classic that drives Naxos like a local",
      "Ο ιταλικός κλασικός που κινείται στη Νάξο σαν ντόπιος",
      "Il classico italiano che guida Naxos come un locale",
      "La classique italienne qui roule comme une locale",
      "Der italienische Klassiker  -  fährt wie ein Einheimischer",
    ),
    description: ls(
      "Tall, square, and easy to park, the Panda gives you slightly more boot space than the i10 with the same nimble feel. Especially good if you're staying in a mountain village.",
      "Ψηλό, τετράγωνο και εύκολο στο παρκάρισμα, με λίγο μεγαλύτερο πορτμπαγκάζ από το i10 και την ίδια ευελιξία. Εξαιρετική επιλογή αν διαμένετε σε ορεινό χωριό.",
      "Alto, squadrato, facile da parcheggiare, bagagliaio leggermente più grande della i10.",
      "Haute, carrée, facile à garer, coffre légèrement plus grand que la i10.",
      "Hoch, kantig, leicht zu parken, etwas mehr Kofferraum als der i10.",
    ),
    image: "/images/fleet/fiat-panda.jpg",
    seats: 5, doors: 5, transmission: "manual", fuelType: "diesel", engineCC: 1300,
    bookingGroup: "Β", luggageLarge: 2, luggageSmall: 3, bookable: true,
    features: [ls("Bluetooth"), ls("Air conditioning"), ls("Tall driving position"), ls("Roomy boot")],
    bestFor: [ls("Mountain villages"), ls("Couples"), ls("Light luggage")],
    priceShoulder: 32, priceHigh: 52, priceWeekly: 230,
  },
  {
    slug: "fiat-500-cabrio",
    category: "cars",
    brand: "Fiat",
    model: "500 Cabrio",
    year: 2024,
    name: ls("Fiat 500 Cabrio"),
    tagline: ls(
      "Drop the top  -  Naxos was made for this",
      "Ανοίξτε την οροφή  -  η Νάξος είναι πλασμένη γι' αυτό",
      "Apri il tetto  -  Naxos è fatta per questo",
      "Ouvre le toit  -  Naxos est faite pour ça",
      "Dach auf  -  Naxos ist dafür gemacht",
    ),
    description: ls(
      "Convertible cabriolet roof, instant Instagram, and surprisingly sensible to park. The high-converter on the island in summer  -  book early in July and August.",
      "Πτυσσόμενη οροφή cabriolet, άμεση φωτογραφία για το Instagram και ευχάριστη έκπληξη στο παρκάρισμα. Ο μεγαλύτερος best-seller του καλοκαιριού  -  προτείνουμε έγκαιρη κράτηση για Ιούλιο και Αύγουστο.",
      "Tetto pieghevole, foto istantanea, facile da parcheggiare. Si esaurisce a luglio e agosto.",
      "Toit pliant, photo instantanée, facile à garer. Très demandé en juillet-août.",
      "Faltdach, sofortiges Foto, leicht zu parken. Im Juli/August schnell weg.",
    ),
    image: "/images/fleet/peugeot-208-a.png",
    seats: 4, doors: 3, transmission: "manual", fuelType: "gasoline", engineCC: 1242,
    bookable: false,
    features: [ls("Folding cabrio roof"), ls("Bluetooth"), ls("Air conditioning"), ls("Sport mode")],
    bestFor: [ls("Couples"), ls("Beach photos"), ls("Sunset drives")],
    priceShoulder: 55, priceHigh: 95, priceWeekly: 480,
  },
  {
    slug: "citroen-c3",
    category: "cars",
    brand: "Citroen",
    model: "C3",
    year: 2024,
    name: ls("Citroen C3"),
    tagline: ls(
      "Comfortable French compact for longer drives",
      "Άνετο γαλλικό compact για μεγαλύτερες διαδρομές",
      "Compatta francese comoda per lunghi viaggi",
      "Compacte française confortable pour les longs trajets",
      "Komfortable französische Kompaktklasse für längere Fahrten",
    ),
    description: ls(
      "Higher driving position, cushy ride, big boot. The pick if you're touring the whole island  -  Apollonas, Moutsouna, the Tragea valley  -  rather than staying close to base.",
      "Ψηλότερη θέση οδήγησης, μαλακή ανάρτηση και ευρύχωρο πορτμπαγκάζ. Η σωστή επιλογή αν σκοπεύετε να εξερευνήσετε όλο το νησί  -  Απόλλωνα, Μουτσούνα, την κοιλάδα της Τραγαίας  -  και όχι μόνο τη γύρω περιοχή της βάσης σας.",
      "Posizione di guida alta, sospensioni morbide, grande bagagliaio.",
      "Position de conduite haute, suspension douce, grand coffre.",
      "Höhere Sitzposition, weiche Federung, großer Kofferraum.",
    ),
    image: "/images/fleet/c3-aircross.jpg",
    seats: 5, doors: 5, transmission: "automatic", fuelType: "gasoline", engineCC: 1199,
    bookable: false,
    features: [ls("Apple CarPlay & Android Auto"), ls("Reverse camera"), ls("Cruise control"), ls("Comfort suspension")],
    bestFor: [ls("Long drives"), ls("Families"), ls("Comfort")],
    priceShoulder: 45, priceHigh: 70, priceWeekly: 320,
  },
  {
    slug: "kia-picanto",
    category: "cars",
    brand: "Kia",
    model: "Picanto",
    year: 2024,
    name: ls("Kia Picanto"),
    tagline: ls(
      "Modern, automatic, easy on petrol",
      "Μοντέρνο, αυτόματο, οικονομικό στην κατανάλωση",
      "Moderna, automatica, parca",
      "Moderne, automatique, économe",
      "Modern, Automatik, sparsam",
    ),
    description: ls(
      "A direct alternative to the i10 with similar specs. Pick whichever is available on your dates  -  both are excellent.",
      "Άμεση εναλλακτική του Hyundai i10 με αντίστοιχα χαρακτηριστικά. Επιλέξτε όποιο είναι διαθέσιμο στις ημερομηνίες σας  -  και τα δύο είναι εξαιρετικά.",
      "Alternativa diretta alla i10 con specifiche simili.",
      "Alternative directe à la i10 avec des specs similaires.",
      "Direkte Alternative zum i10 mit ähnlichen Spezifikationen.",
    ),
    image: "/images/fleet/suzuki-celerio.png",
    seats: 5, doors: 5, transmission: "automatic", fuelType: "gasoline", engineCC: 998,
    bookable: false,
    features: [ls("Bluetooth"), ls("Reverse camera"), ls("Air conditioning"), ls("Cruise control")],
    bestFor: [ls("Couples"), ls("City driving")],
    priceShoulder: 35, priceHigh: 55, priceWeekly: 240,
  },
  {
    slug: "peugeot-208",
    category: "cars",
    brand: "Peugeot",
    model: "208",
    year: 2024,
    name: ls("Peugeot 208"),
    tagline: ls(
      "Sharp French hatch with the comfiest ride in its class",
      "Δυναμικό γαλλικό hatchback με την πιο άνετη ανάρτηση της κατηγορίας",
      "Hatchback francese con la guida più confortevole",
      "Berline française au confort de référence",
      "Französischer Hatchback mit dem komfortabelsten Fahrwerk der Klasse",
    ),
    description: ls(
      "A step up in trim and tech: digital cluster, lane assist, automatic gearbox. Worth the upgrade if you'll be on the road most days.",
      "Σημαντική αναβάθμιση σε εξοπλισμό και τεχνολογία: ψηφιακός πίνακας οργάνων, υποβοήθηση λωρίδας, αυτόματο κιβώτιο. Αξίζει την επιλογή αν πρόκειται να βρίσκεστε στον δρόμο τις περισσότερες ημέρες.",
      "Un passo avanti in dotazione e tecnologia.",
      "Un cran au-dessus en équipement et technologie.",
      "Ein Plus an Ausstattung und Technik.",
    ),
    image: "/images/fleet/peugeot-208-a.png",
    seats: 5, doors: 5, transmission: "manual", fuelType: "gasoline", engineCC: 1200,
    bookingGroup: "C", luggageLarge: 3, luggageSmall: 4, bookable: true,
    features: [ls("Digital cluster"), ls("Lane assist"), ls("Apple CarPlay"), ls("Cruise control")],
    bestFor: [ls("Couples"), ls("Tech lovers"), ls("Long days driving")],
    priceShoulder: 50, priceHigh: 75, priceWeekly: 340,
  },
  {
    slug: "suzuki-jimny",
    category: "cars",
    brand: "Suzuki",
    model: "Jimny 4x4",
    year: 2024,
    name: ls("Suzuki Jimny 4×4"),
    tagline: ls(
      "Real 4×4 for Mount Zas, Alyko dunes and the goat tracks",
      "Αυθεντικό 4×4 για τον Ζα, τις αμμοθίνες του Αλυκού και τα μονοπάτια",
      "Vero 4×4 per il Monte Zas, dune di Alyko e sentieri",
      "Vrai 4×4 pour le mont Zas, dunes d'Alyko et pistes",
      "Echtes 4×4 für Berg Zas, Alyko-Dünen und Schotterwege",
    ),
    description: ls(
      "Compact body, low-range gearbox, rear differential lock  -  the only car on our fleet permitted on unpaved roads. Mandatory if you want to reach the inland chapels and quiet beaches off the asphalt.",
      "Συμπαγές αμάξωμα, κιβώτιο μειωτήρα και κλείδωμα διαφορικού στον πίσω άξονα  -  το μόνο όχημα του στόλου που επιτρέπεται σε χωματόδρομους. Απαραίτητο αν θέλετε να φτάσετε στα ορεινά εξωκλήσια και στις απομονωμένες παραλίες εκτός ασφάλτου.",
      "Carrozzeria compatta, ridotte, blocco differenziale  -  l'unico ammesso su sterrato.",
      "Carrosserie compacte, gamme courte, blocage de diff  -  seul autorisé hors asphalte.",
      "Kompakte Karosserie, Geländeuntersetzung, Differenzialsperre  -  als einziges für Schotter zugelassen.",
    ),
    image: "/images/fleet/jeep-renegade.png",
    seats: 4, doors: 3, transmission: "manual", fuelType: "gasoline", engineCC: 1462, fourByFour: true,
    bookable: false,
    features: [ls("True 4×4"), ls("Low-range gearbox"), ls("Allowed on dirt roads"), ls("Bluetooth")],
    bestFor: [ls("Mount Zas"), ls("Alyko dunes"), ls("Off-road chapels")],
    priceShoulder: 65, priceHigh: 95, priceWeekly: 480,
  },
  {
    slug: "dacia-duster",
    category: "cars",
    brand: "Dacia",
    model: "Duster",
    year: 2024,
    name: ls("Dacia Duster"),
    tagline: ls(
      "SUV space, surprisingly affordable",
      "Χώρος επιπέδου SUV σε προσιτή τιμή",
      "Spazio da SUV a prezzo accessibile",
      "Espace SUV à prix abordable",
      "SUV-Platz zum fairen Preis",
    ),
    description: ls(
      "The smart choice for a family of four with full luggage. Roomy boot, comfortable highway ride, and plenty of ground clearance for rougher village roads.",
      "Έξυπνη επιλογή για τετραμελή οικογένεια με πλήρεις αποσκευές. Ευρύχωρο πορτμπαγκάζ, άνετη συμπεριφορά σε αυτοκινητόδρομο και ικανοποιητική απόσταση από το έδαφος για τους πιο τραχείς δρόμους των χωριών.",
      "Scelta intelligente per una famiglia di quattro con bagagli.",
      "Choix malin pour une famille de quatre avec bagages.",
      "Schlaue Wahl für eine vierköpfige Familie mit Gepäck.",
    ),
    image: "/images/fleet/suvseatarona.jpg",
    seats: 5, doors: 5, transmission: "manual", fuelType: "diesel", engineCC: 1461,
    bookable: false,
    features: [ls("Big boot"), ls("Roof rails"), ls("High ground clearance"), ls("Cruise control")],
    bestFor: [ls("Families"), ls("Big luggage"), ls("Highway comfort")],
    priceShoulder: 55, priceHigh: 85, priceWeekly: 380,
  },
  {
    slug: "toyota-rav4",
    category: "cars",
    brand: "Toyota",
    model: "RAV4 Hybrid",
    year: 2024,
    name: ls("Toyota RAV4 Hybrid"),
    tagline: ls(
      "Hybrid, comfortable, family-grade",
      "Υβριδικό, άνετο, ιδανικό για οικογένειες",
      "Ibrida, comoda, formato famiglia",
      "Hybride, confortable, format famille",
      "Hybrid, komfortabel, familientauglich",
    ),
    description: ls(
      "Our flagship family SUV. Hybrid powertrain sips fuel, plenty of room for five plus large suitcases, and surefooted on every Naxos road.",
      "Το κορυφαίο οικογενειακό SUV του στόλου μας. Υβριδικό σύστημα κίνησης με χαμηλή κατανάλωση, άνετος χώρος για πέντε επιβάτες και μεγάλες βαλίτσες, σταθερή συμπεριφορά σε κάθε δρόμο της Νάξου.",
      "Il nostro SUV ammiraglia. Ibrida, spazio per cinque più valigie grandi.",
      "Notre SUV phare. Hybride, place pour cinq et valises XL.",
      "Unser SUV-Flaggschiff. Hybrid, Platz für fünf plus große Koffer.",
    ),
    image: "/images/fleet/mg-zs-4-768x576.png",
    seats: 5, doors: 5, transmission: "automatic", fuelType: "hybrid", engineCC: 2487,
    bookable: false,
    features: [ls("Hybrid powertrain"), ls("Large boot"), ls("Adaptive cruise"), ls("Apple CarPlay")],
    bestFor: [ls("Families"), ls("Comfort"), ls("Hybrid efficiency")],
    priceShoulder: 75, priceHigh: 110, priceWeekly: 520,
  },
  {
    slug: "kia-sportage",
    category: "cars",
    brand: "Kia",
    model: "Sportage",
    year: 2024,
    name: ls("Kia Sportage"),
    tagline: ls(
      "Modern crossover with all the toys",
      "Μοντέρνο crossover με πλήρη εξοπλισμό",
      "Crossover moderno con tutti gli optional",
      "Crossover moderne avec toutes les options",
      "Modernes Crossover mit voller Ausstattung",
    ),
    description: ls(
      "Big screen, premium feel, smooth automatic. A favourite for couples that want a relaxed, comfortable cruiser without going full luxury.",
      "Μεγάλη οθόνη infotainment, premium αίσθηση και ομαλή λειτουργία του αυτόματου κιβωτίου. Αγαπημένη επιλογή για ζευγάρια που αναζητούν χαλαρή, άνετη οδήγηση χωρίς να μπουν σε κατηγορία πολυτελείας.",
      "Schermo grande, sensazione premium, automatico fluido.",
      "Grand écran, sensation premium, automatique fluide.",
      "Großes Display, Premium-Gefühl, weiche Automatik.",
    ),
    image: "/images/fleet/suvseatarona.jpg",
    seats: 5, doors: 5, transmission: "automatic", fuelType: "gasoline", engineCC: 1598,
    bookable: false,
    features: [ls("12-inch screen"), ls("360 camera"), ls("Lane assist"), ls("Apple CarPlay")],
    bestFor: [ls("Comfort"), ls("Couples"), ls("Tech")],
    priceShoulder: 70, priceHigh: 105, priceWeekly: 500,
  },
  {
    slug: "citroen-berlingo-7",
    category: "cars",
    brand: "Citroen",
    model: "Berlingo 7-seater",
    year: 2024,
    name: ls("Citroen Berlingo 7-seater"),
    tagline: ls(
      "Seven seats, mountain of luggage, one easy-to-drive van",
      "Επτά θέσεις, βουνό αποσκευών και εύκολη οδήγηση",
      "Sette posti, montagna di bagagli, facile da guidare",
      "Sept places, montagne de bagages, facile à conduire",
      "Sieben Sitze, Berge an Gepäck, leicht zu fahren",
    ),
    description: ls(
      "Two extra rows for that family reunion. Sliding rear doors make Chora parking lots much easier with kids.",
      "Δύο επιπλέον σειρές καθισμάτων για οικογενειακές συναντήσεις. Οι συρόμενες πίσω πόρτες κάνουν τα στενά πάρκινγκ της Χώρας πολύ πιο εύκολα με μικρά παιδιά.",
      "Due file extra, porte scorrevoli  -  accesso facile con bambini.",
      "Deux rangs supplémentaires, portes coulissantes  -  accès facile avec enfants.",
      "Zwei zusätzliche Reihen, Schiebetüren  -  leichter Einstieg mit Kindern.",
    ),
    image: "/images/fleet/baleno.jpg",
    seats: 7, doors: 5, transmission: "manual", fuelType: "diesel", engineCC: 1499,
    bookable: false,
    features: [ls("7 seats"), ls("Sliding rear doors"), ls("Massive boot"), ls("Cruise control")],
    bestFor: [ls("Big families"), ls("Group travel"), ls("Heavy luggage")],
    priceShoulder: 75, priceHigh: 115, priceWeekly: 540,
  },
  {
    slug: "dacia-sandero-stepway",
    category: "cars",
    brand: "Dacia",
    model: "Sandero Stepway",
    year: 2024,
    name: ls("Dacia Sandero Stepway Automatic"),
    tagline: ls("Raised automatic hatch for the mountain roads", "Ψηλό αυτόματο για τους ορεινούς δρόμους"),
    description: ls("The largest automatic in the fleet and the easiest choice for the Apeiranthos and Apollonas routes. Raised ride height copes with the rougher village approaches, and the boot takes three large cases without folding a seat.", "Το μεγαλύτερο αυτόματο του στόλου και η πιο άνετη επιλογή για τις διαδρομές προς Απείρανθο και Απόλλωνα. Το αυξημένο ύψος βοηθά στους πιο τραχείς δρόμους των χωριών, και το πορτμπαγκάζ παίρνει τρεις μεγάλες βαλίτσες χωρίς να διπλώσετε κάθισμα."),
    image: "/images/fleet/dacia-sandero-stepway.jpg",
    seats: 5, doors: 5, transmission: "automatic", fuelType: "gasoline", engineCC: 1000,
    bookingGroup: "DA", luggageLarge: 3, luggageSmall: 5, bookable: true,
    features: [
      ls("Air conditioning", "Κλιματισμός"),
      ls("Bluetooth", "Bluetooth"),
      ls("USB charging", "Φόρτιση USB"),
    ],
    bestFor: [
      ls("Mountain villages", "Ορεινά χωριά"),
      ls("Families", "Οικογένειες"),
      ls("Long island days", "Μεγάλες διαδρομές"),
    ],
  },
  {
    slug: "renault-clio",
    category: "cars",
    brand: "Renault",
    model: "Clio",
    year: 2023,
    name: ls("Renault Clio"),
    tagline: ls("Comfortable manual hatch with a usable boot", "Άνετο χειροκίνητο με πρακτικό πορτμπαγκάζ"),
    description: ls("A step up in space from the city cars without becoming awkward in Chora. Comfortable over distance, which matters on the longer runs to Apollonas and the east coast.", "Ένα σκαλί πιο ευρύχωρο από τα μικρά αστικά, χωρίς να δυσκολεύει στη Χώρα. Άνετο στις μεγάλες αποστάσεις, κάτι που μετράει στις διαδρομές προς Απόλλωνα και την ανατολική ακτή."),
    image: "/images/fleet/renault-clio.jpg",
    seats: 5, doors: 5, transmission: "manual", fuelType: "gasoline", engineCC: 1000,
    luggageLarge: 3, luggageSmall: 4, bookable: true,
    features: [
      ls("Air conditioning", "Κλιματισμός"),
      ls("Bluetooth", "Bluetooth"),
      ls("USB charging", "Φόρτιση USB"),
    ],
    bestFor: [
      ls("Couples", "Ζευγάρια"),
      ls("Beach days", "Ημέρες στην παραλία"),
      ls("Longer drives", "Μεγαλύτερες διαδρομές"),
    ],
  },
  {
    slug: "renault-captur",
    category: "cars",
    brand: "Renault",
    model: "Captur",
    year: 2023,
    name: ls("Renault Captur SUV"),
    tagline: ls("Compact SUV with a high seating position", "Compact SUV με ψηλή θέση οδήγησης"),
    description: ls("The high seating position is the real benefit on Naxos: better sightlines over stone walls on the village roads, and easier loading at the port. Compact enough to still park in Chora.", "Η ψηλή θέση οδήγησης είναι το πραγματικό πλεονέκτημα στη Νάξο: καλύτερη ορατότητα πάνω από τις πέτρινες μάντρες στους δρόμους των χωριών και ευκολότερο φόρτωμα στο λιμάνι. Αρκετά μικρό ώστε να παρκάρει ακόμη στη Χώρα."),
    image: "/images/fleet/renault-captur.jpg",
    seats: 5, doors: 5, transmission: "manual", fuelType: "gasoline", engineCC: 1000,
    bookingGroup: "D", luggageLarge: 3, luggageSmall: 5, bookable: true,
    features: [
      ls("Air conditioning", "Κλιματισμός"),
      ls("Bluetooth", "Bluetooth"),
      ls("USB charging", "Φόρτιση USB"),
    ],
    bestFor: [
      ls("Villages", "Χωριά"),
      ls("Families", "Οικογένειες"),
      ls("Comfort", "Άνεση"),
    ],
  },
  {
    slug: "hyundai-i10-automatic",
    category: "cars",
    brand: "Hyundai",
    model: "i10",
    year: 2024,
    name: ls("Hyundai i10 Automatic"),
    tagline: ls("The easiest automatic to park in Chora", "Το πιο εύκολο αυτόματο για παρκάρισμα στη Χώρα"),
    description: ls("Our most requested automatic. Small enough for the Chora alleys, light steering for unfamiliar roads, and no clutch on the switchbacks. Book early: automatic availability is the first thing to run out in August.", "Το πιο ζητούμενο αυτόματό μας. Αρκετά μικρό για τα στενά της Χώρας, ελαφρύ τιμόνι για άγνωστους δρόμους και χωρίς συμπλέκτη στις στροφές. Κάντε έγκαιρη κράτηση: τα αυτόματα εξαντλούνται πρώτα τον Αύγουστο."),
    image: "/images/fleet/hyundai-i10-automatic.jpg",
    seats: 4, doors: 3, transmission: "automatic", fuelType: "gasoline", engineCC: 1200,
    bookingGroup: "BA", luggageLarge: 2, luggageSmall: 2, bookable: true,
    features: [
      ls("Air conditioning", "Κλιματισμός"),
      ls("Bluetooth", "Bluetooth"),
      ls("USB charging", "Φόρτιση USB"),
    ],
    bestFor: [
      ls("Couples", "Ζευγάρια"),
      ls("Chora parking", "Παρκάρισμα στη Χώρα"),
      ls("First-time visitors", "Πρώτη επίσκεψη"),
    ],
  },
  {
    slug: "ford-fiesta-automatic",
    category: "cars",
    brand: "Ford",
    model: "Fiesta EcoBoost",
    year: 2023,
    name: ls("Ford Fiesta Automatic EcoBoost"),
    tagline: ls("Automatic with more pull for the hills", "Αυτόματο με περισσότερη δύναμη στους ανηφορικούς"),
    description: ls("The EcoBoost has noticeably more pull than the small automatics, which shows on the climb to Apeiranthos with four people aboard. Still a compact footprint for the coastal villages.", "Ο EcoBoost έχει αισθητά περισσότερη δύναμη από τα μικρά αυτόματα, κάτι που φαίνεται στην ανάβαση προς Απείρανθο με τέσσερα άτομα. Παραμένει compact για τα παραλιακά χωριά."),
    image: "/images/fleet/ford-fiesta-automatic.jpg",
    seats: 5, doors: 5, transmission: "automatic", fuelType: "gasoline", engineCC: 1000,
    bookingGroup: "CA", luggageLarge: 3, luggageSmall: 4, bookable: true,
    features: [
      ls("Air conditioning", "Κλιματισμός"),
      ls("Bluetooth", "Bluetooth"),
      ls("USB charging", "Φόρτιση USB"),
    ],
    bestFor: [
      ls("Four adults", "Τέσσερις ενήλικες"),
      ls("Mountain routes", "Ορεινές διαδρομές"),
      ls("Automatic comfort", "Άνεση αυτομάτου"),
    ],
  },
  {
    slug: "fiat-panda-hybrid",
    category: "cars",
    brand: "Fiat",
    model: "Panda Hybrid",
    year: 2024,
    name: ls("Fiat Panda Hybrid"),
    tagline: ls("The Naxos classic, now a hybrid", "Ο κλασικός της Νάξου, τώρα υβριδικό"),
    description: ls("The car you see most on the island, for good reason: narrow, tall, and unbothered by a rough village lane. The hybrid drivetrain cuts fuel use on the stop-start coastal runs.", "Το αυτοκίνητο που θα δείτε περισσότερο στο νησί, και όχι τυχαία: στενό, ψηλό και αδιάφορο για έναν κακό δρόμο σε χωριό. Το υβριδικό σύνολο μειώνει την κατανάλωση στις παραλιακές διαδρομές με συχνές στάσεις."),
    image: "/images/fleet/fiat-panda-hybrid.jpg",
    seats: 5, doors: 5, transmission: "manual", fuelType: "hybrid", engineCC: 1000,
    bookingGroup: "B", luggageLarge: 2, luggageSmall: 3, bookable: true,
    features: [
      ls("Air conditioning", "Κλιματισμός"),
      ls("Bluetooth", "Bluetooth"),
      ls("USB charging", "Φόρτιση USB"),
    ],
    bestFor: [
      ls("Couples", "Ζευγάρια"),
      ls("Village lanes", "Δρόμοι χωριών"),
      ls("Fuel economy", "Οικονομία καυσίμου"),
    ],
  },
  {
    slug: "peugeot-108",
    category: "cars",
    brand: "Peugeot",
    model: "108",
    year: 2023,
    name: ls("Peugeot 108 Automatic"),
    tagline: ls("Smallest automatic, easiest parking", "Το μικρότερο αυτόματο, το ευκολότερο παρκάρισμα"),
    description: ls("If the plan is Chora, the west-coast beaches and no mountain days, this is the cheapest way to get an automatic. Two people and light luggage is the honest limit.", "Αν το πρόγραμμα είναι Χώρα, δυτικές παραλίες και χωρίς ορεινές διαδρομές, είναι ο πιο οικονομικός τρόπος να έχετε αυτόματο. Δύο άτομα με ελαφριές αποσκευές είναι το ρεαλιστικό όριο."),
    image: "/images/fleet/peugeot-108.jpg",
    seats: 4, doors: 3, transmission: "automatic", fuelType: "gasoline", engineCC: 1000,
    bookingGroup: "A", luggageLarge: 1, luggageSmall: 2, bookable: true,
    features: [
      ls("Air conditioning", "Κλιματισμός"),
      ls("Bluetooth", "Bluetooth"),
      ls("USB charging", "Φόρτιση USB"),
    ],
    bestFor: [
      ls("Two travellers", "Δύο άτομα"),
      ls("Chora parking", "Παρκάρισμα στη Χώρα"),
      ls("Short trips", "Σύντομες διαδρομές"),
    ],
  },
  {
    slug: "nissan-micra",
    category: "cars",
    brand: "Nissan",
    model: "Micra",
    year: 2023,
    name: ls("Nissan Micra"),
    tagline: ls("Five doors and a real boot, still compact", "Πέντε πόρτες και πραγματικό πορτμπαγκάζ, πάντα compact"),
    description: ls("A practical middle ground: five doors for rear access, a boot that takes three large cases, and a footprint that still fits the beach car parks in August.", "Πρακτική μέση λύση: πέντε πόρτες για εύκολη πρόσβαση πίσω, πορτμπαγκάζ για τρεις μεγάλες βαλίτσες και διαστάσεις που χωρούν ακόμη στα παραλιακά πάρκινγκ τον Αύγουστο."),
    image: "/images/fleet/nissan-micra.jpg",
    seats: 5, doors: 5, transmission: "manual", fuelType: "gasoline", engineCC: 1000,
    bookingGroup: "C", luggageLarge: 3, luggageSmall: 4, bookable: true,
    features: [
      ls("Air conditioning", "Κλιματισμός"),
      ls("Bluetooth", "Bluetooth"),
      ls("USB charging", "Φόρτιση USB"),
    ],
    bestFor: [
      ls("Small families", "Μικρές οικογένειες"),
      ls("Beach days", "Ημέρες στην παραλία"),
      ls("Luggage", "Αποσκευές"),
    ],
  },
  {
    slug: "opel-corsa",
    category: "cars",
    brand: "Opel",
    model: "Corsa Turbo",
    year: 2023,
    name: ls("Opel Corsa Turbo"),
    tagline: ls("Turbo pull in a city-car footprint", "Δύναμη turbo σε μέγεθος αστικού"),
    description: ls("The turbo makes the difference on the inland climbs, where naturally aspirated city cars run out of breath with a full load. Parks like a small car in Chora.", "Ο turbo κάνει τη διαφορά στις ανηφόρες της ενδοχώρας, εκεί που τα μικρά αστικά χωρίς turbo δυσκολεύονται με πλήρες φορτίο. Παρκάρει σαν μικρό αυτοκίνητο στη Χώρα."),
    image: "/images/fleet/opel-corsa.jpg",
    seats: 5, doors: 5, transmission: "manual", fuelType: "gasoline", engineCC: 1200,
    bookingGroup: "C", luggageLarge: 1, luggageSmall: 2, bookable: true,
    features: [
      ls("Air conditioning", "Κλιματισμός"),
      ls("Bluetooth", "Bluetooth"),
      ls("USB charging", "Φόρτιση USB"),
    ],
    bestFor: [
      ls("Couples", "Ζευγάρια"),
      ls("Inland routes", "Διαδρομές ενδοχώρας"),
      ls("Easy parking", "Εύκολο παρκάρισμα"),
    ],
  },
  {
    slug: "hyundai-i10-1200",
    category: "cars",
    brand: "Hyundai",
    model: "i10 1.2",
    year: 2024,
    name: ls("Hyundai i10 1.2"),
    tagline: ls("The i10 with the bigger engine", "Το i10 με τον μεγαλύτερο κινητήρα"),
    description: ls("Same easy-to-park body as the standard i10 with more to give when the car is full and the road turns uphill. Manual gearbox, five seats.", "Το ίδιο ευκολοπάρκαρο αμάξωμα με το βασικό i10, με περισσότερα περιθώρια όταν το αυτοκίνητο είναι γεμάτο και ο δρόμος ανηφορίζει. Χειροκίνητο κιβώτιο, πέντε θέσεις."),
    image: "/images/fleet/hyundai-i10-1200.jpg",
    seats: 5, doors: 5, transmission: "manual", fuelType: "gasoline", engineCC: 1200,
    bookingGroup: "Β", luggageLarge: 2, luggageSmall: 2, bookable: true,
    features: [
      ls("Air conditioning", "Κλιματισμός"),
      ls("Bluetooth", "Bluetooth"),
      ls("USB charging", "Φόρτιση USB"),
    ],
    bestFor: [
      ls("Small families", "Μικρές οικογένειες"),
      ls("Chora parking", "Παρκάρισμα στη Χώρα"),
      ls("Hill routes", "Ανηφορικές διαδρομές"),
    ],
  },
  {
    slug: "hyundai-kona",
    category: "cars",
    brand: "Hyundai",
    model: "Kona",
    year: 2024,
    name: ls("Hyundai Kona Automatic Turbo"),
    tagline: ls("Automatic SUV with turbo pull", "Αυτόματο SUV με δύναμη turbo"),
    description: ls("An automatic with genuine reserves: the turbo holds a comfortable speed on the long climb to Apeiranthos with a full car, and the raised body makes the village approaches less tense.", "Ένα αυτόματο με πραγματικά περιθώρια: ο turbo κρατά άνετη ταχύτητα στη μεγάλη ανάβαση προς Απείρανθο με γεμάτο αυτοκίνητο, και το ψηλό αμάξωμα κάνει τις προσβάσεις στα χωριά λιγότερο αγχωτικές."),
    image: "/images/fleet/hyundai-kona.jpg",
    seats: 5, doors: 5, transmission: "automatic", fuelType: "gasoline", engineCC: 99,
    bookingGroup: "DA", luggageLarge: 3, luggageSmall: 5, bookable: true,
    features: [
      ls("Air conditioning", "Κλιματισμός"),
      ls("Bluetooth", "Bluetooth"),
      ls("USB charging", "Φόρτιση USB"),
    ],
    bestFor: [
      ls("Mountain villages", "Ορεινά χωριά"),
      ls("Families", "Οικογένειες"),
      ls("Automatic comfort", "Άνεση αυτομάτου"),
    ],
  },
  {
    slug: "opel-frontera",
    category: "cars",
    brand: "Opel",
    model: "Frontera",
    year: 2025,
    name: ls("Opel Frontera SUV Automatic Turbo"),
    tagline: ls("Most luggage space in the fleet", "Ο μεγαλύτερος χώρος αποσκευών του στόλου"),
    description: ls("The choice when luggage is the constraint: four large cases and eight cabin bags, which no other car in the fleet comes close to. Automatic, hybrid, and raised for the village roads.", "Η επιλογή όταν το θέμα είναι οι αποσκευές: τέσσερις μεγάλες βαλίτσες και οκτώ χειραποσκευές, νούμερα που δεν πλησιάζει κανένα άλλο αυτοκίνητο του στόλου. Αυτόματο, υβριδικό και ψηλό για τους δρόμους των χωριών."),
    image: "/images/fleet/opel-frontera.jpg",
    seats: 5, doors: 5, transmission: "automatic", fuelType: "hybrid", engineCC: 1200,
    bookingGroup: "DA", luggageLarge: 4, luggageSmall: 8, bookable: true,
    features: [
      ls("Air conditioning", "Κλιματισμός"),
      ls("Bluetooth", "Bluetooth"),
      ls("USB charging", "Φόρτιση USB"),
    ],
    bestFor: [
      ls("Maximum luggage", "Μέγιστες αποσκευές"),
      ls("Families", "Οικογένειες"),
      ls("Airport runs", "Μεταφορές αεροδρομίου"),
    ],
  },
];

export const VEHICLES_BY_SLUG = Object.fromEntries(VEHICLES.map((v) => [v.slug, v]));

export function vehiclesByCategory(category: Vehicle["category"]) {
  return VEHICLES.filter((v) => v.category === category);
}

/**
 * Lowest published shoulder rate in a list, or undefined when none of the
 * vehicles has an owner-confirmed price. Callers must render "check
 * availability" for undefined rather than falling back to 0, which would
 * advertise a free rental.
 */
export function minShoulderPrice(list: Vehicle[]): number | undefined {
  const prices = list.map((v) => v.priceShoulder).filter((p): p is number => p != null);
  return prices.length ? Math.min(...prices) : undefined;
}

export function maxHighPrice(list: Vehicle[]): number | undefined {
  const prices = list.map((v) => v.priceHigh).filter((p): p is number => p != null);
  return prices.length ? Math.max(...prices) : undefined;
}

/** Vehicles the booking engine currently offers. */
export const BOOKABLE_VEHICLES = VEHICLES.filter((v) => v.bookable !== false);
