import type { Location } from "@/types/content";

const ls = (en: string, el?: string, it?: string, fr?: string, de?: string) => ({
  en, el: el ?? en, it: it ?? en, fr: fr ?? en, de: de ?? en,
});

export const LOCATIONS: Location[] = [
  {
    slug: "airport-pickup-jnx",
    type: "airport",
    name: ls("Naxos Airport (JNX) car rental & meet-and-greet", "Ενοικίαση αυτοκινήτου αεροδρόμιο Νάξου (JNX)", "Noleggio aeroporto di Naxos (JNX)", "Location voiture aéroport Naxos (JNX)", "Mietwagen Flughafen Naxos (JNX)"),
    shortName: "JNX Airport",
    hero: ls(
      "Free meet-and-greet at Naxos Island National Airport — under 4 km from Chora",
      "Δωρεάν παραλαβή meet-and-greet στο Εθνικό Αεροδρόμιο Νάξου — λιγότερο από 4 χλμ. από τη Χώρα",
      "Meet-and-greet gratuito all'aeroporto nazionale di Naxos — meno di 4 km da Chora",
      "Accueil gratuit à l'aéroport national de Naxos — moins de 4 km de Chora",
      "Kostenloser Meet-and-Greet am Flughafen Naxos — unter 4 km von Chora",
    ),
    body: ls(
      "Naxos Airport (IATA: JNX, ICAO: LGNX) is a small regional airport <4 km southwest of Chora. There are no permanent rental desks; major brands (Avis, Budget, Enterprise, Europcar, Hertz) only schedule meet-and-greets when a customer's flight lands. We do exactly the same — and we don't charge for it. We track your flight number, wait at arrivals with your name, hand over the keys outside the terminal in under 5 minutes. Drop-off is the reverse: leave the car keys in the agreed spot, walk to your gate.",
      "Το Αεροδρόμιο της Νάξου (JNX) είναι μικρό περιφερειακό αεροδρόμιο, λιγότερο από 4 χλμ. νοτιοδυτικά της Χώρας. Δεν υπάρχουν μόνιμα γραφεία ενοικιάσεων — αποκλειστικά παραλαβές meet-and-greet. Παρακολουθούμε τον αριθμό της πτήσης σας, σας υποδεχόμαστε στις αφίξεις με πινακίδα και παραδίδουμε τα κλειδιά σε λιγότερο από 5 λεπτά — χωρίς χρέωση. Η επιστροφή γίνεται ακριβώς αντίστροφα.",
      "L'aeroporto di Naxos (JNX) è un piccolo scalo regionale, meno di 4 km a sud-ovest di Chora. Nessun banco fisso. Tracciamo il tuo volo, ti aspettiamo agli arrivi e consegniamo l'auto in meno di 5 minuti. Gratis.",
      "L'aéroport de Naxos (JNX) est un petit aéroport régional à moins de 4 km au sud-ouest de Chora. Aucun comptoir permanent. Nous suivons ton vol, t'attendons aux arrivées, remise des clés en moins de 5 minutes. Gratuit.",
      "Der Flughafen Naxos (JNX) ist ein kleiner Regionalflughafen, weniger als 4 km südwestlich von Chora. Keine festen Schalter. Wir verfolgen Ihren Flug, warten am Ankunftsbereich und übergeben das Fahrzeug in unter 5 Minuten. Kostenlos.",
    ),
    geo: { lat: 37.0811, lng: 25.3681 },
    distanceFromChoraKm: 3.6,
    pickupTimeMinutes: 5,
    highlights: [
      ls("Free meet-and-greet (no desk fee)"),
      ls("Flight tracking — we know if you're delayed"),
      ls("Under 5 minutes from arrival to keys"),
      ls("Open whenever your flight lands"),
    ],
    nearbyVehicles: ["cars", "scooters", "atv-quad", "buggy"],
  },
  {
    slug: "port-pickup",
    type: "port",
    name: ls("Naxos Port car rental & ferry pickup", "Ενοικίαση λιμάνι Νάξου", "Noleggio porto di Naxos", "Location port Naxos", "Mietwagen Hafen Naxos"),
    shortName: "Naxos Port",
    hero: ls(
      "2-minute walk from the ferry — keys ready when you step off",
      "2 λεπτά με τα πόδια από το πλοίο — τα κλειδιά σας περιμένουν όταν κατεβαίνετε",
      "2 minuti dalla nave — chiavi pronte allo sbarco",
      "À 2 min du ferry — clés prêtes à la descente",
      "2 Minuten vom Fährhafen — Schlüssel bei Ankunft bereit",
    ),
    body: ls(
      "Most ferries from Athens (Piraeus and Rafina) and the surrounding Cyclades dock at Naxos Port in Chora. Our office is a 2-minute walk from the ferry ramp. Send us your ETA on WhatsApp the day before — we'll meet you with the keys, paperwork already filled in.",
      "Τα περισσότερα πλοία από την Αθήνα (Πειραιά και Ραφήνα), αλλά και από τις γειτονικές Κυκλάδες, προσεγγίζουν στο λιμάνι της Χώρας. Το γραφείο μας απέχει μόλις 2 λεπτά με τα πόδια από τη ράμπα του πλοίου. Στείλτε μας την εκτιμώμενη ώρα άφιξης στο WhatsApp την προηγούμενη ημέρα και θα σας υποδεχθούμε με τα χαρτιά ήδη συμπληρωμένα.",
      "La maggior parte dei traghetti da Pireo e Rafina arriva al porto di Chora. Il nostro ufficio è a 2 minuti. Mandaci l'ETA su WhatsApp.",
      "La plupart des ferries de Pirée et Rafina arrivent au port de Chora. Notre bureau est à 2 minutes. Envoie ton ETA sur WhatsApp.",
      "Die meisten Fähren aus Piräus und Rafina laufen den Hafen Chora an. Unser Büro ist 2 Minuten entfernt. Sende uns die ETA per WhatsApp.",
    ),
    geo: { lat: 37.1075, lng: 25.3801 },
    distanceFromChoraKm: 0.2,
    pickupTimeMinutes: 2,
    highlights: [ls("2-minute walk from ferry"), ls("Drop-off as easy as walking back"), ls("WhatsApp ETA — keys ready"), ls("Free parking right outside")],
    nearbyVehicles: ["cars", "scooters", "atv-quad", "buggy"],
  },
  {
    slug: "naxos-town",
    type: "village",
    name: ls("Car rental Naxos Town (Chora)", "Ενοικίαση αυτοκινήτου Χώρα Νάξου", "Noleggio auto a Naxos città (Chora)", "Location voiture Naxos ville (Chora)", "Mietwagen Naxos-Stadt (Chora)"),
    shortName: "Chora",
    hero: ls(
      "The capital — and where our office sits",
      "Η πρωτεύουσα — και η έδρα μας",
      "La capitale — e la nostra sede",
      "La capitale — et notre siège",
      "Die Hauptstadt — unser Sitz",
    ),
    body: ls(
      "Chora is Naxos's main town: the Portara, the marble pedestrian streets, the harbour-side tavernas. Free delivery to any hotel, Airbnb or villa within Chora.",
      "Η Χώρα είναι η πρωτεύουσα της Νάξου: η θρυλική Πορτάρα, τα μαρμάρινα στενά πεζόδρομοι και οι παραλιακές ταβέρνες. Δωρεάν παράδοση σε κάθε ξενοδοχείο, Airbnb ή βίλα εντός της Χώρας.",
      "Chora è la città principale di Naxos.",
      "Chora est la ville principale de Naxos.",
      "Chora ist die Hauptstadt von Naxos.",
    ),
    geo: { lat: 37.1036, lng: 25.3771 },
    distanceFromChoraKm: 0,
    pickupTimeMinutes: 5,
    highlights: [ls("Free delivery to any Chora address"), ls("Office walk-in welcome"), ls("Best beach base"), ls("Closest to the ferry & airport")],
    nearbyVehicles: ["cars", "scooters", "atv-quad", "buggy"],
  },
  {
    slug: "agios-prokopios",
    type: "beach",
    name: ls("Car rental Agios Prokopios", "Ενοικίαση Αγίου Προκοπίου", "Noleggio Agios Prokopios", "Location Agios Prokopios", "Mietwagen Agios Prokopios"),
    shortName: "Agios Prokopios",
    hero: ls(
      "Naxos's most-loved beach — and our most-requested delivery zone",
      "Η πιο αγαπημένη παραλία της Νάξου — και η πιο ζητούμενη ζώνη παράδοσης",
      "La spiaggia più amata di Naxos",
      "La plage la plus aimée de Naxos",
      "Naxos' beliebtester Strand",
    ),
    body: ls(
      "Agios Prokopios is the long, fine-sand beach 5 km south of Chora. Most visitors here pick a small automatic car or a scooter — the road into Chora is busy in summer.",
      "Ο Άγιος Προκόπιος είναι η μακριά, αμμώδης παραλία 5 χλμ. νότια της Χώρας. Οι περισσότεροι επισκέπτες εδώ επιλέγουν ένα μικρό αυτόματο αυτοκίνητο ή ένα scooter — ο δρόμος προς τη Χώρα έχει αρκετή κίνηση το καλοκαίρι.",
      "Agios Prokopios è la lunga spiaggia di sabbia 5 km a sud di Chora.",
      "Agios Prokopios est la longue plage de sable à 5 km au sud de Chora.",
      "Agios Prokopios ist der lange Sandstrand 5 km südlich von Chora.",
    ),
    geo: { lat: 37.0728, lng: 25.3647 },
    distanceFromChoraKm: 5,
    pickupTimeMinutes: 10,
    highlights: [ls("Free hotel delivery"), ls("Scooter-friendly"), ls("10 mins from Chora")],
    nearbyVehicles: ["cars", "scooters", "atv-quad"],
  },
  {
    slug: "agia-anna",
    type: "beach",
    name: ls("Car rental Agia Anna", "Ενοικίαση Αγία Άννα", "Noleggio Agia Anna", "Location Agia Anna", "Mietwagen Agia Anna"),
    shortName: "Agia Anna",
    hero: ls("Beach village blending into Agios Prokopios", "Παραλιακό χωριό που συνδέεται με τον Άγιο Προκόπιο", "Villaggio balneare", "Village balnéaire", "Strandort"),
    body: ls(
      "Agia Anna sits at the southern end of the Agios Prokopios beach. Quieter, more local, with a working fishing harbour. Free delivery here too.",
      "Η Αγία Άννα βρίσκεται στο νότιο άκρο της παραλίας του Αγίου Προκοπίου. Πιο ήσυχη, πιο αυθεντική, με ενεργό αλιευτικό λιμανάκι. Δωρεάν παράδοση και εδώ.",
      "Agia Anna si trova all'estremo sud di Agios Prokopios.",
      "Agia Anna se trouve à l'extrémité sud d'Agios Prokopios.",
      "Agia Anna liegt am Südende von Agios Prokopios.",
    ),
    geo: { lat: 37.063, lng: 25.366 },
    distanceFromChoraKm: 6,
    pickupTimeMinutes: 12,
    highlights: [ls("Quieter than Prokopios"), ls("Fishing harbour"), ls("Free delivery")],
    nearbyVehicles: ["cars", "scooters", "atv-quad"],
  },
  {
    slug: "plaka",
    type: "beach",
    name: ls("Car rental Plaka beach", "Ενοικίαση Πλάκα", "Noleggio Plaka", "Location Plaka", "Mietwagen Plaka"),
    shortName: "Plaka",
    hero: ls("4 km of fine sand, far enough from town to feel wild", "4 χλμ. ψιλή χρυσαφένια άμμος, αρκετά μακριά από την πόλη για να μοιάζει άγρια", "4 km di sabbia fine", "4 km de sable fin", "4 km feiner Sand"),
    body: ls(
      "Plaka is the long, less-developed beach beyond Agia Anna. Free delivery, easier parking, beachfront tavernas.",
      "Η Πλάκα είναι η μακριά, λιγότερο τουριστικά αναπτυγμένη παραλία πέρα από την Αγία Άννα. Δωρεάν παράδοση, εύκολο πάρκινγκ και ταβέρνες στην παραλία.",
      "Plaka è la spiaggia lunga e meno sviluppata.",
      "Plaka est la longue plage moins développée.",
      "Plaka ist der lange weniger erschlossene Strand.",
    ),
    geo: { lat: 37.0517, lng: 25.3631 },
    distanceFromChoraKm: 8,
    pickupTimeMinutes: 15,
    highlights: [ls("Quietest of the main beaches"), ls("Beachfront tavernas"), ls("Easy parking")],
    nearbyVehicles: ["cars", "scooters", "atv-quad", "buggy"],
  },
  {
    slug: "stelida",
    type: "village",
    name: ls("Car rental Stelida", "Ενοικίαση Στελίδα", "Noleggio Stelida", "Location Stelida", "Mietwagen Stelida"),
    shortName: "Stelida",
    hero: ls("Hilltop villas — only a car gets you down to the beach quickly", "Βίλες στο λόφο — μόνο με αυτοκίνητο κατεβαίνετε γρήγορα στην παραλία", "Ville sulla collina — auto necessaria", "Villas sur la colline — voiture nécessaire", "Hügelvillen — Auto nötig"),
    body: ls(
      "Stelida is the hill above Agios Prokopios full of villas and the new Wyndham resort. Steep streets — small automatic recommended.",
      "Η Στελίδα είναι ο λόφος πάνω από τον Άγιο Προκόπιο, γεμάτος με βίλες και το νέο resort Wyndham. Οι απότομοι δρόμοι καθιστούν ένα μικρό αυτόματο αυτοκίνητο τη σωστή επιλογή.",
      "Stelida è la collina sopra Agios Prokopios con ville e resort.",
      "Stelida est la colline au-dessus d'Agios Prokopios avec villas et resort.",
      "Stelida ist der Hügel über Agios Prokopios mit Villen und Resort.",
    ),
    geo: { lat: 37.0848, lng: 25.3578 },
    distanceFromChoraKm: 4,
    pickupTimeMinutes: 10,
    highlights: [ls("Steep streets — auto recommended"), ls("5 min from beaches"), ls("Best sunsets")],
    nearbyVehicles: ["cars", "scooters"],
  },
  {
    slug: "mikri-vigla",
    type: "beach",
    name: ls("Car rental Mikri Vigla", "Ενοικίαση Μικρή Βίγλα", "Noleggio Mikri Vigla", "Location Mikri Vigla", "Mietwagen Mikri Vigla"),
    shortName: "Mikri Vigla",
    hero: ls("Windsurf and kitesurf central — buggies and ATVs shine here", "Κέντρο windsurf — buggy και ATV", "Centro windsurf — buggy e ATV", "Centre windsurf — buggys et ATV", "Windsurf-Zentrum — Buggys und ATVs"),
    body: ls(
      "Mikri Vigla is the wind-blasted south-west beach famous for kitesurfing. Long unpaved access roads make ATVs and buggies a great choice. About 17 km from Chora.",
      "Η Μικρή Βίγλα είναι η ανεμόδαρτη νοτιοδυτική παραλία, διάσημη για το kitesurf. Οι εκτεταμένοι χωματόδρομοι πρόσβασης καθιστούν τα ATV και τα buggy ιδανική επιλογή. Απέχει περίπου 17 χλμ. από τη Χώρα.",
      "Mikri Vigla è la spiaggia sud-ovest famosa per il kitesurf.",
      "Mikri Vigla est la plage sud-ouest célèbre pour le kitesurf.",
      "Mikri Vigla ist der südwestliche Strand für Kitesurfen.",
    ),
    geo: { lat: 37.0259, lng: 25.4123 },
    distanceFromChoraKm: 17,
    pickupTimeMinutes: 25,
    highlights: [ls("Kitesurf paradise"), ls("Buggies welcomed"), ls("Sunset over the dunes")],
    nearbyVehicles: ["cars", "atv-quad", "buggy"],
  },
  {
    slug: "apollonas",
    type: "village",
    name: ls("Car rental Apollonas", "Ενοικίαση Απόλλωνας", "Noleggio Apollonas", "Location Apollonas", "Mietwagen Apollonas"),
    shortName: "Apollonas",
    hero: ls("North-coast fishing village — the famous Kouros statue", "Βορεινό ψαροχώρι — Κούρος Απόλλωνα", "Villaggio di pescatori — Kouros", "Village de pêcheurs — Kouros", "Fischerdorf — Kouros"),
    body: ls(
      "Apollonas is 35 km from Chora, an hour's drive on winding mountain roads. Worth it for the unfinished giant Kouros and a quiet seafood lunch. A 200cc scooter or any car will do; avoid the 50cc.",
      "Ο Απόλλωνας απέχει 35 χλμ. από τη Χώρα, διαδρομή περίπου μιας ώρας σε ορεινούς δρόμους. Αξίζει για τον ημιτελή γιγαντιαίο Κούρο και για ένα ήσυχο γεύμα με θαλασσινά. Αρκεί ένα scooter 200cc ή οποιοδήποτε αυτοκίνητο — αποφύγετε το 50cc.",
      "Apollonas è a 35 km da Chora, un'ora di guida.",
      "Apollonas est à 35 km de Chora, une heure de route.",
      "Apollonas liegt 35 km von Chora, eine Stunde Fahrt.",
    ),
    geo: { lat: 37.1739, lng: 25.5603 },
    distanceFromChoraKm: 35,
    pickupTimeMinutes: 60,
    highlights: [ls("Famous Kouros"), ls("Quiet seafood lunch"), ls("Best north-coast village")],
    nearbyVehicles: ["cars", "scooters"],
  },
  {
    slug: "filoti",
    type: "village",
    name: ls("Car rental Filoti", "Ενοικίαση Φιλώτι", "Noleggio Filoti", "Location Filoti", "Mietwagen Filoti"),
    shortName: "Filoti",
    hero: ls("Mountain village under Mt Zas — the heart of Tragea", "Ορεινό χωριό κάτω από τον Ζα", "Villaggio montano sotto il Monte Zas", "Village de montagne sous le mont Zas", "Bergdorf am Fuße des Zas"),
    body: ls(
      "Filoti is the gateway to Mount Zas, Cave of Zeus, and the Tragea olive valley. A small automatic car handles the climb easily.",
      "Το Φιλώτι αποτελεί την πύλη προς τον Ζα, τη σπηλιά του Διός και την ελαιοφόρο κοιλάδα της Τραγαίας. Ένα μικρό αυτόματο αυτοκίνητο ανταποκρίνεται άνετα στην ανήφορική διαδρομή.",
      "Filoti è la porta verso il Monte Zas e la Tragea.",
      "Filoti est la porte vers le mont Zas et Tragea.",
      "Filoti ist das Tor zum Berg Zas und Tragea.",
    ),
    geo: { lat: 37.0508, lng: 25.4836 },
    distanceFromChoraKm: 19,
    pickupTimeMinutes: 30,
    highlights: [ls("Mt Zas trailhead"), ls("Tragea olive valley"), ls("Tavernas under plane trees")],
    nearbyVehicles: ["cars", "scooters"],
  },
  {
    slug: "apeiranthos",
    type: "village",
    name: ls("Car rental Apeiranthos", "Ενοικίαση Απείρανθος", "Noleggio Apeiranthos", "Location Apeiranthos", "Mietwagen Apeiranthos"),
    shortName: "Apeiranthos",
    hero: ls("Marble mountain village — the most photographed of the inland", "Μαρμάρινο ορεινό χωριό", "Villaggio marmoreo di montagna", "Village montagnard en marbre", "Marmorbergdorf"),
    body: ls(
      "Apeiranthos sits at 600 m altitude, 28 km east of Chora. Marble streets, museums, balcony tavernas. The Filoti–Apeiranthos drive is the iconic Naxos road trip.",
      "Ο Απείρανθος βρίσκεται στα 600 μέτρα υψόμετρο, 28 χλμ. ανατολικά της Χώρας. Μαρμάρινα στενά, μουσεία και ταβέρνες με θέα από τα μπαλκόνια. Η διαδρομή Φιλώτι–Απείρανθος είναι το εμβληματικό road trip της Νάξου.",
      "Apeiranthos sorge a 600 m di altitudine.",
      "Apeiranthos est à 600 m d'altitude.",
      "Apeiranthos liegt auf 600 m Höhe.",
    ),
    geo: { lat: 37.072, lng: 25.526 },
    distanceFromChoraKm: 28,
    pickupTimeMinutes: 45,
    highlights: [ls("Marble streets"), ls("Mountain views"), ls("Iconic drive")],
    nearbyVehicles: ["cars", "scooters"],
  },
  {
    slug: "chalki",
    type: "village",
    name: ls("Car rental Chalki", "Ενοικίαση Χαλκί", "Noleggio Chalki", "Location Chalki", "Mietwagen Chalki"),
    shortName: "Chalki",
    hero: ls("Tragea's neoclassical heart — and the Vallindras kitron distillery", "Νεοκλασική Τραγαία — αποστακτήριο Βαλληνδρά", "Cuore neoclassico di Tragea — distilleria Vallindras", "Cœur néoclassique de Tragea — distillerie Vallindras", "Neoklassisches Tragea — Vallindras-Brennerei"),
    body: ls(
      "Chalki is the prettiest of the inland villages, lined with restored neoclassical mansions and the historic Vallindras citron distillery. 16 km from Chora.",
      "Το Χαλκί είναι το ομορφότερο από τα εσωτερικά χωριά, με αναπαλαιωμένα νεοκλασικά αρχοντικά και το ιστορικό αποστακτήριο κίτρου Βαλληνδρά. 16 χλμ. από τη Χώρα.",
      "Chalki è il più bello dei villaggi interni.",
      "Chalki est le plus beau des villages intérieurs.",
      "Chalki ist das schönste der Bergdörfer.",
    ),
    geo: { lat: 37.0566, lng: 25.4708 },
    distanceFromChoraKm: 16,
    pickupTimeMinutes: 25,
    highlights: [ls("Neoclassical mansions"), ls("Kitron tasting"), ls("Tragea base")],
    nearbyVehicles: ["cars", "scooters"],
  },
];

export const LOCATIONS_BY_SLUG = Object.fromEntries(LOCATIONS.map((l) => [l.slug, l]));
